### ISSUE TITLE
hardcoded gstreamer video input source 

### ISSUE THREAD

**Issue by misi** [EricssonResearch/openwebrtc#107]
AFAIU gstreamer audio/video source is hardcoded in OpenWebRTC.
Please make it parametrizable not hardcoded, and allow to use other gstreamer modul as video src/sink.

The use case:
I want to use Black Magic Decklink captrue card for audio/video src&sink with openwebrtc stack on linux. Blackmagic Decklink card has a gstreamer modul, but no v4l2 dirver implementation.

And i find that v4l2 source is hardcoded in the source: 
owr_local_media_source.c 
```
#if defined(__APPLE__) && !TARGET_IPHONE_SIMULATOR
#define AUDIO_SRC "osxaudiosrc"
#define VIDEO_SRC "avfvideosrc"

#elif defined(__ANDROID__)
#define AUDIO_SRC "openslessrc"
#define VIDEO_SRC "androidvideosource"

#elif defined(__linux__)
#define AUDIO_SRC  "pulsesrc"
#define VIDEO_SRC  "v4l2src"

#else
#define AUDIO_SRC  "audiotestsrc"
#define VIDEO_SRC  "videotestsrc"
#endif
```

**Comment by superdump** [comment]
I have a plan to create a custom GStreamer media source and media renderer that has a property on which you can set a GstElement. The GstElement will have to behave in a particular way and its state should be managed by the media source/renderer object, but you can set properties and whatnot on it.

**Comment by sdroege** [comment]
https://github.com/EricssonResearch/openwebrtc/issues/221

**Comment by superdump** [comment]
Please track this in #221. Closing.
