### ISSUE TITLE
Obsolete URL for libvpx build > Bootstrapping *and* Building Dependencies on OS X Fail

### ISSUE THREAD

**Issue by doyleindustries** [EricssonResearch/openwebrtc#120]
Mac OS: 10.10.1 Build 14B25 (Yosemite)
Xcode (w/Tools): 6.1.1 (6A2008a) 
Git: 2.2.2

Build error: 

Cloning into 'libvpx'...
fatal: unable to access 'http://git.chromium.org/webm/libvpx.git/': Illegal or missing hexadecimal sequence in chunked-encoding
./build-libvpx.sh: line 16: pushd: libvpx: No such file or directory
fatal: ambiguous argument 'v1.3.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: bad object 33df6d1fc1d268b4901b74b4141f83594266f041
Failed to cherry-pick patch

Issue: URL "http://git.chromium.org/webm/libvpx.git/" is obsolete (9 days).

Fix: New URL for libvpx: https://git.chromium.org/git/webm/libvpx.git

**Comment by stefanalund** [comment]
Would you mind submitting a Pull Request? Otherwise we will fix it on Monday. Thanks

**Comment by doyleindustries** [comment]
We've neither had the time to study the code in any appreciable depth nor locally modify, much less commit, our own local fork.

We can assure, however, that the current libvpx URL clones successfully and the old one is indeed obsolete.

**Comment by stefanalund** [comment]
Ok, thanks!

**Comment by superdump** [comment]
`build-libvpx.sh` contains the command `git clone http://git.chromium.org/webm/libvpx.git`. I tested that and:

```
$ git clone http://git.chromium.org/webm/libvpx.git
Cloning into 'libvpx'...
remote: Counting objects: 85811, done.
remote: Compressing objects: 100% (34532/34532), done.
remote: Total 85811 (delta 69608), reused 65923 (delta 50762)
Receiving objects: 100% (85811/85811), 32.62 MiB | 1.61 MiB/s, done.
Resolving deltas: 100% (69608/69608), done.
Checking connectivity... done.
```

Works for me with current scripts. Maybe it was a temporary issue? Closing.

**Comment by doyleindustries** [comment]
It’s not temporary. I don’t know why it’s working with your current scripts but coming fresh to this project, I had to insert the new URL into the libvpx build script — once I did, all went well.

Once again, the new URL:

https://git.chromium.org/git/webm/libvpx.git <https://git.chromium.org/git/webm/libvpx.git>


Regards

**Comment by sdroege** [comment]
It also works for me, even outside the scripts, e.g.: git clone http://git.chromium.org/webm/libvpx.git
Not sure what the problem here is for you.
