### ISSUE TITLE
build failing for osx / iOS / iOS-simulator

### ISSUE THREAD

**Issue by agouaillard** [EricssonResearch/openwebrtc#134]
following the wiki,
bootstrap ok, 
dependencies ok,
then (it looks like the "gst_debug_bin_to_dot_data" function declaration was not found):

/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in transport
  CC       owr_candidate.lo
  CC       owr_payload.lo
  CC       owr_audio_payload.lo
  CC       owr_video_payload.lo
  CC       owr_session.lo
  CC       owr_media_session.lo
  CC       owr_transport_agent.lo
/Users/agouaillard/DEVEL/GITROOT/openwebrtc/transport/owr_transport_agent.c:2128:12: error: 
      implicit declaration of function 'gst_debug_bin_to_dot_data' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    return gst_debug_bin_to_dot_data(GST_BIN(transport_agent->priv->pipeline), GST_DEBUG_GRA...
           ^
/Users/agouaillard/DEVEL/GITROOT/openwebrtc/transport/owr_transport_agent.c:2128:12: note: did you
      mean 'gst_debug_bin_to_dot_file'?
/Users/agouaillard/DEVEL/GITROOT/openwebrtc/openwebrtc-deps-x86_64-osx/include/gstreamer-1.0/gst/gstdebugutils.h:54:6: note: 
      'gst_debug_bin_to_dot_file' declared here
void gst_debug_bin_to_dot_file (GstBin *bin, GstDebugGraphDetails details, const gchar *file_name);
     ^
/Users/agouaillard/DEVEL/GITROOT/openwebrtc/transport/owr_transport_agent.c:2128:12: error: 
      incompatible integer to pointer conversion returning 'int' from a function with result type
      'gchar *' (aka 'char *') [-Werror,-Wint-conversion]
  ...gst_debug_bin_to_dot_data(GST_BIN(transport_agent->priv->pipeline), GST_DEBUG_GRAPH_SHOW_ALL);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [owr_transport_agent.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Failed building....

**Comment by stefanalund** [comment]
Are you including the simulator? If so, could you please try removing it from the list. There has been problems with it in the past.

**Comment by agouaillard** [comment]
same same:

alexandres-MacBook-Air:openwebrtc agouaillard$ ./build.sh -r osx ios
[...]

Now type 'make' to compile this module.

patching file libtool
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in transport
  CC       owr_transport_agent.lo
/Users/agouaillard/DEVEL/GITROOT/openwebrtc/transport/owr_transport_agent.c:2128:12: error: 
      implicit declaration of function 'gst_debug_bin_to_dot_data' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    return gst_debug_bin_to_dot_data(GST_BIN(transport_agent->priv->pipeline), GST_DEBUG_GRA...
           ^
/Users/agouaillard/DEVEL/GITROOT/openwebrtc/transport/owr_transport_agent.c:2128:12: note: did you
      mean 'gst_debug_bin_to_dot_file'?
/Users/agouaillard/DEVEL/GITROOT/openwebrtc/openwebrtc-deps-x86_64-osx/include/gstreamer-1.0/gst/gstdebugutils.h:54:6: note: 
      'gst_debug_bin_to_dot_file' declared here
void gst_debug_bin_to_dot_file (GstBin *bin, GstDebugGraphDetails details, const gchar *file_name);
     ^
/Users/agouaillard/DEVEL/GITROOT/openwebrtc/transport/owr_transport_agent.c:2128:12: error: 
      incompatible integer to pointer conversion returning 'int' from a function with result type
      'gchar *' (aka 'char *') [-Werror,-Wint-conversion]
  ...gst_debug_bin_to_dot_data(GST_BIN(transport_agent->priv->pipeline), GST_DEBUG_GRAPH_SHOW_ALL);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [owr_transport_agent.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Failed building....

**Comment by agouaillard** [comment]
ok, since I'm stuck at the airport, I investigated further.

the gst_debug_bin_to_dot_data function has only been added to streamer on december 12, 2014:
http://static-173-79-223-25.washdc.fios.verizon.net/?l=gstreamer-cvs&m=141838844118058&w=4

the Gstreamer version used in openWebRTC.io is 1.0 and much older than this:
/openwebrtc/openwebrtc-deps-x86_64-osx/include/gstreamer-1.0/gst/gstdebugutils.h

I guess the developer of openwebrtc/transport/owr_transport_agent.c is using locally a dev version of GStreamer and did not realized it wouldn't work. 

Git blame point to Per-Erik Brodin, with commit 49069e0e on December 15th, 2014.

49069e0e (Per-Erik Brodin  2014-12-15 23:22:43 +0100 2123) gchar * owr_transport_agent_get_dot_data(
478b8b1d (Sebastian Dröge  2014-10-29 18:02:08 +0100 2124) {
49069e0e (Per-Erik Brodin  2014-12-15 23:22:43 +0100 2125)     g_return_val_if_fail(OWR_IS_TRANSPORT
49069e0e (Per-Erik Brodin  2014-12-15 23:22:43 +0100 2126)     g_return_val_if_fail(transport_agent-
478b8b1d (Sebastian Dröge  2014-10-29 18:02:08 +0100 2127) 
49069e0e (Per-Erik Brodin  2014-12-15 23:22:43 +0100 2128)     return gst_debug_bin_to_dot_data(GST_
478b8b1d (Sebastian Dröge  2014-10-29 18:02:08 +0100 2129) }

Hope this helps. See you tomorrow.

**Comment by Rugvip** [comment]
The folder is called gstreamer-1.0, but it's really GStreamer 1.4. It's because there was a pretty big jump between GStreamer 0.10 and 1.0, so all binaries etc where suffixed with 1.0.

OpenWebRTC currently uses the latest commit on GStreamer master https://github.com/EricssonResearch/openwebrtc-build-scripts/blob/master/dependencies/build-gstreamer.sh -> http://cgit.freedesktop.org/gstreamer/gstreamer/commit/?id=3390b70d781a7e2cfe7796e65a8a378a73d95209

You probably just need to fetch the latest version of openwebrtc and build-scripts, update the scripts submodule, and rebuild and redeploy the dependencies.

**Comment by superdump** [comment]
Indeed. We work with the GStreamer community to develop things where they should be developed if we can.

Getting the dot data instead of an API that dumped directly to a file was useful for more cleanly supporting generating media processing graphs on the fly in an application.

**Comment by superdump** [comment]
And we use recent GStreamer master to make the most of all the exciting development that happens there that enables things like the hardware acceleration on iOS, for example.

**Comment by agouaillard** [comment]
fair enough, I thought I had started from a clean clone, but in this case I hadn't.
I did update the submodules, I'm retrying now. Is there a way to avoid this in the future, so that other user don;t shoot themselves in the foot (like having one of the build script check that the scripts submodule hash is the one expected and stop if it is not)?

alexandres-MacBook-Air:openwebrtc agouaillard$ git pull --recurse-submodules
remote: Counting objects: 22, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 22 (delta 7), reused 7 (delta 3)
Unpacking objects: 100% (22/22), done.
From https://github.com/EricssonResearch/openwebrtc
   00239f8..0037bfc  master     -> origin/master
Fetching submodule scripts
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 1), reused 3 (delta 1)
Unpacking objects: 100% (8/8), done.
From https://github.com/EricssonResearch/openwebrtc-build-scripts
   d441c04..17c5635  master     -> origin/master
Updating 00239f8..0037bfc
Fast-forward
 CONTRIBUTING.md               | 59 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 bridge/Makefile.am            | 11 +++++++----
 bridge/worker/bridgeserver.js | 49 ++++++++++++++++++++++++++++++++++++++++++++++++-
 build.sh                      | 10 +++++++---
 local/Makefile.am             |  3 ++-
 scripts                       |  2 +-
 6 files changed, 124 insertions(+), 10 deletions(-)
 create mode 100644 CONTRIBUTING.md

**Comment by agouaillard** [comment]
it seems to fail. To be thorough, I will tests from a fresh clone next.

Making all in rtsp
  GEN      gstrtsp-enumtypes.h
  GEN      gstrtsp-enumtypes.c
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       libgstrtsp_1.0_la-gstrtsptransport.lo
  CC       libgstrtsp_1.0_la-gstrtspurl.lo
  CC       libgstrtsp_1.0_la-gstrtspmessage.lo
  CC       libgstrtsp_1.0_la-gstrtspconnection.lo
  CC       libgstrtsp_1.0_la-gstrtspdefs.lo
make[5]: *** No rule to make target `gstrtsp-marshal.list', needed by `gstrtsp-marshal.h'.  Stop.
make[4]: *** [all] Error 2
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Failed building...gst-plugins-base
mv gst-plugins-base gst-plugins-base_build_failed_on_150128-04:01:18_using_script_with_md5sum_785b3ea7a58ccf9bbfb16899438b5a12d9d53e72

**Comment by stefanalund** [comment]
Any luck @agouaillard?

**Comment by frozeus** [comment]
Got the same issue i updated to the latest Gstreamer plugins base.

@agouaillard Did you find a solution ?

**Comment by superdump** [comment]
@agouaillard any news?

We are working on automated builds to check that everything builds successfully all the time and we are moving to the cerbero build system. After that I expect we can close this issue. We are also looking to make releases and make binary downloads of the releases.

**Comment by superdump** [comment]
We have moved to the cerbero build system. If you have issues building with that, please create a new issue. Thanks for the report!

https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC
