### ISSUE TITLE
Pre-commit and pre-push git hooks fail on OS X

### ISSUE THREAD

**Issue by ikonst** [EricssonResearch/openwebrtc#136]
git_hooks/chain_hook is used for pre-commit and pre-push hooks.
Unfortunately it uses realpath that's unavailable on OS X.

This StackOverflow question offers some alternatives:
http://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-osx

**Comment by superdump** [comment]
@ikonst You're welcome to fix this. :)

**Comment by superdump** [comment]
This setup doesn't work with GitHub and cerbero so we'll need to come up with another solution. I'll create a new issue about enforcing code style and close this one.
