### ISSUE TITLE
Update libopus to a recent version (1.1 or higher)

### ISSUE THREAD

**Issue by ikonst** [EricssonResearch/openwebrtc#142]
Newer versions of Opus promise much improved performance:

* *speed improvements on all architectures, especially ARM, where decoding uses around 40% less CPU and encoding uses around 30% less CPU*

**Comment by superdump** [comment]
Excellent! Can you patch this in openwebrtc-build-scripts and test it?

**Comment by sdroege** [comment]
I think for those optimizations you also have to make sure they're enabled during the build.

Also updating that in cerbero now, how could we miss that :)

**Comment by superdump** [comment]
The autoconf test in the opus configure.ac uses $host_cpu. It should work to set --host=arm-apple-darwin10 for iOS but I didn't manage to get it working. The configure script output shows that the test failed but I haven't yet identified why.

**Comment by nirbheek** [comment]
Opus 1.1 is in Cerbero and compiles properly for iOS with --host=arm-apple-darwin10. Which test failed, exactly? Do you mean the test for using the ARM assembly optimization?

**Comment by superdump** [comment]
Yes. It compiles properly but without optimisations here with our build scripts. Can you check the configure script output in cerbero?

**Comment by nirbheek** [comment]
The ARM assembly optimizations are only enabled when floating point support is disabled (i.e., when Opus only uses fixed point arithmetic). However, Opus already has intrinsics/NEON support on ARM and x86, which also have improved performance in this release.

Cerbero doesn't disable floating point arithmetic; I've just added a comment to the recipe about the fixed point support.

**Comment by superdump** [comment]
We still need a patch against the build scripts but when we move to cerbero, this can be closed.

**Comment by superdump** [comment]
Moved to cerbero. Closing.
