### ISSUE TITLE
Make owr_init API usable

### ISSUE THREAD

**Issue by ikonst** [EricssonResearch/openwebrtc#143]
Using `owr_init` instead of `owr_init_with_main_context` is impractical, since (some? all?) API functions must be invoked on the thread holding the main context, but `owr_init` does not expose its main context.

For example, `owr_media_session_new` expects to acquire the owr main context during its operation, so it can only be invoked on the owr main context thread.

The way I see it, either:
* Get rid of `owr_init` since it's not useful in its current form. The more versatile `owr_init_with_main_context` should stay.
* Add API to invoke code on the "owr_main_loop" thread. This is somewhat redundant since API users are expected to know and use Glib (e.g.  `g_signal_connect`) and this will do little more than wrap `g_main_context_invoke`.

**Comment by sdroege** [comment]
Or third, add something to get the Owr main context so applications know what to use.

I would get rid of owr_init() though, or at least make it just call owr_init_with_main_context() with the default main context. Every other behaviour is just unexpected.

**Comment by sdroege** [comment]
I think there should just be an owr_init() that uses the current thread default main context (or the default one otherwise). And the current dance with the thread and running a custom mainloop there and stuff should be inside the application, or become a owr_init_and_run_in_background() around the new owr_init().

**Comment by sdroege** [comment]
@superdump ?

**Comment by ikonst** [comment]
OK, not sure about `owr_media_session_new`, but here's one:
https://github.com/EricssonResearch/openwebrtc/issues/225

**Comment by superdump** [comment]
I'll figure out what this should be, taking into account suggestions, soon. It will be done before the first release at least. :)

**Comment by superdump** [comment]
Done by @Rugvip
