### ISSUE TITLE
Problems linking with Xcode to static libraries produced by cerbero

### ISSUE THREAD

**Issue by ikonst** [EricssonResearch/openwebrtc#148]
cerbero outputs both static and dynamic libraries into e.g. cerbero/dist/ios_universal/lib:
...
libglib-2.0.a
libglib-2.0.la
libglib-2.0.0.dylib
libglib-2.0.dylib -> libglib-2.0.0.dylib
...

I'm not using OpenWebRTC.framework since using it's currently cumbersome, especially when actively working on the code. Instead, I'm adding $(HOME)/cerbero/dist/ios_universal/lib to the Library Search Paths, and adding the .a files to the Xcode project.

Unfortunately, Xcode emits '-lglib-2.0' for such references, which instead ends up linked to the dylib. If I either move the .dylib files or .a files aside, the problem is solved.

We already have lib/gstreamer-1.0/static; can we have lib/static for the other libs as well?

**Comment by sdroege** [comment]
The .dylibs are not included in the packages created by cerbero. You're not supposed to use the build tree for development, but the real framework that is created by the packaging process. This also contains a static wrapper library ("GStreamer") that contains all the static libraries and GStreamer plugins.
