### ISSUE TITLE
cerbero should not produce dylibs on iOS configurations

### ISSUE THREAD

**Issue by ikonst** [EricssonResearch/openwebrtc#151]
Dynamic libraries are discouraged on iOS. As for iOS 8 they're allowed, but still it's assumed most developers would want static libraries.

Given the complexities brought by .dylib and .a coexistence (see https://github.com/EricssonResearch/openwebrtc/issues/148), can we just drop dylib building from cerbero iOS configs? This will also save significant build time.

**Comment by sdroege** [comment]
They don't cause any issues and are also not included in the packages, they're just an artifact created during the build. The effect on build time should also be relatively small, but measuring that would be interesting.

If it's a big enough difference, someone can look into that and as long as it's not a too huge amount of changes that should be acceptable.

**Comment by ikonst** [comment]
a) They cause tool trouble -- see #148 
b) I see separate recipes and separate directories, i.e.
sources/ios_arm64/gst-plugins-good-1.0-1.5
sources/ios_arm64/gst-plugins-good-1.0-static-1.5

Isn't each of those getting built independently?

**Comment by sdroege** [comment]
See my comment in #148, you're not supposed to use the libraries from the build tree on iOS but the result of the packaging process afterwards. That's only including a single static library then, plus headers.

For 2), yes it would in theory be possible to do it all at once but that requires bigger changes in cerbero. We currently use the static libraries from e.g. gstreamer-1.0 and only use the static plugins from gstreamer-1.0-static.

**Comment by ikonst** [comment]
Thanks.

As you can understand, I was trying to use cerbero to the best of my understanding. My goal is to move forward with openwebrtc / ios work, so I've been employing "workarounds". Basically, I saw how cumbersome the .framework thing is, and thought that if I need to keep introducing small changes into, say, osxaudio until it works right, dealing with .frameworks every time would be counterproductive.

**Comment by sdroege** [comment]
Yeah, cerbero really has a problem of not enough documentation. Sorry that you had to spend your time on working in the wrong direction

Also I agree that regenerating the framework for every single change is quite annoying and time consuming. Unfortunately so far there's no idea for a better solution in general.
What you can do is that you compile and link the specific plugin you work on directly into your application, and only link all the others from the framework.

**Comment by ford-prefect** [comment]
For plugin development, we could probably document how to get a
gst-uninstalled setup working on OS X. Doesn't solve the problem got iOS
though.

**Comment by superdump** [comment]
You can probably use the cerbero shell just as well for that on OS X. Right?

**Comment by sdroege** [comment]
Yes

**Comment by superdump** [comment]
Closing.
