### ISSUE TITLE
cerbero shell not useful in 'universal' (fat) configurations

### ISSUE THREAD

**Issue by ikonst** [EricssonResearch/openwebrtc#152]
````
~/cerbero/cerbero-uninstalled -c config/cross-ios-universal.cbc shell
````
creates a shell whose CFLAGS, CXXFLAGS and OBJCFLAGS don't contain cross-architecture, e.g. no `-arch arm64`.

This shell is not useful for building sources manually.

**Comment by sdroege** [comment]
The shell is also useless for iOS in general :) See my comments in the other tickets.

What do you want to achieve with the shell?

**Comment by ikonst** [comment]
I'm working on gst modules. Building can be done by just invoking 'make' but if I need to re-autoconf (after editing confgiure.ac), I'm in trouble since CFLAGS etc. aren't defined as they should be. That's what I thought the shell is good for.

OTOH, the shell isn't arch-specific nor recipe-specific, so I guess it's the wrong tool for the job.

**Comment by sdroege** [comment]
Yes, for all other platforms the shell can be used for that. For iOS that's not possible as you need to re-run the packaging process after each change, recreate the fat libraries, etc. Only the results of the packaging process are usable for actual development as only that produces a real .framework.

**Comment by ikonst** [comment]
The "useless shell" is serving me rather well in iOS, of course, with the hacky Xcode project I described here:
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero#development

My plan is to distribute a hacky Xcode project as a "template", in place of all manual instructions in this terrible wiki section :)

**Comment by superdump** [comment]
Closing.
