### ISSUE TITLE
osxaudio: Does not support reconfiguration

### ISSUE THREAD

**Issue by ikonst** [EricssonResearch/openwebrtc#154]
source-1 (interaudiosrc) is *sometimes* fixed to rate:48000.

The fixing is done in ...
````c
static GstCaps *
gst_inter_audio_src_fixate (GstBaseSrc * src, GstCaps * caps)
{
  GstStructure *structure;

  GST_DEBUG_OBJECT (src, "fixate");

  caps = gst_caps_make_writable (caps);
  caps = gst_caps_truncate (caps);

  structure = gst_caps_get_structure (caps, 0);

  gst_structure_fixate_field_string (structure, "format", GST_AUDIO_NE (S16));
  gst_structure_fixate_field_nearest_int (structure, "channels", 2);
  gst_structure_fixate_field_nearest_int (structure, "rate", 48000);
  gst_structure_fixate_field_string (structure, "layout", "interleaved");

  return caps;
}
````
... and the rationale is unclear, but nevertheless the troubling thing is that the `caps` argument **randomly** (i.e. seemingly a race condition) is...

 * on "good" runs, has rate:8000 (I'm testing with PCMA)
 * on "bad" runs, has rate:1..2^32

Consequentially:

 * on "good" runs, I'm no longer hitting resampling at all
 * on "bad" runs, source-1 is fixated to rate:48000 and I experience significantly higher CPU usage due to resampling

**Comment by ikonst** [comment]
Here's what a virgin media-renderer looks like -- before caps negotiation:
![image](https://cloud.githubusercontent.com/assets/1186084/6004888/e0349ce0-ab0e-11e4-9eec-33ec70acb7d2.png)
(You can see that everybody is pretty much rate-agnostic.)

Here's what interaudiosrc looks like when it's "good":
![image](https://cloud.githubusercontent.com/assets/1186084/6004873/c15cd29c-ab0e-11e4-8f69-0a5ccf47f3a1.png)

Here's what interaudiosrc looks like when it's "bad":
![image](https://cloud.githubusercontent.com/assets/1186084/6004882/d27cad9a-ab0e-11e4-9cda-58a52fe356d7.png)

**Comment by ikonst** [comment]
After a crash course on GStreamer by @sdroege , I've realized the culprit wasn't what I thought it was.

Actually there's no harm in InterAudioSrc fixating on rate:48000, since it will reconfigure as soon as it receives data from its InterAudioSink. (Yes, there's a race condition here, but it's not what's at fault.)

The trouble is that osxaudio will not reconfigure its caps once it's playing. Actually it's totally safe to do, and this change seems to solve it:
````c
static GstCaps *
gst_osx_audio_sink_getcaps (GstBaseSink * sink, GstCaps * filter)
{
   ...
#if 0
    if (buf->acquired && buf->spec.caps) {
      /* Caps are fixed, use what we have */
      ret = gst_caps_ref (buf->spec.caps);
    }
#endif
    ....
````

The capscaps will be followed:
```` 
1. gst_audio_base_src_setcaps (not overridden by osxaudiosink)
2.  ↳ gst_audio_ring_buffer_acquire 
3.        ↳ gst_core_audio_set_format
4.             ↳ AudioUnitSetProperty
````

**Comment by ikonst** [comment]
PS. Isn't it weird that we have this race condition, regardless? Race conditions that cause the audio component to be (sometimes!) reconfigured for 48000 and afterwards 8000 doesn't sound like very healthy design.

**Comment by ford-prefect** [comment]
The reason it works this way is likely that interaudiosrc provides silence
buffers in the absence of buffers from the corresponding interaudiosink.
There is no way to predict what format will arrive later, so the
renegotiation is inevitable.

**Comment by ford-prefect** [comment]
And of course, if the caps / first buffer become available before the
interaudiosrc has to provide its first buffer, then we don't have to do any
such reconfiguration.

**Comment by ikonst** [comment]
(y)

Submitted as https://bugzilla.gnome.org/show_bug.cgi?id=743925

**Comment by superdump** [comment]
That ticket was closed and the change was pushed into GStreamer. Does that mean that this issue is now closed or is something more needed for osxaudio supporting reconfiguration?

**Comment by sdroege** [comment]
That specific issue is solved, yes. There are some more pending changes for osxaudio though.
