### ISSUE TITLE
can not build openwebrt

### ISSUE THREAD

**Issue by leonhust** [EricssonResearch/openwebrtc#158]
I cloned the latest project and build with following commands:
cd scripts/bootstrap
./bootstrap.sh -r linux
cd -
cd scripts/dependencies
./build-all.sh -Cbr linux android ios
./deploy_deps.sh
cd -
./build.sh -Cbr linux android ios

during ./deploy_deps.sh, I meet this issue:
Creating file release for ios
ls: cannot access *: No such file or directory
cp: cannot stat ‘openwebrtc-deps-armv7-ios/lib/glib-2.0/include/glibconfig.h’: No such file or directory
./build-leon.sh -- Could not create file release.

and during ./build.sh -Cbr linux android ios, I meet this one:
Now type 'make' to compile this module.

patching file libtool
Hunk #1 succeeded at 5718 (offset 3 lines).
Hunk #2 succeeded at 5964 (offset 3 lines).
Hunk #3 succeeded at 6701 (offset 3 lines).
Hunk #4 succeeded at 6874 (offset 3 lines).
Hunk #5 succeeded at 6882 (offset 3 lines).
Hunk #6 succeeded at 7556 (offset 3 lines).
Hunk #7 succeeded at 8452 (offset 3 lines).
Hunk #8 succeeded at 9182 (offset 3 lines).
make  all-recursive
make[1]: Entering directory `/home/xiaobin/YangJun/openwebrtc_new/build/x86_64-unknown-linux'
Making all in transport
make[2]: Entering directory `/home/xiaobin/YangJun/openwebrtc_new/build/x86_64-unknown-linux/transport'
  CC       owr_candidate.lo
  CC       owr_payload.lo
  CC       owr_audio_payload.lo
  CC       owr_video_payload.lo
  CC       owr_session.lo
  CC       owr_media_session.lo
  CC       owr_transport_agent.lo
  CC       owr_remote_media_source.lo
  CCLD     libopenwebrtc_transport.la
make[2]: Leaving directory `/home/xiaobin/YangJun/openwebrtc_new/build/x86_64-unknown-linux/transport'
Making all in local
make[2]: Entering directory `/home/xiaobin/YangJun/openwebrtc_new/build/x86_64-unknown-linux/local'
  CC       owr_local.lo
  CC       owr_local_media_source.lo
  CC       owr_media_renderer.lo
  CC       owr_audio_renderer.lo
  CC       owr_video_renderer.lo
  CC       owr_image_renderer.lo
  CC       owr_image_server.lo
  CC       owr_window_registry.lo
  CC       owr_device_list.lo
  OBJCLD   libopenwebrtc_local.la
make[2]: Leaving directory `/home/xiaobin/YangJun/openwebrtc_new/build/x86_64-unknown-linux/local'
Making all in owr
make[2]: Entering directory `/home/xiaobin/YangJun/openwebrtc_new/build/x86_64-unknown-linux/owr'
  CC       owr.lo
  CC       owr_types.lo
  CC       owr_media_source.lo
  CC       owr_utils.lo
python /home/xiaobin/YangJun/openwebrtc_new/owr/symbols_to_source.py /home/xiaobin/YangJun/openwebrtc_new/libopenwebrtc.exp owr_require_symbols.c
  CC       owr_require_symbols.lo
  CCLD     libopenwebrtc.la
  GISCAN Owr-0.1.gir
./.libs/libopenwebrtc.so: undefined reference to `eglCreateWindowSurface'
./.libs/libopenwebrtc.so: undefined reference to `eglBindAPI'
./.libs/libopenwebrtc.so: undefined reference to `eglCreateContext'
./.libs/libopenwebrtc.so: undefined reference to `eglMakeCurrent'
./.libs/libopenwebrtc.so: undefined reference to `eglDestroySurface'
./.libs/libopenwebrtc.so: undefined reference to `eglGetDisplay'
./.libs/libopenwebrtc.so: undefined reference to `eglChooseConfig'
./.libs/libopenwebrtc.so: undefined reference to `eglInitialize'
./.libs/libopenwebrtc.so: undefined reference to `eglGetProcAddress'
./.libs/libopenwebrtc.so: undefined reference to `eglCreatePbufferSurface'
./.libs/libopenwebrtc.so: undefined reference to `eglQueryString'
./.libs/libopenwebrtc.so: undefined reference to `eglGetCurrentContext'
./.libs/libopenwebrtc.so: undefined reference to `eglDestroyContext'
./.libs/libopenwebrtc.so: undefined reference to `eglReleaseThread'
./.libs/libopenwebrtc.so: undefined reference to `eglSwapBuffers'
./.libs/libopenwebrtc.so: undefined reference to `eglGetError'
./.libs/libopenwebrtc.so: undefined reference to `eglTerminate'
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['/bin/bash', '../libtool', '--mode=link', '--tag=CC', '--silent', 'gcc', '-o', '/home/xiaobin/YangJun/openwebrtc_new/build/x86_64-unknown-linux/owr/tmp-introspectNISbpg/Owr-0.1', '-export-dynamic', '-fPIC', '-I/home/xiaobin/YangJun/openwebrtc_new/openwebrtc-deps-x86_64-linux/include', '-I/home/xiaobin/YangJun/openwebrtc_new/framework', '-L/home/xiaobin/YangJun/openwebrtc_new/openwebrtc-deps-x86_64-linux/lib', '-L/home/xiaobin/YangJun/openwebrtc_new/openwebrtc-deps-x86_64-linux/lib/gstreamer-1.0', '-L/home/xiaobin/YangJun/openwebrtc_new/openwebrtc-deps-x86_64-linux/lib', '/home/xiaobin/YangJun/openwebrtc_new/build/x86_64-unknown-linux/owr/tmp-introspectNISbpg/Owr-0.1.o', '-L.', 'libopenwebrtc.la', '-L/home/xiaobin/.openwebrtc/lib', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0', '-lintl']' returned non-zero exit status 1
make[2]: *** [Owr-0.1.gir] Error 1
make[2]: Leaving directory `/home/xiaobin/YangJun/openwebrtc_new/build/x86_64-unknown-linux/owr'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/xiaobin/YangJun/openwebrtc_new/build/x86_64-unknown-linux'
make: *** [all] Error 2
Failed building....

**Comment by stefanalund** [comment]
You need to have a Mac and build `osx` before you attempt to build for iOS. Removing iOS from the build should solve the problem. If this is not helpful, please re-open the issue.

**Comment by leonhust** [comment]
OK, I'll have a try.
Thanks

**Comment by leonhust** [comment]
Hi stefan, 
Unfortunately, removing osx build does not help. The exact same issue happens.

My host is a 64bit ubuntu 14.04, the build steps are:
cd <root>
cd scripts/bootstrap
./bootstrap.sh -r linux
cd <root>
cd scripts/dependencies
./build-all.sh -Cbr linux android
./deploy_deps.sh
cd <root>
./build.sh -Cbr linux android

How to reopen this ticket?

**Comment by stefanalund** [comment]
@Rugvip any idea?

**Comment by superdump** [comment]
This is a recurring Linux build bug. I'll try a fresh Ubuntu and see if I can reproduce.

**Comment by frozeus** [comment]
I didn't try on ubuntu but the error is comming from the linker the symbols of libEGL.so are missing.
Maybe with adding '-lEGL' no ? or adding libEGL to the pkgconfig file.

**Comment by sdroege** [comment]
Passing --disable-egl to gst-plugins-bad' configure would be the better solution here IMHO.

**Comment by superdump** [comment]
@sdroege what packages are needed on x86 Linux for functional gstgl/glimagesink?

**Comment by sdroege** [comment]
libgl1-mesa-dev (Ubuntu/Debian) should be enough, maybe libglu1-mesa-dev too. libegl1-mesa-dev and libgles2-mesa-dev would additionally enable the EGL and GLES backends, but those won't be used by default anyway unless they are the only available ones.

**Comment by superdump** [comment]
This issue is also noted in https://github.com/EricssonResearch/openwebrtc/issues/97

**Comment by superdump** [comment]
We have now moved to cerbero as our official build system. Please try to build using that. Thanks for the issue report!

https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC
