### ISSUE TITLE
Split libopenwebrtc library into libopenwebrtc and libopenwebrtc-bridge

### ISSUE THREAD

**Issue by frozeus** [EricssonResearch/openwebrtc#159]
Hi,

Is there a way to build only the API of OpenWebRTC without Javascript binding and extra stuff ?

Thanks

**Comment by superdump** [comment]
1-2 hours on a reasonably-specced machine but not on, say a Raspberry Pi. Even the new RPi 2 is going to be pretty slow. And you probably have to sort something out for a fast swap file system in order to link JavaScriptCore, maybe. You can probably set up some cross compilation environment but that's also going to need some work in the current build system. Cerbero is the place to figure this out and do it properly.

**Comment by superdump** [comment]
Having said all that, we have demoed on the RPi though I'm not sure how @pererikb built everything.

**Comment by ikonst** [comment]
I think he's running it on Raspberry Pi, not building it :)

**Comment by stefanalund** [comment]
![image](https://cloud.githubusercontent.com/assets/190856/6035489/cf6aa252-ac34-11e4-8673-3e69c508254d.jpg)

:-)

**Comment by frozeus** [comment]
Cool project, is it open source ?

**Comment by stefanalund** [comment]
@frozeus do you mean the Raspberry Pi part? It could be, but we haven't made it available as one of our support platforms yet. It's still a bit of a hack :) If you are interested, and willing to get your hands dirty, maybe we can provide you with a patch.

We don't have any example code for running OpenWebRTC on a server, we try to limit our focus to clients. But in theory there is nothing preventing you from running the code on (Linux) server. In the picture above the RPI is running as a client.

**Comment by frozeus** [comment]
Yes i will be very interested. I think it could be a lovely solution for all raspberry pi owners, much more better than a simple rtp server with gstreamer :)

And by the way if someone is interested i successfully build with glib and gstreamer.
You just need to remove dirs 'binding, bridge, test' from the configure.ac and Makefile.am and remove some PKG_config_check in configure.ac.

**Comment by stefanalund** [comment]
Cool, we will provide some patches soon, we just need to clean them up a bit first :)

Would be great if you would document your work on the Wiki: https://github.com/EricssonResearch/openwebrtc/wiki

Thanks

**Comment by sdroege** [comment]
@frozeus those are exactly the changes needed, yes. Now if you just make them conditional based on some --disable-bridge configure switch, this should be ready to merge :) Feel to ask here if you need any help.

**Comment by frozeus** [comment]
Thanks for you support, i'm a newbie with autools/autoconf but i will try. 

Also as i have a hardware h264/opus encoder i'm editing owr_local_media_source to support appsrc and push data in this source. Not sure there is a generic way to do this. As soon as it's working i will try to push a patch if you think it can be usefull.

**Comment by stefanalund** [comment]
Cool, please do!

**Comment by superdump** [comment]
I think @ford-prefect has been doing some work to handle compressed media sources but I'm not sure how much he's managed to do. Maybe that work is useful to you and we can discuss how to continue with it if you're interested. :smile:

**Comment by ford-prefect** [comment]
I've left notes on my works so far at
https://github.com/EricssonResearch/openwebrtc/issues/172#issuecomment-74239108

**Comment by superdump** [comment]
This is done. Closing.

**Comment by ikonst** [comment]
Did we split the openwebrtc recipe into openwebrtc and openwebrtc-bridge?

If we do this, we can eliminate the dependency of openwebrtc on Android/iOS on the host openwebrtc build, and so eliminate the annoying "You need to build openwebrtc for the host..." message (as long as you're just building the openwebrtc recipe -- not the whole package, since that'll probably still require the bridge).

**Comment by superdump** [comment]
No, but we can make variants in the openwebrtc.recipe so that if you do not want the bridge and its dependencies, you can disable them.
