### ISSUE TITLE
Cerbero Android build produces broken .jar files

### ISSUE THREAD

**Issue by Rugvip** [EricssonResearch/openwebrtc#161]
The .jar files produces by the cerbero Android build contain invalid dependencies and can't be used. The best way around this at the moment is to use the build scripts instead.

**Comment by nirbheek** [comment]
I've made a preliminary fix for this: https://github.com/nirbheek/cerbero/commit/6b9c8b6ff5e96b14cba7f9231b26f39a06316f41

Everything *looks* ok, but I haven't tested it with a native/webview app yet.

**Comment by stefanalund** [comment]
Have this been verified? Would be great to land.

**Comment by Rugvip** [comment]
Right, I tried this and it does idd look ok, but it crashes with the following:
```
java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libgnustl_shared.so" needed by "libopenwebrtc_jni.so"; caused by library "libgnustl_shared.so" not found
```

**Comment by nirbheek** [comment]
Hum, I thought gnustl_shared would be provided by the Android ABI. I'll look into this again tomorrow.

**Comment by sdroege** [comment]
@nirbheek that should be fixed in cerbero master, if not please talk to Edward. He was fighting with the same problem last week or the week before and found the reason.

**Comment by superdump** [comment]
@Rugvip @nirbheek is this fixed now?

**Comment by nirbheek** [comment]
Not yet; I became blocked by breakage in the bindings due to the DataChannel changes: https://github.com/EricssonResearch/openwebrtc/pull/226. I think I've figured out the gnustl problem though, and will have a fix soon.

**Comment by nirbheek** [comment]
The GNU C++ STL problem should be fixed now. You need to rebuild icu, javascriptcoregtk, seed, and then openwebrtc. To verify, run `readelf -d ~/cerbero/dist/android_armv7/lib/libopenwebrtc_jni.so | grep gnustl_shared`. That should give no output.

**Comment by Rugvip** [comment]
This is now working for me on OS X, but I guess it would be good if someone could build and verify on a Linux host as well before we close the issue.

**Comment by superdump** [comment]
@Rugvip says this is fixed. Closing.
