### ISSUE TITLE
Audio does not work on iOS

### ISSUE THREAD

**Issue by voznesenskym** [EricssonResearch/openwebrtc#162]
I can't get Audio to work on iOS. I also can't get the app to build, but that is a whole other issue which I will post on next. Is this a known issue?

Got app on store, ios 8.1, iPhone 6

**Comment by stefanalund** [comment]
Which app do you mean, Bowser?

**Comment by voznesenskym** [comment]
Yes. Would you like logs? or screenshot? (Video works fine)

**Comment by stefanalund** [comment]
Are you using our demo app demo.openwebrtc.io (I guess you have checked the audio box)? Which browser are you using on the other side?

**Comment by voznesenskym** [comment]
I did check the audio box, and I am using the demo app of the app store.

Chrome on the other end. I tried Safari as well.

**Comment by stefanalund** [comment]
Could you please try again with the latest master? Update OpenWebRTC: https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC#update-openwebrtc

**Comment by superdump** [comment]
@voznesenskym have you had time to try again?

**Comment by superdump** [comment]
I have tested with Bowser built locally and audio works. Either this is already fixed in the App Store version, or it will be with the next update. Closing and we can reopen if the issue reoccurs. Thanks for the report!

**Comment by voznesenskym** [comment]
Hey - will look at this soon, sorry, been crazy busy.

**Comment by igala** [comment]
I am having the same issue, audio is not played either built locally or using the app store version. Do you have any idea where the issue can be?

**Comment by urbaniak** [comment]
I've found the same issue, using a `OpenWebRTCWebView` and OpenWebRTC.framework build from current master, embedded in hybrid app.

WebRTC detection works, establishing a call using sip.js works, but there's just no sound.
