### ISSUE TITLE
No interop FF Nightly or DevEd if OWR inititates

### ISSUE THREAD

**Issue by stefhak** [EricssonResearch/openwebrtc#164]
Works ok if FF is "offerer", but not other way around. Works in both roles towards FF Production.
Difference spotted: FF Production answers with H264, the other two with VP8.

Many SDPs below for the interested:
============== safari -> FF nightly, unsuccessful
"v=0
o=- 1423383362140759600 1 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic:WMS D+PSKFQASblquTMW+yDdTAb3DjjC3onU86dF
m=video 64085 RTP/SAVPF 103 100 120
c=IN IP4 192.168.1.165
a=rtcp:55744 IN IP4 192.168.1.165
a=rtcp-mux
a=sendrecv
a=rtpmap:103 H264/90000
a=rtpmap:100 VP8/90000
a=rtpmap:120 RTX/90000
a=fmtp:103 packetization-mode=1
a=fmtp:120 apt=100;rtx-time=200
a=rtcp-fb:100 nack
a=rtcp-fb:103 nack pli
a=rtcp-fb:100 nack pli
a=rtcp-fb:103 ccm fir
a=rtcp-fb:100 ccm fir
a=ssrc:1051119119 cname:user897184264@host-9f0a266e
a=ssrc:1051119119 msid:D+PSKFQASblquTMW+yDdTAb3DjjC3onU86dF cYSBRmsV3HXPoggm/AnGV/VoKmBiN5Gf/Kpc
a=ice-ufrag:rkfb
a=ice-pwd:Mt7uTo/mgm7YrIesAnbhOe
a=candidate:1 1 UDP 2013266431 fe80::7c77:d0ff:fefe:9f02 64497 typ host
a=candidate:2 1 TCP 1019216383 fe80::7c77:d0ff:fefe:9f02 9 typ host tcptype active
a=candidate:3 1 TCP 1015022079 fe80::7c77:d0ff:fefe:9f02 49978 typ host tcptype passive
a=candidate:4 1 UDP 2013266431 192.168.1.165 64085 typ host
a=candidate:5 1 TCP 1019216383 192.168.1.165 9 typ host tcptype active
a=candidate:6 1 TCP 1015022079 192.168.1.165 49980 typ host tcptype passive
a=candidate:7 1 UDP 2013266431 fe80::22c9:d0ff:fed4:e175 55745 typ host
a=candidate:8 1 TCP 1019216383 fe80::22c9:d0ff:fed4:e175 9 typ host tcptype active
a=candidate:9 1 TCP 1015022079 fe80::22c9:d0ff:fed4:e175 49982 typ host tcptype passive
a=candidate:1 2 UDP 2013266430 fe80::7c77:d0ff:fefe:9f02 64498 typ host
a=candidate:2 2 TCP 1019216382 fe80::7c77:d0ff:fefe:9f02 9 typ host tcptype active
a=candidate:3 2 TCP 1015022078 fe80::7c77:d0ff:fefe:9f02 49979 typ host tcptype passive
a=candidate:4 2 UDP 2013266430 192.168.1.165 55744 typ host
a=candidate:5 2 TCP 1019216382 192.168.1.165 9 typ host tcptype active
a=candidate:6 2 TCP 1015022078 192.168.1.165 49981 typ host tcptype passive
a=candidate:7 2 UDP 2013266430 fe80::22c9:d0ff:fed4:e175 55746 typ host
a=candidate:8 2 TCP 1019216382 fe80::22c9:d0ff:fed4:e175 9 typ host tcptype active
a=candidate:9 2 TCP 1015022078 fe80::22c9:d0ff:fed4:e175 49983 typ host tcptype passive
a=fingerprint:sha-256 4B:F1:BB:A8:68:0E:E2:ED:2C:6E:34:0D:EF:06:91:85:E0:FF:DA:7E:D6:83:8A:78:FF:DE:27:E6:9B:FF:34:6D
a=setup:actpass"

"v=0
o=mozilla...THIS_IS_SDPARTA-38.0a1 3367288220050670269 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 8C:24:F3:B6:EC:CB:71:9F:9E:C6:8A:18:F7:60:EF:71:BE:31:98:CA:1C:93:EC:52:EC:A4:2F:75:C0:45:AF:5F
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 RTP/SAVPF 100
c=IN IP4 0.0.0.0
a=sendrecv
a=fmtp:100 max-fs=12288;max-fr=60
a=ice-pwd:e55fd754fe86d6ef302876612a88dd73
a=ice-ufrag:23096987
a=msid:{76551c82-9f00-5541-8d81-1c38b946d147} {b46fe2f4-50f6-8742-bfbe-6df92c8387b2}
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 ccm fir
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=setup:active
a=ssrc:1530395677 cname:{84f34292-d23b-6041-848d-8cdd45714a97}"

============== FF nightly -> Safari, successful
"v=0
o=mozilla...THIS_IS_SDPARTA-38.0a1 5573867009852634903 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 E8:04:4B:B6:A4:F1:C3:2A:4F:07:D6:B4:6F:D8:CB:87:13:05:4F:B8:92:8F:EA:CA:55:C2:8A:77:9A:E0:86:0A
a=group:BUNDLE sdparta_0
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 RTP/SAVPF 120
c=IN IP4 0.0.0.0
a=sendrecv
a=fmtp:120 max-fs=12288;max-fr=60
a=ice-pwd:657130f7b15d5fac61375a7088f9eed2
a=ice-ufrag:e26ba7eb
a=mid:sdparta_0
a=msid:{b6623a21-9d73-3749-a18b-ad562e6d196a} {5f1dd9b3-49b1-7f4f-aad6-4e97eeb5898a}
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-mux
a=rtpmap:120 VP8/90000
a=setup:actpass
a=ssrc:1188302214 cname:{a9319a04-0a14-9749-98ff-f8cdc9fe1bcb}"

"v=0
o=- 1423383576853210400 1 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic:WMS 2k0HJR3t1PND5rCVYkWzrNyJRw8+XZsgM44s
m=video 1 RTP/SAVPF 120
c=IN IP4 0.0.0.0
a=rtcp-muxa=sendrecv
a=rtpmap:120 VP8/90000
a=fmtp:120 max-fs=12288;max-fr=60
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=ssrc:2106092057 cname:user2727436022@host-20e3b122
a=ssrc:2106092057 msid:2k0HJR3t1PND5rCVYkWzrNyJRw8+XZsgM44s ygWKw8ubEN76OSidQYiaFek+27P11w4W+ZH0
a=ice-ufrag:RGIv
a=ice-pwd:NTQn1PN+eM9ARPml4aRFWT
a=candidate:1 1 UDP 2013266431 fe80::7c77:d0ff:fefe:9f02 59219 typ host
a=fingerprint:sha-256 4B:F1:BB:A8:68:0E:E2:ED:2C:6E:34:0D:EF:06:91:85:E0:FF:DA:7E:D6:83:8A:78:FF:DE:27:E6:9B:FF:34:6D
a=setup:active"

============== safari -> Crhome, successful
"v=0
o=- 1423383946337212000 1 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic:WMS 0v+pB8k85PQ1MMpZdJshavFFJLDQctwfwVlW
m=video 1 RTP/SAVPF 103 100 120
c=IN IP4 0.0.0.0
a=rtcp-mux
a=sendrecv
a=rtpmap:103 H264/90000
a=rtpmap:100 VP8/90000
a=rtpmap:120 RTX/90000
a=fmtp:103 packetization-mode=1
a=fmtp:120 apt=100;rtx-time=200
a=rtcp-fb:100 nack
a=rtcp-fb:103 nack pli
a=rtcp-fb:100 nack pli
a=rtcp-fb:103 ccm fir
a=rtcp-fb:100 ccm fir
a=ssrc:2256261714 cname:user2721748303@host-83756efe
a=ssrc:2256261714 msid:0v+pB8k85PQ1MMpZdJshavFFJLDQctwfwVlW XQBKWjp0CzV1DS+s1yZb54AfDwH7uOlK8hbO
a=ice-ufrag:B9m3
a=ice-pwd:lXHHKTpW0a1gc3r//weFal
a=candidate:1 1 UDP 2013266431 fe80::7c77:d0ff:fefe:9f02 61545 typ host
a=fingerprint:sha-256 4B:F1:BB:A8:68:0E:E2:ED:2C:6E:34:0D:EF:06:91:85:E0:FF:DA:7E:D6:83:8A:78:FF:DE:27:E6:9B:FF:34:6D
a=setup:actpass
"

"v=0
o=- 8501989613333789395 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS 1Q0ycsam97XiZe7qi11Vt6AGy78uHeRIc4QI
m=video 57775 RTP/SAVPF 100 120
c=IN IP4 192.168.1.165
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:188435914 1 udp 2122260223 192.168.1.165 57775 typ host generation 0
a=ice-ufrag:nER42iY0b3TMOAf1
a=ice-pwd:UXZj279jIZNrezhw1gX7w29C
a=fingerprint:sha-256 C2:2C:ED:58:BA:D8:EC:AF:16:27:75:98:8F:42:22:23:18:F3:50:5F:98:63:6F:7E:77:A7:4D:59:AF:04:E3:C9
a=setup:active
a=mid:video
a=sendrecv
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=100
a=ssrc-group:FID 2950595205 3690969930
a=ssrc:2950595205 cname:k77jTsyIDz2nkvFx
a=ssrc:2950595205 msid:1Q0ycsam97XiZe7qi11Vt6AGy78uHeRIc4QI 790ce3aa-a509-41a8-93eb-98df62de7fea
a=ssrc:2950595205 mslabel:1Q0ycsam97XiZe7qi11Vt6AGy78uHeRIc4QI
a=ssrc:2950595205 label:790ce3aa-a509-41a8-93eb-98df62de7fea
a=ssrc:3690969930 cname:k77jTsyIDz2nkvFx
a=ssrc:3690969930 msid:1Q0ycsam97XiZe7qi11Vt6AGy78uHeRIc4QI 790ce3aa-a509-41a8-93eb-98df62de7fea
a=ssrc:3690969930 mslabel:1Q0ycsam97XiZe7qi11Vt6AGy78uHeRIc4QI
a=ssrc:3690969930 label:790ce3aa-a509-41a8-93eb-98df62de7fea
"

==================== Chrome -> Safari successful
"v=0
o=- 5806412914254700928 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE video
a=msid-semantic: WMS QAqSa3bTuld22MrEp4FxStBeZH0t1AR4lmhS
m=video 52639 RTP/SAVPF 100 116 117 96
c=IN IP4 192.168.1.165
a=rtcp:52639 IN IP4 192.168.1.165
a=candidate:188435914 1 udp 2122260223 192.168.1.165 52639 typ host generation 0
a=candidate:188435914 2 udp 2122260223 192.168.1.165 52639 typ host generation 0
a=ice-ufrag:M7Ti2OOTc4L1QKUD
a=ice-pwd:5TPjuZdWfC15Azt7aeGReU7t
a=ice-options:google-ice
a=fingerprint:sha-256 C2:2C:ED:58:BA:D8:EC:AF:16:27:75:98:8F:42:22:23:18:F3:50:5F:98:63:6F:7E:77:A7:4D:59:AF:04:E3:C9
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=ssrc-group:FID 1838108359 2705888063
a=ssrc:1838108359 cname:/2MtxqtE+WFZ3Ns2
a=ssrc:1838108359 msid:QAqSa3bTuld22MrEp4FxStBeZH0t1AR4lmhS 73293672-20bb-4bed-946f-34b0bde5f95f
a=ssrc:1838108359 mslabel:QAqSa3bTuld22MrEp4FxStBeZH0t1AR4lmhS
a=ssrc:1838108359 label:73293672-20bb-4bed-946f-34b0bde5f95f
a=ssrc:2705888063 cname:/2MtxqtE+WFZ3Ns2
a=ssrc:2705888063 msid:QAqSa3bTuld22MrEp4FxStBeZH0t1AR4lmhS 73293672-20bb-4bed-946f-34b0bde5f95f
a=ssrc:2705888063 mslabel:QAqSa3bTuld22MrEp4FxStBeZH0t1AR4lmhS
a=ssrc:2705888063 label:73293672-20bb-4bed-946f-34b0bde5f95f
"

"v=0
o=- 1423384160925239000 1 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic:WMS Ln7qS16QJ97yLbjsNUjjAnqHcGEZ2xEeAPi9
m=video 1 RTP/SAVPF 100 96
c=IN IP4 0.0.0.0
a=rtcp-mux
a=sendrecv
a=rtpmap:100 VP8/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 ccm fir
a=ssrc:3596697307 cname:user1238550358@host-89ac9053
a=ssrc:3596697307 msid:Ln7qS16QJ97yLbjsNUjjAnqHcGEZ2xEeAPi9 1VF328dYsax7Kh0R1vcbqsxKinx/YynIeFy3
a=ice-ufrag:DEUL
a=ice-pwd:GdVfa1CrnvNYG29/i8ROL9
a=candidate:1 1 UDP 2013266431 fe80::7c77:d0ff:fefe:9f02 52640 typ host
a=fingerprint:sha-256 4B:F1:BB:A8:68:0E:E2:ED:2C:6E:34:0D:EF:06:91:85:E0:FF:DA:7E:D6:83:8A:78:FF:DE:27:E6:9B:FF:34:6D
a=setup:active
"

============== safari -> FF nightly, unsuccessful, modified to include 1st candidate in answer
"v=0
o=- 1423385069995686100 1 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic:WMS JqDraZjM+W9yIuQoKgNEajLpRlUTrZqo3KWL
m=video 1 RTP/SAVPF 103 100 120
c=IN IP4 0.0.0.0
a=rtcp-mux
a=sendrecv
a=rtpmap:103 H264/90000
a=rtpmap:100 VP8/90000
a=rtpmap:120 RTX/90000
a=fmtp:103 packetization-mode=1
a=fmtp:120 apt=100;rtx-time=200
a=rtcp-fb:100 nack
a=rtcp-fb:103 nack pli
a=rtcp-fb:100 nack pli
a=rtcp-fb:103 ccm fir
a=rtcp-fb:100 ccm fir
a=ssrc:56591397 cname:user1194462372@host-ce146ba9
a=ssrc:56591397 msid:JqDraZjM+W9yIuQoKgNEajLpRlUTrZqo3KWL 4Ro+HW8gCBcMzI4QkTh3QOP9HLKhQ3aROI8C
a=ice-ufrag:QqMC
a=ice-pwd:oxepQXEBDeFiNlw8/VTeKQ
a=candidate:1 1 UDP 2013266431 fe80::7c77:d0ff:fefe:9f02 57832 typ host
a=fingerprint:sha-256 4B:F1:BB:A8:68:0E:E2:ED:2C:6E:34:0D:EF:06:91:85:E0:FF:DA:7E:D6:83:8A:78:FF:DE:27:E6:9B:FF:34:6D
a=setup:actpass"

"v=0
o=mozilla...THIS_IS_SDPARTA-38.0a1 4103759695377403431 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 F8:FF:56:4B:74:D5:01:2D:3C:AD:5E:01:6B:6A:F2:BE:19:8A:43:97:1C:00:58:96:DD:14:7B:6A:BC:21:A2:35
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 9 RTP/SAVPF 100
c=IN IP4 0.0.0.0
a=candidate:0 1 UDP 2130444543 192.168.1.165 53929 typ host
a=sendrecv
a=fmtp:100 max-fs=12288;max-fr=60
a=ice-pwd:9d132cd077b359d957f24d51edb33c1b
a=ice-ufrag:35aad126
a=msid:{8b486d33-7578-a944-91f6-f0365bbba575} {72970661-964f-8f46-93cb-1554c15457e7}
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 ccm fir
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=setup:active
a=ssrc:1731339640 cname:{df08c547-a839-d542-9282-97442d9d3e20}"

============================ safar -> FF production, successful (only answer from FF shown)
"v=0
o=Mozilla-SIPUA-35.0.1 26213 0 IN IP4 0.0.0.0
s=SIP Call
t=0 0
a=ice-ufrag:94278a27
a=ice-pwd:80277d35c22dc099e2c23967727b6b9f
a=fingerprint:sha-256 E8:68:AA:EF:A1:9E:F0:F4:35:F4:DA:0F:0F:CB:4F:EA:7E:37:3C:17:6D:78:15:26:01:4D:40:72:57:7D:64:05
m=video 9 RTP/SAVPF 103
c=IN IP4 0.0.0.0
a=rtpmap:103 H264/90000
a=fmtp:103 profile-level-id=42e01f;packetization-mode=1
a=sendrecv
a=rtcp-fb:103 nack pli
a=rtcp-fb:103 ccm fir
a=setup:active
a=rtcp-mux
a=candidate:0 1 UDP 2130444543 192.168.1.165 64097 typ host
a=candidate:0 2 UDP 2130444542 192.168.1.165 57387 typ host
a=candidate:1 1 UDP 1694302207 79.136.27.45 64097 typ srflx raddr 192.168.1.165 rport 64097
a=candidate:1 2 UDP 1694302206 79.136.27.45 57387 typ srflx raddr 192.168.1.165 rport 57387"

============================ safar -> FF DevEd, unsuccessful (only answer from FF shown)
"v=0
o=mozilla...THIS_IS_SDPARTA-37.0a2 427280868993715567 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 3D:B7:B8:7E:7B:50:58:D9:D0:01:4F:D8:77:AF:FD:5F:6F:FF:AB:99:53:97:8C:0F:8D:92:11:46:64:BC:97:2B
a=ice-options:trickle
m=video 9 RTP/SAVPF 100
c=IN IP4 0.0.0.0
a=candidate:0 1 UDP 2130444543 192.168.1.165 59293 typ host
a=sendrecv
a=fmtp:100 max-fs=12288;max-fr=60
a=ice-pwd:f2c79f12af19feabaf65116a60841a3b
a=ice-ufrag:414a5992
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 ccm fir
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=setup:active
a=ssrc:4184068635 cname:{c445a4c5-a2a2-f348-b52e-41f366f2a9af}"

**Comment by stefhak** [comment]
H264 in offer seems not to be the problem, even if removed before setLocal it does not work.

**Comment by superdump** [comment]
We recently added RTX support to the JS layer. Could that be related?

**Comment by superdump** [comment]
Does modifying to add the first candidate actually create a valid SDP though, if claiming trickle mode?

**Comment by stefhak** [comment]
I don't know. I just noted that Chrome and OWR includes a candidate in first offer/answer even if mode is trickling, so I added it to the FF answer just to do the same thing. Nothing changed regarding functionality.
I guess someone needs to do some wiresharking.

**Comment by stefhak** [comment]
If I remove RTX from the JS layer, from which stage do I need to re-build stuff?

**Comment by superdump** [comment]
Just rebuild openwebrtc itself.

**Comment by stefanalund** [comment]
Was this fixed?

**Comment by superdump** [comment]
@stefhak was this only due to the SSL crypto method? If so, I think it's fixed.

**Comment by stefhak** [comment]
Yes, it works now AFAIK.

**Comment by stefanalund** [comment]
Then we can close this issue, thanks.
