### ISSUE TITLE
Build error ./build.sh -Cbr linux android

### ISSUE THREAD

**Issue by francus87** [EricssonResearch/openwebrtc#171]
Hi everyone,

I have a error when running $ sudo ./build.sh -Cbr linux android

This is  the result console:

  CCLD     libopenwebrtc.la
/usr/bin/ld: cannot find -lgstopus
/usr/bin/ld: cannot find -lgstopengl
/usr/bin/ld: cannot find -lgstinter
/usr/bin/ld: cannot find -lgstgl-1.0
/usr/bin/ld: cannot find -lgstsrtp
/usr/bin/ld: cannot find -lgstvideoparsersbad
/usr/bin/ld: cannot find -lgstbadvideo-1.0
/usr/bin/ld: cannot find -lgstbadbase-1.0
/usr/bin/ld: cannot find -lgstcodecparsers-1.0
collect2: error: ld returned 1 exit status
make[2]: *** [libopenwebrtc.la] Error 1
make[2]: se sale del directorio «/home/francus/openwebrtc/build/x86_64-unknown-linux/owr»
make[1]: *** [all-recursive] Error 1
make[1]: se sale del directorio «/home/francus/openwebrtc/build/x86_64-unknown-linux»
make: *** [all] Error 2
Failed building....

Previously, I follow steps like https://github.com/EricssonResearch/openwebrtc/issues/97 because i had the same error but it had fixed.
I changed some lines of  build.sh script how it explan in the issue

I think the trouble will be in these lines of the build.sh script:

132 export GSTREAMER_LIBS="-L${src_dir}/openwebrtc-deps-${target}/lib -L${src_dir}/openwebrtc-deps-${target}/lib/gstreamer-1.0 -lgstaudiotestsrc -lgstvideotestsrc -lgstcoreelements -lgstalaw -lgstmulaw -lgstopus -lopus -lgstapp -lgstaudioconvert -lgstaudioresample -lgstvolume -lgstvideoconvert -lgstvpx -lvpx -lgstopengl -lgstinter -lgstgl-1.0"
133	export GSTREAMER_LIBS="$GSTREAMER_LIBS $PLATFORM_GSTREAMER_LIBS -lgstrtpmanager -lgstrtp -lgstsrtp -lsrtp -lgstvideocrop -lgstvideofilter -lgstvideoparsersbad -lgstvideorate -lgstvideoscale -lgstnice -lgstcontroller-1.0 -lgstpbutils-1.0 -lgstnet-1.0 -lgstrtp-1.0 -lgstbadvideo-1.0 -lgstbadbase-1.0"
134  export GSTREAMER_LIBS="$GSTREAMER_LIBS -lgsttag-1.0 -lgstapp-1.0 -lgstaudio-1.0 -lgstvideo-1.0 -lgstcodecparsers-1.0 -lgstbase-1.0 -lgstreamer-1.0"

Thanks.

**Comment by superdump** [comment]
It looks instead like a problem with your dependencies build. Did that step complete without error?

**Comment by francus87** [comment]
I think so, but I have run again: ./build-all-sh -Cbr linux android and it ocurred this error:

checking for xxd... /usr/bin/xxd
configure: error: Android API level 19 not found in the SDK
Failed building...openwebrtc-gst-plugins
mv openwebrtc-gst-plugins openwebrtc-gst-plugins_build_failed_on_150217-20:24:19_using_script_with_md5sum_3322236bfb56e044696fb79e707682275dc76676

I have installed Android API 19 like can see in the image.
![android_sdk_manager](https://cloud.githubusercontent.com/assets/10158247/6236007/2861df26-b6e7-11e4-8b96-1aab115d9eed.png)

And I have added  android sdk path(/home/francus/.android-sdk-linux) to the variable $PATH. I dont know if this applied.

Thanks.

**Comment by Rugvip** [comment]
Here's the check from configure.ac:
```
  dx_path=`AS_DIRNAME(["$DX"])`
  ANDROID_CLASSPATH="$dx_path/../../platforms/android-19/android.jar"
  if ! test -f "$ANDROID_CLASSPATH"; then
    AC_MSG_ERROR([Android API level 19 not found in the SDK])
  fi
```

It looks like dx is found, what's the path to your `dx` binary? or have you set the DX environment variable?

The directory that the configure script is searching for is `<android-sdk>/platforms/android-19` do you have that directory in your SDK dir?

**Comment by francus87** [comment]
The dx binary's path is ~/.openwebrtc/bin and i haven't set DX enviroment variable.

I have copied  to $dx_path/../../ SDK directories that script is serching and i think resolve it. The script don't stop in the same line.

is this solution ok? or have i do other thing??

But then other error happens:

/home/francus/.openwebrtc/bin/dx --dex --output=classes_dex.jar src
dx: can't find dx.jar
make[3]: *** [classes_dex.jar] Error 1
make[3]: se sale del directorio «/home/francus/openwebrtc/scripts/dependencies/build/arm-linux-androideabi/openwebrtc-gst-plugins/sys/androidvideo/video-source»
make[2]: *** [install-recursive] Error 1
make[2]: se sale del directorio «/home/francus/openwebrtc/scripts/dependencies/build/arm-linux-androideabi/openwebrtc-gst-plugins/sys/androidvideo»
make[1]: *** [install-recursive] Error 1
make[1]: se sale del directorio «/home/francus/openwebrtc/scripts/dependencies/build/arm-linux-androideabi/openwebrtc-gst-plugins/sys»
make: *** [install-recursive] Error 1
Failed building...openwebrtc-gst-plugins
mv openwebrtc-gst-plugins openwebrtc-gst-plugins_build_failed_on_150224-19:07:43_using_script_with_md5sum_3322236bfb56e044696fb79e707682275dc76676

**Comment by superdump** [comment]
As far as I recall, the path to `dx`is important to identify as other tools are also found in that directory. You need to set up your `PATH` environment variable to point out where `dx` is in your Android SDK.

**Comment by superdump** [comment]
We have now moved to the cerbero build system. Thanks for your issue report. Please try cerbero for building from now on.

https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC
