### ISSUE TITLE
Gio not instantiatable

### ISSUE THREAD

**Issue by ijsf** [EricssonResearch/openwebrtc#173]
Hey,

I've been checking out the OpenWebRTC project for a while, and recently attempted a iOS universal build using Cerbero, target deployment being an iPad Mini on iOS 8.1.3.

The build completed successfully, and the appropriate framework was linked with Bowser. When I booted Bowser up though the following error occurred:

    ** Message: Loaded namespace: GLib
    ** Message: Loaded namespace: GObject
    ** Message: Loaded namespace: Gio
    ** Message: Loaded namespace: GIRepository
    ** Message: Loaded namespace: Owr
    WARNING: no real random source present!
    ** Message: Exception: Line 347 in websocket.js: ArgumentError Type can not be created - not INSTANTIATABLE

Did a Cerbero fetch, so I assume that the latest master has been checked out.

**Comment by stefanalund** [comment]
I just noticed the same problem. It is even worse on 64-bit devices where the app crashes inside JavaScriptCore. Presumably there is a problem with JavaScript handling when using Cerbero. We are investigating. Ping @sdroege @nirbheek :)

**Comment by sdroege** [comment]
This would happen if the compiler optimized away our hack to retain the symbols not used directly. openwebrtc master still doesn't have that right, I have a fix here though: https://github.com/nirbheek/openwebrtc/commit/9e71939eb47e8ea2319a84af326f6fc07bdb062f

before cerbero built from that branch, it does not do that anymore. So this fix has to go in master. Doing that now.


@stefanalund for the 64 bit crash, can you open another ticket?

**Comment by sdroege** [comment]
This issue should be fixed now with https://github.com/EricssonResearch/openwebrtc/commit/2eb27b4344079f03127d296f96068260e4c6e1eb

**Comment by stefanalund** [comment]
@sdroege Ticket created: https://github.com/EricssonResearch/openwebrtc/issues/177 Do you think it could be related?
