### ISSUE TITLE
Scale problem in GL video view

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/openwebrtc#178]
`OpenWebRTCVideoView` does not scale down. Therefore, only a small part of the video is shown. Making the view bigger in Xcode/Storyboard reveals bigger part of video. Ideally, the GL view should respect the UIView's scale mode (such as "Scaled to Fill"):

![img_0113](https://cloud.githubusercontent.com/assets/190856/6214117/acd8b3c0-b5f6-11e4-9d4b-e1e095de5969.PNG)

**Comment by sdroege** [comment]
Is this a regression or was it always like that?

**Comment by stefanalund** [comment]
Pretty sure it's a regression. Before switching to use Cerbero the video was scaled down to fit the view (sometimes letter boxed though).

**Comment by stefanalund** [comment]
Any progress on this one? @sdroege @alessandrod

**Comment by sdroege** [comment]
@alessandrod is looking into it and AFAIU the scaling problem is gone, there's just something weird still with orientation changes that might also be a problem in the app

**Comment by stefanalund** [comment]
That's another issue: https://github.com/EricssonResearch/openwebrtc/issues/150 😏

**Comment by alessandrod** [comment]
I just pushed a commit to gst-plugins-bad master that fixes this issue. Rotation (#150) is still a problem.

**Comment by alessandrod** [comment]
commit 2a430872edeb7082fea2c00c92a0330a4ee5245b
Author: Alessandro Decina <alessandro.d@gmail.com>
Date:   Tue Feb 24 14:23:49 2015 +1100

    libgstgl: eagl: handle CALayer resize
