### ISSUE TITLE
CRITICAL: gst_gl_window_show problem?

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/openwebrtc#179]
This is logged when using owr native API on iOS using Cerbero:
```
** (<unknown>:2335): CRITICAL **: gst_gl_window_show: assertion 'window_class->show != NULL' failed
```
Is this something that needs to be fixed? The video is shown.

**Comment by sdroege** [comment]
This is fixed now here: http://cgit.freedesktop.org/gstreamer/gst-plugins-bad/commit/?id=475dfaedc1f06904bed9f2c230cedc23b8c024a7

As you already guessed, it's not really a problem.
