### ISSUE TITLE
libsoup_build failed

### ISSUE THREAD

**Issue by StephaneC** [EricssonResearch/openwebrtc#187]
Trying to compile OpenWebRTC on my Mac OSX 10.10.1, got this error running ./build-all.sh -Cbr osx ios-simulator

9 warnings generated.
  CCLD     libsoup-2.4.la
  CC       soup-cookie-jar-sqlite.lo
  CC       soup-gnome-features.lo
  CC       soup-proxy-resolver-gnome.lo
  CC       soup-password-manager-gnome.lo
  CCLD     libsoup-gnome-2.4.la
libtool: link: warning: `/opt/workspaces2/ios/fwk-openwebrtc/openwebrtc/scripts/dependencies/out/i386-apple-darwin10/libsoup/../gettext-0.18.2.1/lib/libintl.la' seems to be moved
libtool: link: warning: `/opt/workspaces2/ios/fwk-openwebrtc/openwebrtc/scripts/dependencies/out/i386-apple-darwin10/libsoup/../libxml2-2.7.8/lib/libxml2.la' seems to be moved
libtool: link: warning: `/opt/workspaces2/ios/fwk-openwebrtc/openwebrtc/scripts/dependencies/out/i386-apple-darwin10/libsoup/../sqlite-autoconf-3080500/lib/libsqlite3.la' seems to be moved
  GISCAN Soup-2.4.gir
Can't open directory
Command '['/opt/workspaces2/ios/fwk-openwebrtc/openwebrtc/scripts/dependencies/build/i386-apple-darwin10/libsoup/libsoup/tmp-introspect3VAbRC/Soup-2.4', '--introspect-dump=/opt/workspaces2/ios/fwk-openwebrtc/openwebrtc/scripts/dependencies/build/i386-apple-darwin10/libsoup/libsoup/tmp-introspect3VAbRC/functions.txt,/opt/workspaces2/ios/fwk-openwebrtc/openwebrtc/scripts/dependencies/build/i386-apple-darwin10/libsoup/libsoup/tmp-introspect3VAbRC/dump.xml']' returned non-zero exit status 1
make[3]: *** [Soup-2.4.gir] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Failed building...libsoup
mv libsoup libsoup_build_failed_on_150219-19:26:35_using_script_with_md5sum_5838cdedea082deecc9acb79c05ccc91c4f53bf4

**Comment by superdump** [comment]
Have you had any luck with this issue? It looks like a GObject Introspection issue and we don't use any soup API through introspection so if you like you can edit the `build-libsoup.sh` script to add `--disable-introspection` to the `autogen.sh` parameters, say after `--disable-shared`

**Comment by superdump** [comment]
Closing as we have now moved to a new build system called cerbero. Please try to build using that.

https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC
