### ISSUE TITLE
Libsoup GI failure in Raspberry PI -   GISCAN Soup-2.4.gir

### ISSUE THREAD

**Issue by santokum** [EricssonResearch/openwebrtc#189]
Tried building  in RPi - found below issue with Libsoup...

  CC       soup-session-sync.lo
  CC       soup-socket.lo
  CC       soup-status.lo
  CC       soup-tld.lo
  CC       soup-uri.lo
  CC       soup-value-utils.lo
  CC       soup-version.lo
  CC       soup-xmlrpc.lo
  CCLD     libsoup-2.4.la
  CC       soup-cookie-jar-sqlite.lo
  CC       soup-gnome-features.lo
  CC       soup-proxy-resolver-gnome.lo
  CC       soup-password-manager-gnome.lo
  CCLD     libsoup-gnome-2.4.la
libtool: link: warning: `/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/libsoup/../libxml2-2.7.8/lib/libxml2.la' seems to be moved
libtool: link: warning: `/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/libsoup/../sqlite-autoconf-3080500/lib/libsqlite3.la' seems to be moved
  GISCAN Soup-2.4.gir
Invalid GType function: 'soup_address_get_type'
Failed to find symbol 'soup_address_get_type'
Command '['/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup/tmp-introspecthlsV80/Soup-2.4', '--introspect-dump=/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup/tmp-introspecthlsV80/functions.txt,/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup/tmp-introspecthlsV80/dump.xml']' returned non-zero exit status 1
make[3]: *** [Soup-2.4.gir] Error 1
make[3]: Leaving directory `/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup'
make: *** [all] Error 2
Failed building...libsoup
mv libsoup libsoup_build_failed_on_150220-11:04:24_using_script_with_md5sum_5838cdedea082deecc9acb79c05ccc91c4f53bf4

**Comment by superdump** [comment]
We don't currently have a build target for the Raspberry Pi. You can't build using the linux target as that is specifically for x86-64 Linux and not ARM Linux. We will be moving to a new build system soon that does have support for building on the Raspberry Pi. I'll check that build myself soon.

**Comment by superdump** [comment]
Closing as we don't support building on the Raspberry Pi using our build scripts.
