### ISSUE TITLE
 build-libffi.sh invalid git option

### ISSUE THREAD

**Issue by santokum** [EricssonResearch/openwebrtc#190]
Issue with build-libffi.sh - invalid option for GIT - i guess this should be a patch -p3 < ffi_android.patch instead of git.

I removed following line in order get through:- 
git am -p3 --include *closures* ffi_android.patch 

/bin/mkdir -p '/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/sqlite-autoconf-3080500/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c sqlite3 '/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/sqlite-autoconf-3080500/bin'
libtool: install: /usr/bin/install -c sqlite3 /home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/sqlite-autoconf-3080500/bin/sqlite3
 /bin/mkdir -p '/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/sqlite-autoconf-3080500/include'
 /usr/bin/install -c -m 644 sqlite3.h sqlite3ext.h '/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/sqlite-autoconf-3080500/include'
 /bin/mkdir -p '/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/sqlite-autoconf-3080500/share/man/man1'
 /usr/bin/install -c -m 644 sqlite3.1 '/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/sqlite-autoconf-3080500/share/man/man1'
 /bin/mkdir -p '/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/sqlite-autoconf-3080500/lib/pkgconfig'
 /usr/bin/install -c -m 644 sqlite3.pc '/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/sqlite-autoconf-3080500/lib/pkgconfig'
make[1]: Leaving directory `/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/sqlite-autoconf-3080500'
Marking build successful in sqlite-autoconf-3080500
clean_source, /home/pi/openwebrtc/scripts/dependencies
Cleaning source in libffi
Cloning into 'libffi'...
remote: Counting objects: 10074, done.
remote: Total 10074 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (10074/10074), 7.80 MiB | 1.57 MiB/s, done.
Resolving deltas: 100% (5764/5764), done.
HEAD is now at f22ab3c Merge branch 'master' of github.com:/atgreen/libffi
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2092    0  2092    0     0   3894      0 --:--:-- --:--:-- --:--:--  5178
error: unknown option `include'
usage: git am [options] [(<mbox>|<Maildir>)...]
   or: git am [options] (--resolved | --skip | --abort)

    -i, --interactive     run interactively
    -3, --3way            allow fall back on 3way merging if needed
    -q, --quiet           be quiet
    -s, --signoff         add a Signed-off-by line to the commit message
    -u, --utf8            recode into utf8 (default)
    -k, --keep            pass -k flag to git-mailinfo
    --keep-non-patch      pass -b flag to git-mailinfo
    --keep-cr             pass --keep-cr flag to git-mailsplit for mbox format
    --no-keep-cr          do not pass --keep-cr flag to git-mailsplit independent of am.keepcr
    -c, --scissors        strip everything before a scissors line
    --whitespace ...      pass it through git-apply
    --ignore-space-change
                          pass it through git-apply
    --ignore-whitespace   pass it through git-apply
    --directory ...       pass it through git-apply
    --exclude ...         pass it through git-apply
    -C ...                pass it through git-apply
    -p ...                pass it through git-apply
    --patch-format ...    format the patch(es) are in
    --reject              pass it through git-apply
    --resolvemsg ...      override error message when patch failure occurs
    --continue            continue applying patches after resolving a conflict
    -r, --resolved        synonyms for --continue
    --skip                skip the current patch
    --abort               restore the original branch and abort the patching operation.
    --committer-date-is-author-date
                          lie about committer date
    --ignore-date         use current timestamp for author date
    --rerere-autoupdate   update the index with reused conflict resolution if possible

./build-libffi.sh - Could not apply patch.
ERROR: Failed to install sources and configure source git

**Comment by superdump** [comment]
What version of git do you have?

**Comment by santokum** [comment]
git --version
git version 1.7.10.4
--------------------------------------------
On Fri, 20/2/15, Robert Swain <notifications@github.com> wrote:

 Subject: Re: [openwebrtc]  build-libffi.sh invalid git option (#190)
 To: "EricssonResearch/openwebrtc" <openwebrtc@noreply.github.com>
 Cc: "santokum" <santoshjram@yahoo.co.uk>
 Date: Friday, 20 February, 2015, 16:13
 
 What version of git do you
 have?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by superdump** [comment]
Are you able to update to something newer? That version is from 2012. It looks like the include option for git am was possibly added around the time of gut 1.8.3.

We support Ubuntu 14.04 LTS with the build scripts though you're welcome to try on other distributions with similarly new packages.

**Comment by santokum** [comment]
I will give it a go this evening with RPi. Thanks
--------------------------------------------
On Fri, 20/2/15, Robert Swain <notifications@github.com> wrote:

 Subject: Re: [openwebrtc]  build-libffi.sh invalid git option (#190)
 To: "EricssonResearch/openwebrtc" <openwebrtc@noreply.github.com>
 Cc: "santokum" <santoshjram@yahoo.co.uk>
 Date: Friday, 20 February, 2015, 16:52
 
 Are you able to update to
 something newer? That version is from 2012. It looks like
 the include option for git am was possibly added around the
 time of gut 1.8.3.
 
 We support Ubuntu 14.04 LTS with the build scripts though
 you're welcome to try on other distributions with
 similarly new packages.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by gtk2k** [comment]
I get git 2.3.0 (download form repository and make instal).

dependencies build problem.
>./build-all.sh -Cbr linux

CC soup-password-manager-gnome.lo
CCLD libsoup-gnome-2.4.la
libtool: link: warning: `/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/libsoup/../libxml2-2.7.8/lib/libxml2.la' seems to be moved
libtool: link: warning: `/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/libsoup/../sqlite-autoconf-3080500/lib/libsqlite3.la' seems to be moved
GISCAN Soup-2.4.gir
Invalid GType function: 'soup_address_get_type'
Failed to find symbol 'soup_address_get_type'
Command '['/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup/tmp-introspecttM9U_m/Soup-2.4', '--introspect-dump=/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup/tmp-introspecttM9U_m/functions.txt,/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup/tmp-introspecttM9U_m/dump.xml']' returned non-zero exit status 1
/home/pi/.openwebrtc/share/gobject-introspection-1.0/Makefile.introspection:153: recipe for target 'Soup-2.4.gir' failed
make[3]: *** [Soup-2.4.gir] Error 1
make[3]: Leaving directory '/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup'
Makefile:642: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup'
Makefile:471: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup'
Makefile:375: recipe for target 'all' failed
make: *** [all] Error 2
Failed building...libsoup
mv libsoup libsoup_build_failed_on_150221-17:25:27_using_script_with_md5sum_5838cdedea082deecc9acb79c05ccc91c4f53bf4
pi@raspberrypi ~/openwebrtc/scripts/dependencies $

**Comment by gtk2k** [comment]
I get git 2.3.0 (download form repository and make instal).

dependencies build problem.

./build-all.sh -Cbr linux
CC soup-password-manager-gnome.lo
CCLD libsoup-gnome-2.4.la
libtool: link: warning: /home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/libsoup/../libxml2-2.7.8/lib/libxml2.la' seems to be moved libtool: link: warning:/home/pi/openwebrtc/scripts/dependencies/out/x86_64-unknown-linux/libsoup/../sqlite-autoconf-3080500/lib/libsqlite3.la' seems to be moved
GISCAN Soup-2.4.gir
Invalid GType function: 'soup_address_get_type'
Failed to find symbol 'soup_address_get_type'
Command '['/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup/tmp-introspecttM9U_m/Soup-2.4', '--introspect-dump=/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup/tmp-introspecttM9U_m/functions.txt,/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup/tmp-introspecttM9U_m/dump.xml']' returned non-zero exit status 1
/home/pi/.openwebrtc/share/gobject-introspection-1.0/Makefile.introspection:153: recipe for target 'Soup-2.4.gir' failed
make[3]: *** [Soup-2.4.gir] Error 1
make[3]: Leaving directory '/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup'
Makefile:642: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup/libsoup'
Makefile:471: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/pi/openwebrtc/scripts/dependencies/build/x86_64-unknown-linux/libsoup'
Makefile:375: recipe for target 'all' failed
make: *** [all] Error 2
Failed building...libsoup
mv libsoup libsoup_build_failed_on_150221-17:25:27_using_script_with_md5sum_5838cdedea082deecc9acb79c05ccc91c4f53bf4
pi@raspberrypi ~/openwebrtc/scripts/dependencies $

**Comment by superdump** [comment]
@santokum Have you managed to update git on an x86 (Intel / AMD) Linux machine and try again?

**Comment by santokum** [comment]
Hi, not yet- i will give it a go this thu again. thanks
--------------------------------------------
On Tue, 24/2/15, Robert Swain <notifications@github.com> wrote:

 Subject: Re: [openwebrtc]  build-libffi.sh invalid git option (#190)
 To: "EricssonResearch/openwebrtc" <openwebrtc@noreply.github.com>
 Cc: "santokum" <santoshjram@yahoo.co.uk>
 Date: Tuesday, 24 February, 2015, 7:35
 
 @santokum Have you
 managed to update git on an x86 (Intel / AMD) Linux machine
 and try again?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by superdump** [comment]
Closing as we have now moved to a new build system called cerbero. Please try to build the project using that.

https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC
