### ISSUE TITLE
Unable to build dependencies on Mac OS X 10.10.2

### ISSUE THREAD

**Issue by mlakkadshaw** [EricssonResearch/openwebrtc#195]
Hi,
 When I try to build the dependences, I see this message, when the script is building gobject-introspection:
`env: Studio.app/sdk/platform-tools/:/Applications/Android: No such file or directory`
`everything-stamp.h error 127`
But the script marks gobject-introspection as successful and later when it build seed, I get an error ` girepository.h` file not found.
Any ideas why?

Thanks

**Comment by mlakkadshaw** [comment]
Now type `make' to compile seed
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in po
make[2]: Nothing to be done for `all'.
Making all in libseed
  CC       libseed-gtk3_la-seed-closure.lo
/Users/User/openwebrtc/scripts/dependencies/seed/libseed/seed-closure.c:79:35: error: invalid token at start of a preprocessor expression
#if GOBJECT_INTROSPECTION_VERSION < 0x000900
                                  ^
/Users/User/openwebrtc/scripts/dependencies/seed/libseed/seed-closure.c:198:35: error: invalid token at start of a preprocessor expression
#if GOBJECT_INTROSPECTION_VERSION < 0x000900
                                  ^
2 errors generated.
make[2]: *** [libseed-gtk3_la-seed-closure.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Failed building...seed
mv seed seed_build_failed_on_150221-19:58:03_using_script_with_md5sum_7899093106a389b38f9e64d5864dbf03e580ab6b

**Comment by stefanalund** [comment]
Did you build for the host platform `osx` first?

**Comment by mlakkadshaw** [comment]
Yes, I am getting these errors when building for osx

**Comment by mlakkadshaw** [comment]
When the run the command `./build-all.sh -Cbr osx` I get the above errors.

**Comment by superdump** [comment]
If you `./build-girepository.sh -Cbr osx` do you see the same problem as in your first comment in this issue? It looks like your PATH environment variable may be broken or something. Or that that part of the build output was irrelevant and the issue was elsewhere.

**Comment by mlakkadshaw** [comment]
Yes, I see the same errors:

env: Studio.app/sdk/platform-tools/:/Applications/Android: No such file or directory
everything-stamp.h error 127

**Comment by mlakkadshaw** [comment]
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in .
Making all in docs
make[3]: Nothing to be done for `all-am'.
Making all in tests
  GEN      everything-stamp.h
env: Studio.app/sdk/platform-tools/:/Applications/Android: No such file or directory
make[2]: *** [everything-stamp.h] Error 127
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
xxd: G*-2.0.gir: No such file or directory
./build-girepository.sh: line 86: G*-2.0.gir: No such file or directory
Marking build successful in gobject-introspection

**Comment by superdump** [comment]
Can you paste the output of `env | grep PATH` here?

**Comment by mlakkadshaw** [comment]
PATH=/Users/mohammed/bin/Sencha/Cmd/3.1.0.256:/Applications/Android Studio.app/sdk/platform-tools/:/Applications/Android Studio.app/sdk/tools/:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/mohammed/db-derby-10.10.1.1-bin/bin:/opt/X11/bin:/usr/local/git/bin

**Comment by superdump** [comment]
I wonder if the space in `Android Studio.app` is causing problems... Can you temporarily remove those from your PATH and try again?

**Comment by mlakkadshaw** [comment]
I reset my path PATH=/bin:/usr/bin  and  ran 
 ./build-girepository.sh -r osx
I get this message on the console:

Making all in docs
make[3]: Nothing to be done for `all-am'.
Making all in tests
  GEN      everything-stamp.h
env: ../g-ir-scanner: Too many levels of symbolic links
make[2]: *** [everything-stamp.h] Error 126
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
xxd: G*-2.0.gir: No such file or directory
./build-girepository.sh: line 86: G*-2.0.gir: No such file or directory
Marking build successful in gobject-introspection

**Comment by superdump** [comment]
Try with -Cbr instead of just -r.

**Comment by mlakkadshaw** [comment]
Same error:

5 warnings generated.
  CC       gthash_test-gthash-test.o
  CCLD     gthash-test
  CC       gi_dump_types-gdump.o
  CC       gi_dump_types-gi-dump-types.o
  CCLD     gi-dump-types
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
  CC       glib_print-glib-print.o
  CCLD     glib-print
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
Making all in docs
make[3]: Nothing to be done for `all-am'.
Making all in tests
  GEN      everything-stamp.h
env: ../g-ir-scanner: Too many levels of symbolic links
make[2]: *** [everything-stamp.h] Error 126
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
xxd: G*-2.0.gir: No such file or directory
./build-girepository.sh: line 86: G*-2.0.gir: No such file or directory
Marking build successful in gobject-introspection

**Comment by mlakkadshaw** [comment]
I ran the command again, and now I am getting this error:

Making all in docs
make[3]: Nothing to be done for `all-am'.
Making all in tests
  GEN      everything-stamp.h
Traceback (most recent call last):
  File "../g-ir-scanner", line 53, in <module>
    from giscanner.scannermain import scanner_main
  File "../giscanner/scannermain.py", line 34, in <module>
    from giscanner.dumper import compile_introspection_binary
  File "../giscanner/dumper.py", line 28, in <module>
    from .gdumpparser import IntrospectionBinary
  File "../giscanner/gdumpparser.py", line 31, in <module>
    from .transformer import TransformerException
  File "../giscanner/transformer.py", line 27, in <module>
    from .girparser import GIRParser
  File "../giscanner/girparser.py", line 26, in <module>
    from .girwriter import COMPATIBLE_GIR_VERSION
  File "../giscanner/girwriter.py", line 25, in <module>
    from .xmlwriter import XMLWriter
  File "../giscanner/xmlwriter.py", line 91, in <module>
    from _giscanner import collect_attributes
ImportError: No module named _giscanner
make[2]: *** [everything-stamp.h] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
xxd: G*-2.0.gir: No such file or directory
./build-girepository.sh: line 86: G*-2.0.gir: No such file or directory
Marking build successful in gobject-introspection

**Comment by mlakkadshaw** [comment]
I tried on different computer and I was able to build the depenedencies succefully, but when I tried to build openWebrtc, using `./build -Cbr osx` I am getting the following error:

rm peerhandler.js_ bridgeserver.js_
  CC       libopenwebrtc_bridge_la-owr_bridge.lo
  CCLD     libopenwebrtc_bridge.la
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
  CC       daemon.o
  CCLD     openwebrtc-daemon
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
Undefined symbols for architecture x86_64:
  "_gst_plugin_nice_register", referenced from:
      _owr_init in libopenwebrtc.a(owr.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [openwebrtc-daemon] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Failed building....

Any ideas why? 

Thanks

**Comment by superdump** [comment]
Looks like you're having the same issue as in issue 194.

**Comment by superdump** [comment]
Sorry, I meant #197

**Comment by sdroege** [comment]
The libnice problem should already be fixed by https://github.com/EricssonResearch/openwebrtc-build-scripts/commit/9fe9423288aa857de4d8d7827575435b835e5613
Can you try rebuilding libnice with the latest build scripts?

**Comment by mlakkadshaw** [comment]
Deleting everything and rebuilding for scratch solved the problem.
Thanks
