### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by dataliven** [EricssonResearch/openwebrtc#198]
Hi there,

I just want to evaluate the solution by building a simple mobile App, but have to build the openwebrtc.jar and openwebrtc_bridge.jar from scratch. Would you please release the built library for IOS and Android so we can have a quick start?

**Comment by stefanalund** [comment]
We are aware of the pains involved, and are looking in to a solution for this. But for now you will need to build OpenWebRTC yourself.

**Comment by stefanalund** [comment]
I'm happy to let you know that we will soon start distributing releases of OpenWebRTC. This will allow you to just add a pre-compiled library to your project without the need to build everything yourself.

Releases will start to be available once we have moved over to our new build system Cerbero: https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero

**Comment by superdump** [comment]
https://github.com/EricssonResearch/openwebrtc/releases
