### ISSUE TITLE
submodules_patches support for Cerbero

### ISSUE THREAD

**Issue by ijsf** [EricssonResearch/openwebrtc#205]
My recent patches for orc require modification of the common/orc.mak file in all gst* as well as the gstreamer repositories. I thought I would be able to use the Cerbero patches feature here, but unfortunately the "common" subdirectory in each of these repositories is a submodule in itself (linking to the gstreamer-common repository), and thus falls outside of the reach of the "git am" command that is invoked by Cerbero's patch implementation.

For this to work easily, Cerbero could use support for a "submodule_patches" feature to be specified in the .recipe. Basically the only thing required would be for Cerbero to chdir into the specified subdirectory and apply the specified patch.

I could do this myself but would like to know your opinion on whether the above is the most suitable approach for this to work.

**Comment by superdump** [comment]
GStreamer will be interested in the patches so you can just submit them upstream. @sdroege and others working on OpenWebRTC are GStreamer maintainers so they can advise how to proceed.

**Comment by ijsf** [comment]
Great to hear that.

However, this feature would still be very helpful as it, in this case, the developer won't have to fork all gst*, gstreamer and gstreamer-common repositories locally, change all submodules, and change all recipes, but could just leverage the Cerbero system instead.

**Comment by ijsf** [comment]
Problem for now seems to have been worked around by patching the Makefiles.

**Comment by superdump** [comment]
The workaround sounds good for now to get things working. :smile:

**Comment by sdroege** [comment]
Patching Makefiles is not going to work, autoreconf/autogen.sh is going to overwrite those changes. Same for Makefile.in. Only Makefile.am should be patched, but those don't contain the content of the common submodule (automake injects them into the Makefile.in).

**Comment by ijsf** [comment]
Patching the `include $(top_srcdir)/common/orc.mak` line in the Makefile.am files has been working fine so far.

**Comment by sdroege** [comment]
Ah yes, that works of course :smile:

**Comment by superdump** [comment]
Closing as this only applied to development of the orc code and some solutions have been presented.
