### ISSUE TITLE
Have bootstrap.sh use Xcode path presented by xcode-select

### ISSUE THREAD

**Issue by msmollin** [EricssonResearch/openwebrtc#206]
I noticed an issue since I'm running solely Xcode 6.2 beta 5 (issues in Xcode 6.1 with security holes in git forced me to update). The application, and thus folder, is "/Applications/Xcode-Beta.app/Contents/Developer" whereas it looks like there's a hardcoded path in bootstrap.sh to "/Applications/Xcode.app/Contents/Developer" for the OS X SDK. The utility called xcode-select will print out the path needed by adding the -p flag.

I fixed it for now by just changing my Xcode-Beta.app to Xcode.app and updating my system's selected xcode using the aformetioned utility. It shouldn't be hardcoded though since that xcode-select utility is installed by default along with Xcode. I could probably patch this myself, but it wouldn't be for a few weeks as I have some travel coming up. Can anyone else take a look in the mean time?

**Comment by superdump** [comment]
I believe this only applied to the build scripts and we have now moved to a new build system.

https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

If you still experience the issue when using cerbero, please create a new issue. Thanks!
