### ISSUE TITLE
Build error - Repo Glib lib, gnome-common, gobject-introspection unavailable

### ISSUE THREAD

**Issue by michael-tourneur** [EricssonResearch/openwebrtc#207]
i downloaded the lastest source code of openwebrtc with dependencies but when i build i get error.
Seems those repo are dead.

file build-glib.sh change line 25
git clone git://anongit.freedesktop.org/gstreamer-sdk/glib
by 
git clone https://github.com/GNOME/glib.git

and

file build-gnome-common.sh line 25
git clone git://git.gnome.org/gnome-common
by 
git clone https://git.gnome.org/browse/gnome-common

file build-gobject-introspection.sh line 25
git://git.gnome.org/gobject-introspection
by
git clone https://git.gnome.org/browse/gobject-introspection

**Comment by sdroege** [comment]
Those repositories are slightly different and contain different versions. The problem you had must've been a transient problem with the freedesktop.org GIT servers, they are running again now at least.
