### ISSUE TITLE
createOffer doesn't match method signature from the spec

### ISSUE THREAD

**Issue by szimek** [EricssonResearch/openwebrtc#208]
According to the spec in both promise based and legacy versions of `createOffer` method, `RTCOfferOptions` parameter is optional, but I'm getting an error telling me that either first or third argument must be an object.

See http://www.w3.org/TR/2015/WD-webrtc-20150210/#h-interface-definition and http://www.w3.org/TR/2015/WD-webrtc-20150210/#h-legacy-interface-extensions.

**Comment by stefanalund** [comment]
@stefhak @adam-be please advise.

**Comment by stefhak** [comment]
I've been using this with Promises for some time now. My code looks like:
    pc.onnegotiationneeded = function () {
        log("in onnegotiationneeded");
        // check signaling state here because Chrome dispatches negotiationeeded during negotiation
        if (pc.signalingState == "stable")
            pc.createOffer().then(localDescCreated).catch(logError);
    };
and seems to work. Is the issue only for apps using the legacy interface?

**Comment by szimek** [comment]
@stefhak I figured out what's wrong. peer.js library passes `connection.options.constraints ` as the third argument, but it may be `undefined`. OpenWebRTC does an explicit check if the first or third argument is an object if it's present: https://github.com/EricssonResearch/openwebrtc/blob/9673b77a0bfe743a6a76a3853984533e2a081cf8/bridge/client/webrtc.js#L442-L452

It works fine in Chrome and Firefox, but breaks OpenWebRTC. I'm not passing any constraints there, so I can simply fix it by changing peer.js library and remove this third param or do `connection.options.constraints || {}`. I'm not sure if OpenWebRTC should be more forgiving, like other browsers. If not, then this issue can be closed.

**Comment by stefhak** [comment]
Thanks, we'd need to discuss if we need to do anything. The third (legacy API) or first (Promise API) argument must be an object according to the spec, but perhaps it is inconvenient to not accept undefined.

**Comment by stefhak** [comment]
I tested a bit more, it seems that while FF (Nightly) accepts an undefined options argument, e.g. a string is not accepted. Error message:
"TypeError: Argument 1 of mozRTCPeerConnection.createOffer can't be converted to a dictionary."

**Comment by stefhak** [comment]
One more update: seems we should change: Object, Null and Undefined should be allowed, see http://heycam.github.io/webidl/#es-dictionary

**Comment by stefhak** [comment]
I think this issue should be closed. The PR (https://github.com/EricssonResearch/openwebrtc/issues/296) that has been integrated fixes this.

**Comment by stefanalund** [comment]
Really? Did this require changes in libnice and other places?

**Comment by stefanalund** [comment]
Sorry, my mistake, wrong Issue :-)
