### ISSUE TITLE
App wrapping a hosted-app-url could get approved by the AppStore?

### ISSUE THREAD

**Issue by zevarito** [EricssonResearch/openwebrtc#213]
Hi, I am just playing with this (didn't finish the build yet) and have a few concerns about app publication.

If I create a new IOS app based on OpenWebRtc and it just point to an URL outside like the example, it cold get approved? AppStore doesn't complain about it just being a wrap to an URL instead a local application?

Thanks!

**Comment by stefanalund** [comment]
Obviously we cannot make any guarantees that Apple will approve your application, but by using OpenWebRTC and integrating it in your application you have added value outside a simple web view app that just wraps a web app. Apple's UIWebView does not have WebRTC until you integrate with OpenWebRTC.

**Comment by zevarito** [comment]
Thanks!

On Thursday, March 5, 2015, Stefan Ålund <notifications@github.com> wrote:

> Obviously we cannot make any guarantees that Apple will approve your
> application, but by using OpenWebRTC and integrating it in your application
> you have added value outside a simple web view app that just wraps a web
> app. Apple's UIWebView does not have WebRTC until you integrate with
> OpenWebRTC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EricssonResearch/openwebrtc/issues/213#issuecomment-77415877>
> .
>


-- 
Sent from Gmail Mobile
