### ISSUE TITLE
Use cerbero as the official build system

### ISSUE THREAD

**Issue by superdump** [EricssonResearch/openwebrtc#222]
cerbero is the build system used by GStreamer and GStreamer is our primary dependency. It makes sense to share the same build system. cerbero also brings some shiny benefits:

* Rebuild only the dependencies that need rebuilding when updating
* Paralellised builds for faster build times
* More mature and tested
* More people maintaining the same code on more platforms / machines
* 64-bit arm support
* Windows support for the majority of our dependencies and we just need to fix support for a few more to have Windows support in OpenWebRTC
* Builds iOS / Mac OS X frameworks and Debian packages
* ...much more

**Comment by sdroege** [comment]
What's left to be done for this?

Currently pending issues I'm aware of are:
- it either fails on ios/arm64 (with old libffi) at runtime, or fails to build on ios/arm (with new libffi)
- Android packaging is not finished yet

**Comment by frozeus** [comment]
Would there be a possibility, to disable python bindings and the building of tests. This could avoid to build lot of dependencies not required by the libopenwebrtc.

#159

**Comment by ford-prefect** [comment]
One more todo item for this:

* Update examples to use the Cerbero-generated framework

**Comment by superdump** [comment]
@frozeus: GObject Introspection is for Python and JavaScript bindings. So it is needed for the JavaScript bridge code and generally otherwise if people want bindings. We can make this optional as a separate issue.

My definition of done is basically that it builds for all platforms, the tests, examples and openwebrtc-daemon for each platform work as expected (or at least do not regress from the build script behaviour) when using the cerbero build results.

In practice that is hopefully just what @sdroege and @ford-prefect said.

**Comment by superdump** [comment]
Also Android build results are not fully working yet afaik. @rugvip and @nirbheek are working on that

**Comment by frozeus** [comment]
@superdump My issue is more with webkitgtk-3.0 which requires GTK, etc... and for the example is just that they require libsoup and json-glib.

**Comment by superdump** [comment]
We don't ever build GTK afaik. But there is a separate issue about splitting out the bridge to avoid building JavaScriptCore from webkitgtk. This issue is about moving to cerbero and getting all of that working.

**Comment by nirbheek** [comment]
We indeed don't build GTK+; neither in the owrtc build scripts nor with Cerbero. JavaScriptCore only depends on GLib and ICU. The OpenWebRTC tests do pull in libsoup and json-glib, and it should be possible to make those optional.

**Comment by superdump** [comment]
Sounds like @Rugvip has tested Android pre-data channel changes with cerbero and that all works.

**Comment by Rugvip** [comment]
@superdump Not quite. It didn't work pre-data channel because of the gnutls issue, but I haven't tested it since the merge with master. I did get it to build post-data channel thought, but I haven't tested it yet.

**Comment by sdroege** [comment]
@nirbheek had a fix for the gnustl issue earlier today

**Comment by nirbheek** [comment]
The GNU C++ STL issue should be fixed now. Another item on the list of things to do for this:

1) Move cerbero from nirbheek/ to EricssonResearch/
2) Rebase the openwebrtc branch on top of master once before the move (we started merging all changes from master a while back)

**Comment by sdroege** [comment]
Which merging here you mean the Android autotools changes?

**Comment by nirbheek** [comment]
I meant that we were merging cerbero's origin/master into nirbheek/openwebrtc instead of rebasing so that people wouldn't have to do `git pull --force`. We should rebase that one last time, and then continue merging in the future.

**Comment by superdump** [comment]
I'm working on the details of 1) and hope to sort that out soon.

**Comment by nirbheek** [comment]
I created a wiki page with a list of configurations we need to test to be sure that Cerbero works:

https://github.com/EricssonResearch/openwebrtc/wiki/Cerbero-Testing

If everyone could commit to whichever configurations they can test (and/or add more), that would be great. :)

**Comment by superdump** [comment]
Nice! I added a couple more iOS devices of interest.

**Comment by superdump** [comment]
We've now moved over but we need to test everything.

**Comment by superdump** [comment]
OS X stuff works well. iOS stuff works pretty well apart from known issues not related to cerbero. Android is working well apart from non-cerbero issues. Someone needs to confirm Linux and then I think we can close this.

The only outstanding problem really is the Android icu build bug with append_env. @Rugvip thinks it could be something to do with https://github.com/EricssonResearch/cerbero/blob/master/recipes/icu.recipe#L66 where a decorator is used to apply append_env stuff but in the code block for non-host targets (i.e. only on Android builds because we don't build ICU for iOS) there is some stuff that retrieves the environment, stores it in a variable and then restores it. Maybe that's a clue?

**Comment by superdump** [comment]
Right, there is the append_env bug which seems to sometimes work if your run package openwebrtc, the build fails, run buildone for the failed package which succeeds and then run package again. It's an odd bug which we have tried to debug a bit and will eventually get fixed but I don't consider it a blocker for the move and its reported elsewhere.

@ford-prefect reported that the test programs work on Linux. As such, I'm going to close this ticket.

Thanks for all the testing and input!

**Comment by ijsf** [comment]
FYI: my append_env issue seems to be bogus and caused by some other means.
