### ISSUE TITLE
Excessively slow handshaking on iOS/armv7

### ISSUE THREAD

**Issue by ijsf** [EricssonResearch/openwebrtc#236]
When using Bowser and demo.openwebrtc.io:38080, setting up a call between A and B (see below) takes excessively long (5 minutes or so).

A-side: iOS 8.1.3, iPad Mini Gen 1
B-side: Chrome 41.0.2272.76 (64-bit) on OS X 10.10

**Comment by superdump** [comment]
Is that time to first frame? If not, what is measured?

**Comment by ijsf** [comment]
Correct, time to first frame.

**Comment by sdroege** [comment]
I'm looking into some issues with libnice that can cause this currently.

Also see https://github.com/EricssonResearch/openwebrtc/issues/186

**Comment by ijsf** [comment]
Compiling with -O2 flag (-Os is currently standard for `config/ios.config`) helps to reduce the required time.

**Comment by sdroege** [comment]
That would be unrelated to what I'm looking into then. Do you have some profiler information about what takes so much more time with -Os than with -O2?

**Comment by ijsf** [comment]
By the way, it seems that the first attempt is always failing. I'm always getting this message before a whole lot of gst stuff reappears:

    erdtlssrtpdemux src/gsterdtlssrtpdemux.c:136:sink_chain:<dtls-srtp-demux> received invalid buffer: 1

**Comment by sdroege** [comment]
I think that didn't happen anymore with my changes to delay DTLS until the ICE connection is set up

**Comment by ijsf** [comment]
The above message occurred with latest master of OpenWebRTC and all dependencies.

**Comment by ijsf** [comment]
Duplicate of #186.
