### ISSUE TITLE
Inconsistent capture frame rate on iOS/armv7

### ISSUE THREAD

**Issue by ijsf** [EricssonResearch/openwebrtc#243]
I have been testing the local video capturing in the iOS build of OpenWebRTC on an iPad Mini Gen 1 (armv7) using demo.openwebrtc.io:38080 and noticed that the frame rate of the local video frame is very inconsistent. At times it is reasonably fast (15 to 30 Hz), but most of the time it is way too low (1 Hz).

The video capturing is handled by the sys/applemedia code in gst-plugins-bad. I've been checking the code and I think that the `activeVideoMaxFrameDuration` is not set properly: it is set to the maximum frame duration, while I believe it should be set to the minimum frame duration as to "fix" the frame rate to the highest possible value.

I have been testing a patch in my fork and noticed the local video performance is much better with it.

https://github.com/ijsf/OpenWebRTC-gst-plugins-bad/commit/887700d3eb85f35643c4246ef53608232b9b4528

**Comment by sdroege** [comment]
This is probably the same as https://github.com/EricssonResearch/openwebrtc/issues/96

**Comment by ijsf** [comment]
Yeah, seems similar. Good thing is the fix seems to be consistently working here.

**Comment by superdump** [comment]
What does the capture preset do? Should it be configurable? Should it be a separate patch? Can you submit those patches upstream?

**Comment by ijsf** [comment]
Fixed that. How do I submit upstream?

https://github.com/ijsf/OpenWebRTC-gst-plugins-bad/commit/887700d3eb85f35643c4246ef53608232b9b4528

**Comment by superdump** [comment]
Create an account at http://bugzilla.gnome.org/ and then create a ticket against gst-plugins-bad git master for avfvideosrc I guess: https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer

**Comment by sdroege** [comment]
There's also something with autofocus settings that can improve the situation here according to @alessandrod

**Comment by ijsf** [comment]
I'll probably submit this patch upstream tomorrow.

**Comment by ijsf** [comment]
Just discussed with @ikonst and realized that this patch is pretty WebRTC specific and might upset some non-WebRTC use cases. Any suggestions?

**Comment by superdump** [comment]
@ijsf - which change is WebRTC-specific?

**Comment by ijsf** [comment]
@superdump Apple allows you to set an upper and lower bound on the capture rate. For our WebRTC case, only the highest possible capture rate is good enough. There must be a reason for option to use a varying rate though, perhaps light conditions and such? Perhaps the min/max should be a configurable setting instead.

https://developer.apple.com/library/prerelease/ios/documentation/AVFoundation/Reference/AVCaptureDevice_Class/index.html

**Comment by ijsf** [comment]
Patch has been submitted at https://bugzilla.gnome.org/show_bug.cgi?id=747403

**Comment by superdump** [comment]
I think that change was already merged by @alessandrod a few weeks ago. Can you compare against GStreamer master?

**Comment by superdump** [comment]
Yup: http://cgit.freedesktop.org/gstreamer/gst-plugins-bad/commit/sys/applemedia/avfvideosrc.m?id=f62dda74cc7f1396ce2b49679d8a35a2fe182c93

Closing. Thanks! :smile:
