### ISSUE TITLE
rtpsource cannot interpolate rtp time (green video)

### ISSUE THREAD

**Issue by ijsf** [EricssonResearch/openwebrtc#244]
Though I'd create a separate issue for this one, although the resulting problems are still occassional green/missing video on the A-side, and consistently green video on the B-side.

I have been testing the local video capturing in the iOS build of OpenWebRTC on an iPad Mini Gen 1 (armv7) using demo.openwebrtc.io:38080.

A-side: iOS 8.1.3, iPad Mini Gen 1
B-side: Chrome 41.0.2272.76 (64-bit) on OS X 10.10

Turned on GST_DEBUG with warnings and noticed that there are a number of rtp-related warnings appearing in the log around the time that the video turns green:

    rtpsource rtpsource.c:1412:rtp_source_get_new_sr: no clock-rate, cannot interpolate rtp time

    /GstPipeline:transport-agent-1/GstBin:transport_bin_1/GstBin:send-output-bin-1/GstErDtlsSrtpEnc:dtls_srtp_rtp_encoder_1/GstFunnel:funnel.GstPad:src: caps = "application/x-srtcp\,\ srtp-key\=\(buffer\)95dc7f02fb08cee18153faecf1ed16442e3899f029824b7b903f58bba0dc\,\ srtp-cipher\=\(string\)aes-128-icm\,\ srtp-auth\=\(string\)hmac-sha1-80\,\ srtcp-cipher\=\(string\)aes-128-icm\,\ srtcp-auth\=\(string\)hmac-sha1-80"
    /GstPipeline:transport-agent-1/GstBin:transport_bin_1/GstBin:send-output-bin-1/GstErDtlsSrtpEnc:dtls_srtp_rtp_encoder_1.GstGhostPad:src: caps = "application/x-srtcp\,\ srtp-key\=\(buffer\)95dc7f02fb08cee18153faecf1ed16442e3899f029824b7b903f58bba0dc\,\ srtp-cipher\=\(string\)aes-128-icm\,\ srtp-auth\=\(string\)hmac-sha1-80\,\ srtcp-cipher\=\(string\)aes-128-icm\,\ srtcp-auth\=\(string\)hmac-sha1-80"
    /GstPipeline:transport-agent-1/GstBin:transport_bin_1/GstBin:send-output-bin-1/GstNiceSink:nice-rtp-sink-1.GstPad:sink: caps = "application/x-srtcp\,\ srtp-key\=\(buffer\)95dc7f02fb08cee18153faecf1ed16442e3899f029824b7b903f58bba0dc\,\ srtp-cipher\=\(string\)aes-128-icm\,\ srtp-auth\=\(string\)hmac-sha1-80\,\ srtcp-cipher\=\(string\)aes-128-icm\,\ srtcp-auth\=\(string\)hmac-sha1-80"
    /GstPipeline:transport-agent-1/GstBin:transport_bin_1/GstBin:send-output-bin-1/GstErDtlsSrtpEnc:dtls_srtp_rtp_encoder_1.GstGhostPad:src.GstProxyPad:proxypad9: caps = "application/x-srtcp\,\ srtp-key\=\(buffer\)95dc7f02fb08cee18153faecf1ed16442e3899f029824b7b903f58bba0dc\,\ srtp-cipher\=\(string\)aes-128-icm\,\ srtp-auth\=\(string\)hmac-sha1-80\,\ srtcp-cipher\=\(string\)aes-128-icm\,\ srtcp-auth\=\(string\)hmac-sha1-80"

The above seems to happen just before/after a pipeline change?

During the video call I'm also seeing the following rtpjitterbuffer warnings:

    rtpjitterbuffer rtpjitterbuffer.c:449:calculate_skew: resync to time 0:00:15.217295000, rtptime 6:15:23.385266666
    rtpjitterbuffer rtpjitterbuffer.c:487:calculate_skew: delta - skew: 0:00:03.569738000 too big, reset skew

**Comment by ijsf** [comment]
I worked around the `cannot interpolate rtp time` issue in my fork by implementing a `request-pt` callback for `rtpjitterbuffer` that passes on the caps including the `clock-rate`. Does not seem to completely solve the green video issue.

https://github.com/ijsf/openwebrtc/commit/997ac7e5b5a07572de2d6cd554d4788448c75d34

**Comment by sdroege** [comment]
For which pt is it requesting the caps? Isn't it complaining about no clock-rate on the RTCP caps?

But it would make sense probably to keep a pt->caps map around and let rtpbin request caps from that in any case.

**Comment by ijsf** [comment]
I'm not sure yet. What I can tell from the logs is that there is a proxypad `GstRtpBin:rtpbin.GstGhostPad:recv_rtp_src_1_2426246665_100.GstProxyPad` and it contains a clock-rate in the caps.

**Comment by ijsf** [comment]
It seems something odd is going on with the timing. Perhaps this has to do with the performance on the iPad, or with the system time synchronization mechanism on iOS that gstreamer apparently relies on.

I've tried to change rtpbin to use the pipeline running-time instead of the system clock (if I understand this correctly, see discussion at http://comments.gmane.org/gmane.comp.video.gstreamer.bugs/72342), and the above messages as well as the green video disappeared altogether. Video was significantly lagged (5 seconds or so) but was coming through nicely.

Patched this in my own fork: https://github.com/ijsf/openwebrtc/commit/2341b1b75fdad0c228384253a6ccfb81c434c370

**Comment by sdroege** [comment]
Yeah if everything is too slow, RTP won't work very nicely.

**Comment by superdump** [comment]
It has to be real-time! :smiley:

**Comment by ijsf** [comment]
Although some commits in my fork may improve RTP handling for non real-time cases, the actual green video issue seems to be unrelated to RTP and can be closed. See: https://github.com/EricssonResearch/openwebrtc/issues/260
