### ISSUE TITLE
Compilation issue gst-plugins-base-1.0

### ISSUE THREAD

**Issue by ijsf** [EricssonResearch/openwebrtc#250]
When building `gst-plugins-base-1.0` for ios/armv7:

    gstsocketsrc.c:52:10: fatal error: 'gst/net/gstnetcontrolmessagemeta.h' file not found
    #include <gst/net/gstnetcontrolmessagemeta.h>
             ^
    1 error generated.

**Comment by sdroege** [comment]
If you rebuild GStreamer core first, this error should go away. There was new API added.
