### ISSUE TITLE
Execute local media operations on the main owr thread

### ISSUE THREAD

**Issue by Rugvip** [EricssonResearch/openwebrtc#253]
I had some trouble with the main thread locking up on Android when creating a simple self-view, and it turned out that a `WindowRegistry.get().register(mTag, surface);` call ended up doing all the work of setting up the entire pipeline on the calling thread.

Looking at the transport agent it seems like most operations are scheduled on the main thread, while most local media operations are executed on the calling thread. Imo we should make sure that at least all functions that now or in the future may result in a large amount of work should schedule the task on the main owr thread.

**Comment by sdroege** [comment]
:+1:

**Comment by superdump** [comment]
Agreed.
