### ISSUE TITLE
openwebrtc build failure for linux Ubuntu 14.04 LTS 

### ISSUE THREAD

**Issue by ravindrabharathi** [EricssonResearch/openwebrtc#257]
Hi all

I've been trying to build openwebrtc for a Linux host and then from there try and build the library for Android. I use a ubuntu VM guest 14.04 LTS . The issue that I'm facing now is that a build for linux fails . I'm pasting the output below. Any insights into why it fails would help. 
Thanks

./build.sh -Cbr linux
This script will add the .local suffix to all hooks already in the .git/hooks directory
and create symbolic links to the hooks in git_hooks/ directory.
clean_source, /home/ravindra/openwebrtc
Trying default toolchain
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1858: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
autoreconf: configure.ac: tracing
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1858: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1858: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
autoreconf: running: /home/ravindra/.openwebrtc/bin/autoconf --force
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1858: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
autoreconf: running: /home/ravindra/.openwebrtc/bin/autoheader --force
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1858: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:16: warning: AC_ARG_PROGRAM was called before AC_CANONICAL_TARGET
../../lib/autoconf/general.m4:1858: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:16: the top level
autoreconf: no config.status: cannot re-make
autoreconf: Leaving directory `.'
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-unknown-linux-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for x86_64-unknown-linux-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking for x86_64-unknown-linux-gcc... no
checking for x86_64-unknown-linux-objcc... no
checking for x86_64-unknown-linux-objc... no
checking for x86_64-unknown-linux-cc... no
checking for x86_64-unknown-linux-CC... no
checking for gcc... gcc
checking whether we are using the GNU Objective C compiler... no
checking whether gcc accepts -g... no
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc -std=gnu99... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for x86_64-unknown-linux-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-unknown-linux-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-unknown-linux-ar... no
checking for ar... ar
checking for archiver @FILE support... @
checking for x86_64-unknown-linux-strip... strip
checking for x86_64-unknown-linux-ranlib... no
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc -std=gnu99 object... ok
checking for sysroot... no
checking for x86_64-unknown-linux-mt... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... yes
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for x86_64-unknown-linux-pkg-config... no
checking for pkg-config... /home/ravindra/.openwebrtc/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GLIB... yes
checking for GSTREAMER... yes
checking for NICE... yes
checking for GSTREAMER_SCTP... yes
checking for ORC... yes
checking for JSON_GLIB... yes
checking for LIBSOUP... yes
checking whether to build bridge or not... yes
checking for SEED... yes
checking for gobject-introspection... yes
checking for gtkdoc-check... /home/ravindra/.openwebrtc/bin/gtkdoc-check
checking for gtkdoc-rebase... /home/ravindra/.openwebrtc/bin/gtkdoc-rebase
checking for gtkdoc-mkpdf... /home/ravindra/.openwebrtc/bin/gtkdoc-mkpdf
checking whether to build gtk-doc documentation... no
checking whether to build debug or not... no
checking whether to build static owr or not... yes
checking for PULSE... yes
checking for V4L2... yes
checking whether to generate java bindings or not... no
checking for jar installation path... ${exec_prefix}/lib/jni
checking for javadoc installation path... ${prefix}/share/javadoc/openwebrtc
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating bridge/Makefile
config.status: creating bridge/openwebrtc-bridge-0.1.pc
config.status: creating bridge/client/Makefile
config.status: creating bridge/seed/Makefile
config.status: creating bridge/shared/Makefile
config.status: creating bridge/worker/Makefile
config.status: creating owr/Makefile
config.status: creating owr/openwebrtc-0.1.pc
config.status: creating transport/Makefile
config.status: creating local/Makefile
config.status: creating tests/Makefile
config.status: creating bindings/Makefile
config.status: creating bindings/java/Makefile
config.status: creating docs/Makefile
config.status: creating docs/reference/Makefile
config.status: creating docs/reference/owr/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

Now type 'make' to compile this module.

patching file libtool
Hunk #1 succeeded at 5718 (offset 3 lines).
Hunk #2 succeeded at 5964 (offset 3 lines).
Hunk #3 succeeded at 6701 (offset 3 lines).
Hunk #4 succeeded at 6874 (offset 3 lines).
Hunk #5 succeeded at 6882 (offset 3 lines).
Hunk #6 succeeded at 7556 (offset 3 lines).
Hunk #7 succeeded at 8452 (offset 3 lines).
Hunk #8 succeeded at 9182 (offset 3 lines).
make  all-recursive
make[1]: Entering directory `/home/ravindra/openwebrtc/build/x86_64-unknown-linux'
Making all in transport
make[2]: Entering directory `/home/ravindra/openwebrtc/build/x86_64-unknown-linux/transport'
  CC       owr_candidate.lo
  CC       owr_payload.lo
  CC       owr_audio_payload.lo
  CC       owr_video_payload.lo
  CC       owr_session.lo
  CC       owr_media_session.lo
  CC       owr_transport_agent.lo
  CC       owr_remote_media_source.lo
  CC       owr_data_channel.lo
  CC       owr_data_session.lo
  CCLD     libopenwebrtc_transport.la
make[2]: Leaving directory `/home/ravindra/openwebrtc/build/x86_64-unknown-linux/transport'
Making all in local
make[2]: Entering directory `/home/ravindra/openwebrtc/build/x86_64-unknown-linux/local'
  CC       owr_local.lo
  CC       owr_local_media_source.lo
  CC       owr_media_renderer.lo
  CC       owr_audio_renderer.lo
  CC       owr_video_renderer.lo
  CC       owr_image_renderer.lo
  CC       owr_image_server.lo
  CC       owr_window_registry.lo
  CC       owr_device_list.lo
  OBJCLD   libopenwebrtc_local.la
make[2]: Leaving directory `/home/ravindra/openwebrtc/build/x86_64-unknown-linux/local'
Making all in owr
make[2]: Entering directory `/home/ravindra/openwebrtc/build/x86_64-unknown-linux/owr'
python /home/ravindra/openwebrtc/owr/symbols_to_sym.py /home/ravindra/openwebrtc/libopenwebrtc.exp libopenwebrtc.sym x86_64-unknown-linux-gnu
make  all-am
make[3]: Entering directory `/home/ravindra/openwebrtc/build/x86_64-unknown-linux/owr'
  CC       owr.lo
  CC       owr_types.lo
  CC       owr_media_source.lo
  CC       owr_utils.lo
python /home/ravindra/openwebrtc/owr/symbols_to_source.py /home/ravindra/openwebrtc/libopenwebrtc.exp owr_require_symbols.c x86_64-unknown-linux-gnu
  CC       owr_require_symbols.lo
  CCLD     libopenwebrtc.la
  GISCAN Owr-0.1.gir
./.libs/libopenwebrtc.so: undefined reference to `eglCreateWindowSurface'
./.libs/libopenwebrtc.so: undefined reference to `eglBindAPI'
./.libs/libopenwebrtc.so: undefined reference to `eglCreateContext'
./.libs/libopenwebrtc.so: undefined reference to `eglMakeCurrent'
./.libs/libopenwebrtc.so: undefined reference to `eglDestroySurface'
./.libs/libopenwebrtc.so: undefined reference to `eglGetDisplay'
./.libs/libopenwebrtc.so: undefined reference to `eglChooseConfig'
./.libs/libopenwebrtc.so: undefined reference to `eglInitialize'
./.libs/libopenwebrtc.so: undefined reference to `eglGetProcAddress'
./.libs/libopenwebrtc.so: undefined reference to `eglCreatePbufferSurface'
./.libs/libopenwebrtc.so: undefined reference to `eglQueryString'
./.libs/libopenwebrtc.so: undefined reference to `eglGetCurrentContext'
./.libs/libopenwebrtc.so: undefined reference to `eglDestroyContext'
./.libs/libopenwebrtc.so: undefined reference to `eglReleaseThread'
./.libs/libopenwebrtc.so: undefined reference to `eglSwapBuffers'
./.libs/libopenwebrtc.so: undefined reference to `eglGetError'
./.libs/libopenwebrtc.so: undefined reference to `eglTerminate'
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['/bin/bash', '../libtool', '--mode=link', '--tag=CC', '--silent', 'gcc', '-o', '/home/ravindra/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspect8NAiBz/Owr-0.1', '-export-dynamic', '-fPIC', '-I/home/ravindra/openwebrtc/openwebrtc-deps-x86_64-linux/include', '-I/home/ravindra/openwebrtc/framework', '-L/home/ravindra/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '-L/home/ravindra/openwebrtc/openwebrtc-deps-x86_64-linux/lib/gstreamer-1.0', '-L/home/ravindra/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '/home/ravindra/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspect8NAiBz/Owr-0.1.o', '-L.', 'libopenwebrtc.la', '-L/home/ravindra/.openwebrtc/lib', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0', '-lintl']' returned non-zero exit status 1
make[3]: *** [Owr-0.1.gir] Error 1
make[3]: Leaving directory `/home/ravindra/openwebrtc/build/x86_64-unknown-linux/owr'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/ravindra/openwebrtc/build/x86_64-unknown-linux/owr'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ravindra/openwebrtc/build/x86_64-unknown-linux'
make: *** [all] Error 2
Failed building....

**Comment by entd** [comment]
See this patch of mine: https://github.com/EricssonResearch/openwebrtc/pull/251, or either read comments on pull request and do as they say and disable egl (build gstreamer with  `--disable-egl`). Someone should patch this up (it is trivial, however someone should consider what right course should be).

**Comment by ravindrabharathi** [comment]
Thank you very much. The patch worked.

**Comment by siva-t** [comment]
Hi,
Please give some samples to test the openwebrtc in ubuntu? 
Thanks

**Comment by stefanalund** [comment]
@siva-t have a look here: https://github.com/EricssonResearch/openwebrtc/tree/master/tests
