### ISSUE TITLE
Recipe 'gst-plugins-bad-1.0' failed at the build step 'compile'

### ISSUE THREAD

**Issue by zevarito** [EricssonResearch/openwebrtc#262]
I am stuck with this error, please let me know if you identify what is happening. Thanks!

- branch openwebrtc
- osx 10.9.5

Log excerpt:

make[2]: *** [applemedia] Error 2
make[2]: *** Waiting for unfinished jobs....
libtool: link: ( cd ".libs" && rm -f "libgstapplemedia_nonpublic.la" && ln -s "../libgstapplemedia_nonpublic.la" "libgstapplemedia_nonpublic.la" )
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Running command 'make -j4'

Full log here:  https://gist.github.com/zevarito/c4e721ca683881bcddbc

**Comment by Rugvip** [comment]
That missing symbol is new in iOS 8.0, do you have the latest version of Xcode? (6.2, 6C131e)

**Comment by zevarito** [comment]
Sadly I Will be not in front of the computer until a few hours. I think I
have sdk 8.1 and Xcode 5.x but honestly don't sure.

Should I update to latest Xcode?

On Friday, March 20, 2015, Patrik Oldsberg <notifications@github.com> wrote:

> That missing symbol is new in iOS 8.0, do you have the latest version of
> Xcode? (6.2, 6C131e)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EricssonResearch/openwebrtc/issues/262#issuecomment-84134389>
> .
>


-- 
Sent from Gmail Mobile

**Comment by zevarito** [comment]
@Rugvip I've updated Xcode to 6.2 but same thing if I try to rebuild.

Do you think delete all and bootstrap again will make the difference?

**Comment by sdroege** [comment]
It shouldn't make a difference, no. The problem is that the specific API that it complains about there is only available since OSX 10.10. It seems like your OSX SDK is older than that.

**Comment by sdroege** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=746631

**Comment by zevarito** [comment]
@sdroege Seems I need to upgrade to Yosemite :/

Closing this issue, thanks!
