### ISSUE TITLE
Eliminate armv7s from Cerbero

### ISSUE THREAD

**Issue by ikonst** [EricssonResearch/openwebrtc#263]
Remove the obsolete armv7s architecture from Cerbero (both as separate configuration and as part of iOS universal builds).

Arguments:
* http://www.cocoanetics.com/2014/10/xcode-6-drops-armv7s/
* https://github.com/openframeworks/openFrameworks/issues/3423

**Comment by ijsf** [comment]
FYI: XCode 6 has removed armv7s from the default standard architectures, hinting that armv7s will likely be deprecated.

**Comment by superdump** [comment]
@nirbheek @sdroege @alessandrod @ford-prefect - I guess this is something for cerbero upstream as well, right?

**Comment by ford-prefect** [comment]
Based on this, it sounds like maybe we don't want to drop this yet?

http://www.cocoanetics.com/2014/10/xcode-6-drops-armv7s/

**Comment by ikonst** [comment]
@ford-prefect - good point. Now I feel inclined not to remove it.

**Comment by nirbheek** [comment]
So, the only advantage is the build time, which will be alleviated when we start doing binary releases. Also, Arun pointed out on IRC that downstreams might be using armv7s in their applications, and there's no reason why we should prevent them from doing so. 

I'm in agreement with Arun that we shouldn't remove armv7s from Cerbero.

**Comment by sdroege** [comment]
Agreed, let's reconsider this once Apple really removes armv7s support.

**Comment by ikonst** [comment]
http://wanderingcoder.net/2010/07/19/ought-arm/

> Yep, ARMv7s does include support for integer division in hardware, but that only applies for new devices, existing devices are still unable to do so and will keep using the ARMv7 code and divide in software, so don’t just go division-happy yet.

For example, audioconvert uses integer division, which makes it 20 times (!) more efficient on arm64 (and probably armv7s but I haven't tested) than on armv7. (Though, when it comes to audioconvert, we're best not using it anywhere.)
