### ISSUE TITLE
Build libsrtp against openssl

### ISSUE THREAD

**Issue by superdump** [EricssonResearch/openwebrtc#264]
cerbero should build libsrtp against openssl for both compatibility and performance reasons. OpenSSL, last I tested, was significantly better performance than otherwise. OpenSSL 1.0.2 or newer is needed for compatibility with Firefox nightlies (a specific set of more secure ciphers as I recall.)

**Comment by sdroege** [comment]
@nirbheek this change has to stay in the openwebrtc cerbero though, or become a (upstream not enabled by default) variant.

Reason for that is that upstream cerbero will
a) ship GNUTLS for glib-networking, libsoup and stuff... and I really don't want to ship two TLS implementation, each with their own security bugs
b) ship GPL licensed software... and the openssl license is GPL incompatible, so we can't ship openssl and GPL software together

Both points are not valid for openwebrtc though (unless we start including e.g. libsoup for native HTTP and websocket support, then a) would apply).

**Comment by sdroege** [comment]
(sidenote: all this is also the reason why I look into porting the DTLS plugin to GNUTLS, to allow it running against both openssl and GNUTLS... maybe doing the same for libsrtp would be useful too, just that nettle should be enough already. It doesn't need a full features TLS stack AFAICS)

**Comment by superdump** [comment]
test-client uses libsoup I think. I don't want to have to build two TLS stacks either but if there are benefits to doing so then I'm fine with doing it.

Good point about GPL a compatibility. I was aware of that but had forgotten upstream ships GPL.

**Comment by sdroege** [comment]
As long as test-client only uses plain HTTP and not HTTPS, then we can get away with not shipping GNUTLS.

**Comment by superdump** [comment]
Merged a patch to do this into cerbero: https://github.com/EricssonResearch/cerbero/commit/a2879ca7a9affaef0b355c98e7300b51a7629c9d Closing.
