### ISSUE TITLE
OpenSSL context broken and DTLS non-functional

### ISSUE THREAD

**Issue by ijsf** [EricssonResearch/openwebrtc#273]
I'm having issues with the latest version of OpenSSL (1.0.2a) and OpenWebRTC. Testing with stefanalund's NativeDemo for iOS to isolate problems (https://github.com/EricssonResearch/openwebrtc-examples/pull/49) and calling from Chrome (OS X) to iOS 8.x (iPad Air Gen 1).

Specifically, the creation of an OpenSSL context is failing with the following error:

    dtlsagent gstdtlsagent.c:180:gst_dtls_agent_init:<GstDtlsAgent@0x1782ef70> Error creating SSL Context: error:140A90A1:SSL routines:func(169):reason(161)

As a result, the code in `gstdtlsagent` and everything depending on it is failing and asserting the application, making OpenWebRTC unusable on iOS/armv7.

The full log with GST_DEBUG on 2 (warning) can be found here: https://gist.github.com/ijsf/d28df97219856c3b4f36

**Comment by superdump** [comment]
@Rugvip ideas?

**Comment by Rugvip** [comment]
The error is `SSL_R_LIBRARY_HAS_NO_CIPHERS`, which happens if you don't call `SSL_library_init`, but I don't see how that could stop working. I guess it could also be a build issue, related to the switch to 1.0.2. Perhaps cleaning the openssl dist and then rebuilding might help.

**Comment by ijsf** [comment]
Issue is caused by `SSL_library_init` in gnutls being called instead of OpenSSL. This indicates that something is going wrong during linking.

**Comment by ijsf** [comment]
I'm linking against all .a files in dist/ios_armv7/lib/static and dist/ios_armv7/lib/gstreamer-1.0/static. See this list for all files: https://gist.github.com/ijsf/8074ff2e917bb86a1b31

**Comment by ijsf** [comment]
Looking at the linked files, the problem seems to be that I am linking against both gnutls and openssl.

I have been following the Cerbero wiki manual at https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero and specifically the .a static linkage steps for iOS at Development points 3 and 4. Dragging in all .a files causes both gnutls and openssl to be linked into the same project, which is quite unfortunate.

Updated the wiki and added a warning.
