### ISSUE TITLE
Cerbero build failed - permission denied

### ISSUE THREAD

**Issue by simonpi** [EricssonResearch/openwebrtc#278]
Hello there, 

I am building OpenWebRTC on my Ubuntu 14.04 64bit using the cerbero script. And I have the following error while typing ./cerbero-uninstalled package openwebrtc

szpi@szpi:~/Pobrane/cerbero$ ./cerbero-uninstalled package openwebrtc
WARNING: Using default configuration because /home/szpi/.cerbero/cerbero.cbc is missing
Building the following recipes: libffi zlib glib orc bzip2 gmp openssl gobject-introspection gtk-doc-lite gstreamer-1.0 gst-plugins-base-1.0 libvpx gst-plugins-good-1.0 openh264 opus libsrtp gst-plugins-bad-1.0 libnice gstreamer-1.0-static gst-plugins-base-1.0-static gst-plugins-good-1.0-static gst-plugins-bad-1.0-static libnice-static gettext intltool gnome-js-common icu javascriptcoregtk seed libusrsctp openwebrtc-gst-plugins json-glib libxml2 libsoup openwebrtc openwebrtc-gst-plugins-static
[(1/36) libffi -> already built ]
[(2/36) zlib -> already built ]
[(3/36) glib -> already built ]
[(4/36) orc -> already built ]
[(5/36) bzip2 -> already built ]
[(6/36) gmp -> already built ]
[(7/36) openssl -> already built ]
[(8/36) gobject-introspection -> already built ]
[(9/36) gtk-doc-lite -> already built ]
[(10/36) gstreamer-1.0 -> already built ]
[(11/36) gst-plugins-base-1.0 -> already built ]
[(12/36) libvpx -> already built ]
[(13/36) gst-plugins-good-1.0 -> already built ]
[(14/36) openh264 -> already built ]
[(15/36) opus -> already built ]
[(16/36) libsrtp -> already built ]
[(17/36) gst-plugins-bad-1.0 -> already built ]
[(18/36) libnice -> already built ]
[(19/36) gstreamer-1.0-static -> already built ]
[(20/36) gst-plugins-base-1.0-static -> already built ]
[(21/36) gst-plugins-good-1.0-static -> already built ]
[(22/36) gst-plugins-bad-1.0-static -> already built ]
[(23/36) libnice-static -> already built ]
[(24/36) gettext -> already built ]
[(25/36) intltool -> already built ]
[(26/36) gnome-js-common -> already built ]
[(27/36) icu -> already built ]
[(28/36) javascriptcoregtk -> already built ]
[(29/36) seed -> already built ]
[(30/36) libusrsctp -> already built ]
[(31/36) openwebrtc-gst-plugins -> already built ]
[(32/36) json-glib -> already built ]
[(33/36) libxml2 -> already built ]
[(34/36) libsoup -> already built ]
[(35/36) openwebrtc -> already built ]
[(36/36) openwebrtc-gst-plugins-static -> already built ]
WARNING: No specific packager available for the distro version ubuntu_trusty, using generic packager for distro debian
WARNING: No packager defined, using default packager "Default <default@change.me>"
-----> Creating package for openwebrtc
-----> Creating debian package structure at /home/szpi/cerbero/tmpyi0zPz/openwebrtc-0.1.0 for package openwebrtc
-----> Packing dependency base-system-1.0 for package openwebrtc
WARNING: No packager defined, using default packager "Default <default@change.me>"
-----> Creating debian package structure at /home/szpi/cerbero/tmpyi0zPz/base-system-1.0-1.5.0 for package base-system-1.0
-----> Creating package for base-system-1.0
Running command 'dpkg-buildpackage -rfakeroot -us -uc -D -b'
dpkg-buildpackage: pakiet źródłowy base-system-1.0
dpkg-buildpackage: wersja pakietu źródłowego 1.5.0-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: źródła zmienione przez Default <default@change.me>
dpkg-buildpackage: architektura gościa amd64
 dpkg-source --before-build base-system-1.0-1.5.0
 fakeroot debian/rules clean
dh_testdir
dh_testroot
rm -f build-stamp
dh_clean
 debian/rules build
dh_testdir
touch build-stamp
 fakeroot debian/rules binary
dh_testdir
dh_testroot
dh_prep
dh_installdirs
dh_installdocs
dh_install
dh_testdir -a
dh_testroot -a
dh_strip -a --dbg-package=base-system-1.0-dbg 
dh_link -a
dh_compress -a
dh_fixperms -a
dh_makeshlibs -a -V
dh_installdeb -a
dh_shlibdeps -a
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/libgirepository-1.0.so.1.0.0: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/libcrypto.so.1.0.0: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/libffi.so.6.0.4: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/liborc-0.4.so.0.23.0: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/libssl.so.1.0.0: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/libgobject-2.0.so.0.4200.2: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/libz.so.1.2.8: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/libgmodule-2.0.so.0.4200.2: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/liborc-test-0.4.so.0.23.0: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/libgthread-2.0.so.0.4200.2: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/libgio-2.0.so.0.4200.2: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/libbz2.so.1.0.6: Invalid operation
objdump: debian/base-system-1.0-dbg/usr/lib/debug/home/szpi/cerbero/dist/linux_x86_64/lib/libglib-2.0.so.0.4200.2: Invalid operation
dh_gencontrol -a
dh_md5sums -a
dh_builddeb -a
dpkg-deb: budowanie pakietu "base-system-1.0" w "../base-system-1.0_1.5.0-1_amd64.deb".
dpkg-deb: budowanie pakietu "base-system-1.0-dbg" w "../base-system-1.0-dbg_1.5.0-1_amd64.deb".
dpkg-deb: budowanie pakietu "base-system-1.0-dev" w "../base-system-1.0-dev_1.5.0-1_amd64.deb".
 dpkg-genchanges -b >../base-system-1.0_1.5.0-1_amd64.changes
dpkg-genchanges: wydanie tylko binarne - niedołączanie żadnych kodów źródłowych
 dpkg-source --after-build base-system-1.0-1.5.0
dpkg-buildpackage: wydanie tylko binarne (bez żadnych źródeł)
-----> Copying generated shlibs file /home/szpi/cerbero/tmpyi0zPz/base-system-1.0-1.5.0/debian/base-system-1.0/DEBIAN/shlibs to /home/szpi/cerbero/tmpyi0zPz/base-system-1.0-shlibs
Traceback (most recent call last):
  File "./cerbero-uninstalled", line 9, in <module>
    main()
  File "./cerbero/main.py", line 130, in main
    Main(sys.argv[1:])
  File "./cerbero/main.py", line 55, in __init__
    self.run_command()
  File "./cerbero/main.py", line 105, in run_command
    res = commands.run(command, self.config, self.args)
  File "./cerbero/commands/__init__.py", line 78, in run
    return _commands[command].run(config, args)
  File "./cerbero/commands/package.py", line 97, in run
    args.force, args.keep_temp)
  File "./cerbero/packages/linux.py", line 57, in pack
    self.pack_deps(output_dir, tmpdir, force)
  File "./cerbero/packages/linux.py", line 115, in pack_deps
    packager.pack(output_dir, self.devel, force, True, True, tmpdir)
  File "./cerbero/packages/linux.py", line 78, in pack
    paths = self.build(output_dir, tarname, tmpdir, packagedir, srcdir)
  File "./cerbero/packages/debian.py", line 308, in build
    shutil.move(os.path.join(tmpdir, f), output_dir)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/home/szpi/Pobrane/cerbero/base-system-1.0_1.5.0-1_amd64.deb'

Any suggestions how can I fix this?

**Comment by nirbheek** [comment]
What are the permissions on "/home/szpi/Pobrane/cerbero/"? See: 

ls -lhd /home/szpi/Pobrane/cerbero/

**Comment by simonpi** [comment]
I get the following:

drwxr-xr-x 10 root root 4,0K mar 25 15:31 /home/szpi/Pobrane/cerbero/

**Comment by nirbheek** [comment]
Right, so you must've used sudo while creating that directory. It should be owned by your user, not by root. You should not run any of the commands that we've listed as root.

`chown -R szpi /home/szpi/Pobrane/cerbero/` should fix your issue. This is unrelated to Cerbero.
