### ISSUE TITLE
dependencies build fails when run twice

### ISSUE THREAD

**Issue by bill-auger** [EricssonResearch/openwebrtc#28]
after running scripts/dependencies/build-all.sh a second time after a successful build (this was necessary when the main build failed because of a bug in the dependencies phase) - at the very end (after ~90 minutes on a P4) it fails with

    Creating file release for linux
    File release exists. Please remove old file release if you want to create a new one.
    ./build-all.sh -- Could not create file release.

obviously one must first delete ./openwebrtc-deps-x86_64-linux/ and ./openwebrtc-deps-x86_64-linux.tgz but perhaps the script could detect this upon invocation - or just clobber them anyways - creating this package is the only purpose of this script - is it not?

**Comment by superdump** [comment]
Moved to cerbero. Closing.

See here for more info: https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC
