### ISSUE TITLE
iOS glimagesink broken

### ISSUE THREAD

**Issue by ikonst** [EricssonResearch/openwebrtc#280]
On current builds, `videotestsrc ! videoconvert ! glimagesink` doesn't work on iOS (the CAEAGLLayer remains empty).

On @stefanalund 's [iOS framework built on 10:56 February 19, 2015](http://static.verkstad.net/OpenWebRTC.framework_old.zip), it still works.

On @stefanalund 's [iOS framework built on 11:10 March 13, 2015](http://static.verkstad.net/OpenWebRTC_framework_0.1.zip), it no longer works.

This means that between 10:56 February 19, 2015 and 11:10 March 13, 2015, a breaking change was introduced.

**Comment by sdroege** [comment]
I suspect something related to https://bugzilla.gnome.org/show_bug.cgi?id=746251 , and the big refactoring done as part of https://bugzilla.gnome.org/show_bug.cgi?id=743974 (pushed on the 12th, just before the new binaries).

**Comment by ikonst** [comment]
Culprit found:
https://bugzilla.gnome.org/show_bug.cgi?id=745090

**Comment by superdump** [comment]
@alessandrod - can I close this one too?

**Comment by superdump** [comment]
Closing. Thanks!
