### ISSUE TITLE
Windows 7 or 8.1 - installing openwebRTC for Enterprise kiosks

### ISSUE THREAD

**Issue by shamun** [EricssonResearch/openwebrtc#281]
How can i install openWebRTC for Enterprise Kiosks?
(in past i used CentOS, FreeBSD, but for legal terms and condition of some enterprises i cant use violated packages, they want me to use Windows 7 or 8.1)

But there is no documentation ever written or found : https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

Can anyone please share me the working concept of this in Windows OS's?

**Comment by stefanalund** [comment]
You want to track this Issue, things are starting to move:

https://github.com/EricssonResearch/openwebrtc/issues/2
