### ISSUE TITLE
Poor EAGL initialization flow causing GL failure on iOS.

### ISSUE THREAD

**Issue by ijsf** [EricssonResearch/openwebrtc#283]
This is actually a flow bug in gstreamer (bad plugins) causing issues on iOS 8.x.

A FIXME in `gst_gl_window_set_window_handle` is causing issues. Here, the `set_window_handle` function is being called asynchronously and is only actually called after the relevant thread is started. This happens after the GL context has been created, while GL context creation function `gst_gl_context_eagl_create_context` expects a valid window handle.

A workaround has been committed in my fork and seems to solve this specific case: https://github.com/ijsf/OpenWebRTC-gst-plugins-bad/commit/16bab0b506ea60d0049acd938136a7a158639782

**Comment by superdump** [comment]
Can you submit the patch to upstream GStreamer bugzilla? Probably even this ticket: https://bugzilla.gnome.org/show_bug.cgi?id=745090

**Comment by superdump** [comment]
Oh, it's basically reverting the change as @ikonst posted there. Never mind then. But thanks for more details on the problem. :)

**Comment by ijsf** [comment]
Yeah, it's more like a stopgap solution for iOS. I'm not sure why the FIXME was put there.

**Comment by ijsf** [comment]
Possibly a duplicate of https://github.com/EricssonResearch/openwebrtc/issues/280. Seems to be caused by the same issue, or rather, a fix of the bug below would likely fix this issue as well.

Also see: https://bugzilla.gnome.org/show_bug.cgi?id=745090

**Comment by alessandrod** [comment]
I'm working on this and have a working patch. I will polish it and push upstream.

**Comment by alessandrod** [comment]
commit 6981a8d15b17094cde8a2cec0a2c821c6eaa9547
Author: Alessandro Decina <alessandro.d@gmail.com>
Date:   Thu Apr 2 18:05:55 2015 +1100

    libgstgl: fix rendering on iOS
    
    Stop assuming that the handle has been set by the time ->create_context is
    called. After bc7a7259f357b0065dd94e0668b5a895d83fa53a set_window_handle always
    happens after ->create_context in fact.
    
    See also https://bugzilla.gnome.org/show_bug.cgi?id=745090

**Comment by superdump** [comment]
@alessandrod can I close this then?

**Comment by superdump** [comment]
Closing. Thanks!
