### ISSUE TITLE
Use built-in libiconv and zlib on iOS

### ISSUE THREAD

**Issue by ikonst** [EricssonResearch/openwebrtc#290]
libiconv and zlib come built-in on iOS.
Is there a reason to keep building libiconv and zlib recipes on iOS?
Do we have any particular version requirements?

**Comment by nirbheek** [comment]
zlib is a very stable library, so I doubt we have version requirements for it for any of our dependencies. But Cerbero builds its own versions of as much as possible to reduce cross-platform differences and bugs.

However, libiconv is actually used by gettext, so we need it at build-time, and it shouldn't make its way into the final binaries/libraries at all.

**Comment by sdroege** [comment]
iconv is also used by glib, and various other software.

**Comment by nirbheek** [comment]
Should we just close this? I don't think using the iOS versions of libz and libiconv is a good idea. Reusing libz won't really give us much benefit, and libiconv might have incompatibilities.

**Comment by superdump** [comment]
++ Closing.
