### ISSUE TITLE
Error while installing packages

### ISSUE THREAD

**Issue by simonpi** [EricssonResearch/openwebrtc#293]
Hello,

I have successfully built packages using cerbero but now I have one little problem when I want to install some of them. 
Using the command: sudo dpkg --install gstreamer-1.0-core-dev_1.5.0-1_amd64.deb

I get the following:

Preparing to unpack gstreamer-1.0-core-dev_1.5.0-1_amd64.deb ...
Unpacking gstreamer-1.0-core-dev (1.5.0-1) ...
dpkg: error processing archive gstreamer-1.0-core-dev_1.5.0-1_amd64.deb (--install):
 trying to overwrite '/home/user/cerbero/dist/linux_x86_64/include/gstreamer-1.0/gst/pbutils/encoding-target.h', which is also in package gstreamer-1.0-core 1.5.0-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 gstreamer-1.0-core-dev_1.5.0-1_amd64.deb

And also the similar error when typing: sudo dpkg --install openwebrtc-base-dev_0.1.0-1_amd64.deb

Preparing to unpack openwebrtc-base-dev_0.1.0-1_amd64.deb ...
Unpacking openwebrtc-base-dev (0.1.0-1) ...
dpkg: error processing archive openwebrtc-base-dev_0.1.0-1_amd64.deb (--install):
 trying to overwrite '/home/user/cerbero/dist/linux_x86_64/include/gstreamer-1.0/gst/sctp/sctpsendmeta.h', which is also in package openwebrtc-base 0.1.0-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 openwebrtc-base-dev_0.1.0-1_amd64.deb

Do I have to force overwrite it?

**Comment by superdump** [comment]
@sdroege @nirbheek ?

**Comment by simonpi** [comment]
Anybody?

**Comment by superdump** [comment]
It sounds like there are bugs in the Linux packaging where the same files exist in both the regular and -dev package. I would argue that the .h files should only be in the -dev variant. @sdroege @nirbheek?

**Comment by nirbheek** [comment]
@superdump Yes, the headers should only be in the -dev variant. I'll take a look at this.

**Comment by magoogli** [comment]
I also have encountered the same issue. Is there a way to get around this before the code is fixed?

**Comment by superdump** [comment]
@nirbheek any news?

**Comment by nirbheek** [comment]
commit f2783fdae0be7898c52de6f6f009ba835d3afaed is to blame; I'm fixing it right now.

**Comment by nirbheek** [comment]
Turned out to be a bug in Cerbero. The following patch fixes it upstream: http://cgit.freedesktop.org/gstreamer/sdk/cerbero/commit/?id=20049cfe63221c76524d8f9d8989769e04473ffe

**Comment by superdump** [comment]
I just landed that commit in our cerbero. Thanks! I'm going to close this but will reopen if the issue persists.
