### ISSUE TITLE
DataChannel

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/openwebrtc#3]
Add support for the WebRTC DataChannel. We are working on this and hope to have a solution soon.

**Comment by feross** [comment]
Any update on this?

**Comment by stefanalund** [comment]
Soon. We think it will be available during January actually. More about our roadmap here:

http://www.openwebrtc.io/blog/2015/1/15/roadmap-for-2015

**Comment by unanimous1** [comment]
Is there a new ETA for this?  Excited to see this feature.

**Comment by stefanalund** [comment]
Within a couple of days!

**Comment by superdump** [comment]
https://github.com/EricssonResearch/openwebrtc/pull/193

**Comment by superdump** [comment]
This has now landed. OpenWebRTC has Data Channel support!

**Comment by stefanalund** [comment]
Awesome! I will prepare a new version of Bowser as well.

**Comment by aamirkhan24** [comment]
Can you please provide datachannel example for iOS like this
https://github.com/EricssonResearch/openwebrtc-examples/tree/master/ios

**Comment by stefanalund** [comment]
@aamirkhan24 I created an Issue to keep track of this request: https://github.com/EricssonResearch/openwebrtc-examples/issues/58
