### ISSUE TITLE
Setup Freeswitch server

### ISSUE THREAD

**Issue by vdev2015** [EricssonResearch/openwebrtc#302]
Hello everyone,

I would like to setup my own Freeswitch server settings. How can I organize that staff ?

**Comment by stefanalund** [comment]
How does this question relate to OpenWebRTC? Do you want to use it as a client connecting to Freeswitch? Please explain a bit more what you want to achieve. Thanks.

**Comment by KerwinMa** [comment]
I think he meant to use freeswitch as a signaling server.
