### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by superdump** [EricssonResearch/openwebrtc#305]
This issue is not to create a bikeshed about versioning, but I wanted to discuss some of the points of the versioning integration stuff in OpenWebRTC to make sure we have all bases covered.

I plan to use [semantic versioning](http://semver.org) for OpenWebRTC releases. Given our internal iterations on the codebase, I think we will start at 0.3.0 (the current 0.1 is arbitrary.)

We need to identify all points in the codebase that need to be changed when a version is set. We also need to make sure all the results are correctly versioned. What is needed here?

**Comment by sdroege** [comment]
Also see https://github.com/EricssonResearch/openwebrtc/issues/106

**Comment by superdump** [comment]
cerbero:
```
config/osx-x86-64.cbc:prefix='/Library/Frameworks/OpenWebRTC.framework/Versions/0.1'

packages/openwebrtc-base.package:    version = '0.1.0'
packages/openwebrtc/openwebrtc.package:    version = '0.1.0'
packages/openwebrtc/openwebrtc.package:    sdk_version = '0.1'

recipes/openwebrtc-gst-plugins-static.recipe:    version = '0.0.1'
recipes/openwebrtc-gst-plugins.recipe:    version = '0.0.1'
recipes/openwebrtc-osx-framework.recipe:    version = '0.1'
recipes/openwebrtc-osx-framework.recipe:        libs = ['openwebrtc-0.1', 'openwebrtc-bridge-0.1', 'glib-2.0', 'gobject-2.0']
recipes/openwebrtc.recipe:    version = '0.1'
recipes/openwebrtc.recipe:    files_devel = ['lib/pkgconfig/openwebrtc-0.1.pc',
recipes/openwebrtc.recipe:                   'lib/pkgconfig/openwebrtc-bridge-0.1.pc',
recipes/openwebrtc.recipe:        Platform.DARWIN: ['Owr-0.1'],
recipes/openwebrtc.recipe:        Platform.LINUX: ['Owr-0.1'],
recipes/openwebrtc.recipe:        Platform.WINDOWS: ['Owr-0.1'],
recipes/openwebrtc.recipe:            gir_file = 'Owr-0.1.gir'
recipes/openwebrtc.recipe:            # Generate Owr-0.1.gir.h from the Owr-0.1.gir in the host build,
recipes/openwebrtc.recipe:            gir_h_file = os.path.join(self.build_dir, 'Owr-0.1.gir.h')
```

openwebrtc:
```
./bridge/openwebrtc-bridge-0.1.pc.in
./owr/openwebrtc-0.1.pc.in


bindings/java/Makefile.am:OWR_GIR = $(top_builddir)/owr/Owr-0.1.gir
bindings/java/Makefile.am:OWR_GIR = Owr-0.1.gir
bindings/java/Makefile.am:Owr-0.1.gir:
bindings/java/Makefile.am:      cat `find $(top_srcdir)/out -name Owr-0.1.gir || echo "Owr-0.1.gir"` | sed 's/shared-library="[^"]*"/shared-library="libopenwebrtc_jni.so"/' > Owr
bridge/Makefile.am:pkgconfig_DATA = openwebrtc-bridge-0.1.pc
bridge/Makefile.am:    openwebrtc-bridge-0.1.pc.in

bridge/openwebrtc-bridge-0.1.pc.in:Requires: openwebrtc-0.1 glib-2.0 gobject-2.0 gmodule-2.0 gthread-2.0 seed
bridge/owr_bridge.c:#include "Owr-0.1.gir.h"

configure.ac:AC_INIT(openwebrtc, 0.1)

configure.ac:bridge/openwebrtc-bridge-0.1.pc
configure.ac:owr/openwebrtc-0.1.pc

docs/reference/owr/Makefile.am:DOC_MODULE_VERSION=0.1 ???

owr/Makefile.am:    Owr-0.1.gir.h
owr/Makefile.am:pkgconfig_DATA = openwebrtc-0.1.pc
owr/Makefile.am:    openwebrtc-0.1.pc.in
owr/Makefile.am:Owr-0.1.gir: libopenwebrtc.la
owr/Makefile.am:INTROSPECTION_GIRS += Owr-0.1.gir
owr/Makefile.am:Owr-0.1.gir.h: Owr-0.1.gir
owr/Makefile.am:CLEANFILES += $(gir_DATA) $(typelib_DATA) Owr-0.1.gir.h
owr/Makefile.am:Owr-0.1.gir.h:
owr/Makefile.am:        cp -f `find $(top_srcdir) -name Owr-0.1.gir.h || echo "Owr-0.1.gir.h"` .
```

And this one I remember too:
```
owr/Makefile.am:libopenwebrtc_la_LDFLAGS = -export-dynamic -version-info 3601
```

**Comment by superdump** [comment]
Also these in openwebrtc:
```
bridge/owr_bridge.c:        Owr_0_1_gir_sha1,
bridge/owr_bridge.c:        Owr_0_1_gir,
bridge/owr_bridge.c:    gir_checksum_lengths[4] = Owr_0_1_gir_sha1_len,
bridge/owr_bridge.c:    gir_lengths[4] = Owr_0_1_gir_len,

owr/Makefile.am:Owr_0_1_gir_INCLUDES = GObject-2.0
owr/Makefile.am:Owr_0_1_gir_CFLAGS = \
owr/Makefile.am:Owr_0_1_gir_LIBS = libopenwebrtc.la
owr/Makefile.am:Owr_0_1_gir_FILES = \
```

The 3601 apparently came from the glib version we were using at the time in order for us to be able to get Python bindings to work.

**Comment by superdump** [comment]
For the OpenWebRTC part, I've made this pull request - https://github.com/EricssonResearch/openwebrtc/pull/307

I've tested it for the OS X build locally but it would be good to have a thorough review before it lands. I'm going to try to land all the 'infrastructure' changes first and then do a couple of commits that bump the version when we're ready to make an actual release.

**Comment by superdump** [comment]
And here's another one to help a little with updating cerbero recipes: https://github.com/EricssonResearch/cerbero/pull/5

**Comment by superdump** [comment]
Those two are now merged, so I think I'll try putting together some patches that show what we would do when we release and try to test those.

**Comment by superdump** [comment]
Please do not commit the following, or I'll be a bit irritated.

A 0.3.0 release would look like this, I think:
https://github.com/superdump/openwebrtc/commit/d29ad5c9023c4b9834d9e0476d71c7b5e14de16b
https://github.com/superdump/cerbero/commit/3ce9346f7fb89cac31998d8a7a6bc541f62e2a37

I need to retest all this. We will need to update the documentation to point out `/Library/Frameworks/OpenWebRTC.framework/Versions/0.3` where necessary.

@sdroege @nirbheek @ford-prefect @alessandrod @pererikb @Rugvip - you are all welcome to check this and if you wish, test it too.

**Comment by nirbheek** [comment]
It all looks good to me in general. I'll also note here that since the git commit id wasn't embedded in any installed files, openwebrtc.recipe creates $(prefix)/share/owr/version_id which has the commit hash.

**Comment by sdroege** [comment]
Makes sense to me, just see my comment in the owr commit

**Comment by superdump** [comment]
@nirbheek - I'm going to tag the relevant repos and use the tag in the recipes. Are you suggesting something specific that we should change? Some compiled in OWR version that is either the version number or a commit hash?

@sdroege - not for this release as we will make it clear that the API is likely to/will change soon and that full versioning will be done when things have stabilized.

**Comment by nirbheek** [comment]
I think a compiled-in commit hash (for nightly/git builds) and the release version (for release builds) that's displayed in the logs and with `--version` makes sense to make sense of bug reports, especially once we start shipping binaries.

**Comment by superdump** [comment]
The branches above were merged. What remains:
* Final bug fixes perhaps
* Tag openwebrtc-gst-plugins and openwebrtc
* Use the tags in cerbero

I think I'll leave the compiled-in commit hash or release version for next time around, when the API has stabilised and we start to get more serious about the release versioning.

**Comment by superdump** [comment]
Closing.
