### ISSUE TITLE
embedded linux support for OpenWebRTC

### ISSUE THREAD

**Issue by tsonghong** [EricssonResearch/openwebrtc#309]
Hello, I would like to get OpenWebRTC to run on an embedded linux device (Arm architecture) - namely a security camera.

The goal would be to have the security camera directly stream the live feed
to the web browser (firefox, chrome, IE, Safari, etc...) and not have to stream to some middle server.

Is there any document, tutorial or tips that I can get to help out on the porting to embedded linux?

Also, 
is there any requirements you can think of - for example in terms of cpu and memory
that the security camera needs to get OpenWebRTC itself running and able to stream a single live feed?
Or any other key requirement you think I would have to consider before consider OpenWebRTC as an option to achieve my goal?

Thanks!

Henry

**Comment by superdump** [comment]
You will likely need good integration with the embedded platform hardware as doing software processing and making unnecessary memory copies will kill performance on the lower-powered embedded CPUs. So you need to choose your platform wisely and then you will want to have existing /  GStreamer elements that access and use the hardware capture and codecs, for example.

There is a simple build configuration in our cerbero build system to allow cross-compiling for armv7 Linux. That is probably a good starting point. In general I would advise that you make sure that the GStreamer elements you need for your use case work well on the platform before starting to look at OpenWebRTC.

**Comment by tsonghong** [comment]
thanks
