### ISSUE TITLE
openwebrtc build error [iOS-arm64, Xcode 6.2]

### ISSUE THREAD

**Issue by mirekestafet** [EricssonResearch/openwebrtc#331]
Unable to build using Cerbero (rev. 3e46969)

$ ./cerbero-uninstalled -c config/osx-x86-64.cbc package -f openwebrtc
OK

$ ./cerbero-uninstalled -c config/cross-ios-arm64.cbc package -f openwebrtc
...
[(33/33) openwebrtc -> compile ]
...
clang: error: argument unused during compilation: '-pthread'
make[3]: *** [openwebrtc-daemon] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by superdump** [comment]
I'm fixing that one at the moment. It's because we added graphene to the build.

**Comment by mirekestafet** [comment]
Great, appreciate such prompt feedback. Whenever you are ready, please let me know.

**Comment by jwvdiermen** [comment]
Glad it's being picked up, just bumped into the same issue. Will watch this thread to see when it's resolved.

**Comment by superdump** [comment]
Follow the wiki instructions on the build page to update your cerbero repo, re-fetch and re-package and it should be fixed. Report back that it is broken in this ticket and I'll reopen it.

**Comment by mirekestafet** [comment]
Got the same error at the end, please help. 

I pulled and re-fetched:
$ cd ~/cerbero
$ git pull --rebase
$ ./cerbero-uninstalled fetch-package --full-reset --reset-rdeps openwebrtc
OK

Then built for Darwin:
$ ./cerbero-uninstalled -c config/osx-x86-64.cbc package -f openwebrtc
OK

Then built for iOS-arm64:
$ ./cerbero-uninstalled -c config/cross-ios-arm64.cbc package -f openwebrtc
...
[(32/32) openwebrtc -> fetch ]
-----> Step done
[(32/32) openwebrtc -> extract ]
-----> Step done
[(32/32) openwebrtc -> configure ]
-----> Step done
[(32/32) openwebrtc -> compile ]
...
clang: error: argument unused during compilation: '-pthread'
make[3]: *** [openwebrtc-daemon] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by jwvdiermen** [comment]
Same issue here, same error.

**Comment by superdump** [comment]
OK. So, for some reason this worked for me locally without problem, but it broke on our automated build systems. The following steps should fix it:
```
cd /path/to/cerbero
./cerbero-uninstalled -c config/osx-x86-64.cbc cleanone graphene
./cerbero-uninstalled -c config/cross-ios-universal.cbc cleanone graphene
find dist -type f -name "*graphene*" -delete
find dist -type d -name "*graphene*" -exec rm -r {} \;
./cerbero-uninstalled -c config/osx-x86-64.cbc buildone gst-plugins-bad-1.0
./cerbero-uninstalled -c config/osx-x86-64.cbc buildone openwebrtc
./cerbero-uninstalled -c config/osx-x86-64.cbc package openwebrtc
./cerbero-uninstalled -c config/cross-ios-universal.cbc buildone gst-plugins-bad-1.0
./cerbero-uninstalled -c config/cross-ios-universal.cbc buildone gst-plugins-bad-1.0-static
./cerbero-uninstalled -c config/cross-ios-universal.cbc buildone openwebrtc
./cerbero-uninstalled -c config/cross-ios-universal.cbc package openwebrtc
```

Hopefully that's enough.

**Comment by mirekestafet** [comment]
Success, worked also for '-c config/cross-ios-arm64.cbc'

Thank you!
