### ISSUE TITLE
Caps renegotiations in the send elements will sometimes cause the ssrc to change

### ISSUE THREAD

**Issue by Rugvip** [EricssonResearch/openwebrtc#334]
see #333

**Comment by sdroege** [comment]
Are you recreating the payloader, or changing it back to READY state? That's when it will decide to use a new ssrc.

**Comment by Rugvip** [comment]
There are no state changes happening at all, assuming GST_STATE:5 would show them.
I can't find any difference in the logs between the working and not working scenarios when looking through gstbasepayload, it seems to be happening inside RtpBin.

**Comment by sdroege** [comment]
Is there something about ssrc collisions in the logs? rtpsession has some code to change ssrcs

**Comment by Rugvip** [comment]
The first time the incorrect ssrc is mentioned in the logs with *rtp*:9 is in `0:00:12.817566000 60963 0x7fe51c07e8f0 DEBUG             rtprtxsend gstrtprtxsend.c:395:gst_rtp_rtx_buffer_new:<rtprtxsend0> retransmit seqnum: 7370, ssrc: 4128394237`

**Comment by Rugvip** [comment]
Nope, nothing about ssrc collisions

**Comment by Rugvip** [comment]
I'm seeing this though... `gstrtprtxreceive.c:543:gst_rtp_rtx_receive_chain:<rtprtxreceive0> associate retransmisted stream 4128394237 to master stream 2788228357 thanks to packet 15001`
So that seems fine, still ends up in a new pad though.

I'm trying to upload a log btw, but it was a bit too large to put in a gist :p

**Comment by Rugvip** [comment]
There we go: https://gist.github.com/Rugvip/3e65bb3931cef90c121b I cut out some boring parts, it's video only btw, \*pay\*:9,GST_STATES:5,\*rtp\*:9

The bonus ssrc is 4128394237 / f6124bfd

**Comment by Rugvip** [comment]
Right, so in `rtp_session_send_rtp` `obtain_internal_source` is called, and if that doesn't find a source it creates a new internal source, which then sets `sess->suggested_ssrc` inside `add_source`. `rtp_session_suggest_ssrc` is used inside `gst_rtp_session_getcaps_send_rtp` which replies to the caps query on the rtp send pad, which then causes the caps to change.

So what's the solution? :grinning:

**Comment by sdroege** [comment]
Why doesn't it find a source already and creates a new one instead?

**Comment by sdroege** [comment]
Ok, so the ssrc/pt/stuff negotiation in rtpbasepayload is a bit suboptimal.

It should
a) prefer values set on the properties over downstream values if downstream also supports the property values
b) prefer currently set values (element is already running) over anything that downstream wants as long as downstream still supports the currently set values

while at the same time considering SSRC collision to switch to a different SSRC if needed.


b) is your case btw, but it's all closely related in the rtpbasepayload code so I'm just going to fix it together.

**Comment by sdroege** [comment]
This should be fixed by http://cgit.freedesktop.org/gstreamer/gst-plugins-base/commit/?id=faafaaec56de31ebecf02b87e1fc0e4c07ed9ecc

**Comment by superdump** [comment]
Pushed updates to our cerbero fork. Will test.

**Comment by sdroege** [comment]
Supposed to be fixed now
