### ISSUE TITLE
Mac OS X 10.10 build fail

### ISSUE THREAD

**Issue by qingfeng** [EricssonResearch/openwebrtc#335]
```
libtool: link: ( cd ".libs" && rm -f "libgstopengl.la" && ln -s "../libgstopengl.la" "libgstopengl.la" )
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Running command 'make -j8'
```

**Comment by nirbheek** [comment]
Please attach the compile log for the recipe that failed. In this case, it's in ~/cerbero/logs/*/gst-plugins-bad-1.0-compile.log.

In the future, please attach the entire console output from when you entered the cerbero command till the end. :)

**Comment by superdump** [comment]
By attach, @nirbheek means paste it into https://gist.github.com/ and link it here.

**Comment by qingfeng** [comment]
OK, thanks~ 

https://gist.github.com/qingfeng/20184493a4b8a086bfc6

**Comment by superdump** [comment]
```
gstopenh264enc.cpp:685:14: error: no member named 'bEnableSpsPpsIdAddition' in 'TagEncParamExt'
  enc_params.bEnableSpsPpsIdAddition = 1;
  ~~~~~~~~~~ ^
1 error generated.
make[3]: *** [libgstopenh264_la-gstopenh264enc.lo] Error 1
```

Odd, OpenH264 should have been updated at the same time as gst-plugins-bad. I think there was an API change there but that was fixed in cerbero.
