### ISSUE TITLE
x86_64/glibconfig.h file not found

### ISSUE THREAD

**Issue by qingfeng** [EricssonResearch/openwebrtc#341]
build openwebrtc success, but....

![screen shot 2015-04-20 at 4 33 58](https://cloud.githubusercontent.com/assets/18495/7221270/8a073cd0-e716-11e4-8a7b-098853284880.png)

**Comment by superdump** [comment]
Did you follow all the steps in https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC#using-the-results ?

**Comment by mirekingr** [comment]
@qingfeng: Try to build & run your app on a real device could help because iOS Simulator requires x86_64 libs present.
