### ISSUE TITLE
Question: ICE on OpenWebRTC & libjingle (GTalk)

### ISSUE THREAD

**Issue by mirekingr** [EricssonResearch/openwebrtc#344]
Just wanted to ask about libnice and how it behaves with libjingle (GTalk) clients?

The libnice has a useful configuration parameter called STUN_USAGE_ICE_COMPATIBILITY_GOOGLE which helped to pass through STUN binding stage, the data is there but no 'on-incoming-source' signal has been emitted from the iOS-SDK.

Any hints, experience with this? Thanks for help, guys.

**Comment by stefanalund** [comment]
@superdump or @Rugvip?

**Comment by mirekingr** [comment]
Okay, GTalk ICE fixed by disabling randomly generated candidates.

After some debugging it seems that GStreamer is processing audio but dropping video data - this could be my bad..

**Comment by superdump** [comment]
In general we try to be standards compliant. The compatibility flag for Google has not been needed so far, as I recall.

I've been testing a bit just now with the openwebrtc-daemon and test-client on OS X and having some trouble with Chrome (42.0.2311.90 (64-bit)) specifically. Firefox is working fine.

Are you using NativeDemo on iOS to test?

**Comment by mirekingr** [comment]
Sure thing, the NativeDemo app is very useful for testing. Closing the question as resolved and will propose minor tweaks regarding GTalk ICE to folks from libnice.
