### ISSUE TITLE
openwebrtc build failing for cross-ios-universal

### ISSUE THREAD

**Issue by iivalchev** [EricssonResearch/openwebrtc#356]
I get the new error running:

./cerbero-uninstalled -c config/osx-x86-64.cbc buildone openwebrtc && \
./cerbero-uninstalled -c config/osx-x86-64.cbc package openwebrtc && \
./cerbero-uninstalled -c config/cross-ios-universal.cbc buildone openwebrtc && \
./cerbero-uninstalled -c config/cross-ios-universal.cbc package openwebrtc

Building the following recipes: openwebrtc
[(1/1) openwebrtc -> fetch ]
[(1/1) openwebrtc -> extract ]
[(1/1) openwebrtc -> configure ]
-----> copying /Users/dilyanatodorova/cerbero/data/autotools/config.guess to /Users/dilyanatodorova/cerbero/sources/ios_universal/armv7s/openwebrtc-0.1/config.guess
-----> copying /Users/dilyanatodorova/cerbero/data/autotools/config.sub to /Users/dilyanatodorova/cerbero/sources/ios_universal/armv7s/openwebrtc-0.1/config.sub
-----> copying /Users/dilyanatodorova/cerbero/data/autotools/config.guess to /Users/dilyanatodorova/cerbero/sources/ios_universal/x86/openwebrtc-0.1/config.guess
-----> copying /Users/dilyanatodorova/cerbero/data/autotools/config.sub to /Users/dilyanatodorova/cerbero/sources/ios_universal/x86/openwebrtc-0.1/config.sub
-----> copying /Users/dilyanatodorova/cerbero/data/autotools/config.guess to /Users/dilyanatodorova/cerbero/sources/ios_universal/armv7/openwebrtc-0.1/config.guess
-----> copying /Users/dilyanatodorova/cerbero/data/autotools/config.sub to /Users/dilyanatodorova/cerbero/sources/ios_universal/armv7/openwebrtc-0.1/config.sub
-----> copying /Users/dilyanatodorova/cerbero/data/autotools/config.guess to /Users/dilyanatodorova/cerbero/sources/ios_universal/arm64/openwebrtc-0.1/config.guess
-----> copying /Users/dilyanatodorova/cerbero/data/autotools/config.sub to /Users/dilyanatodorova/cerbero/sources/ios_universal/arm64/openwebrtc-0.1/config.sub
[(1/1) openwebrtc -> compile ]
make[2]: `.gitignore' is up to date.
make[2]: `.gitignore' is up to date.
make[2]: `.gitignore' is up to date.
make[2]: `.gitignore' is up to date.
make[3]: `.gitignore' is up to date.
make[3]: `.gitignore' is up to date.
make[3]: `.gitignore' is up to date.
make[3]: `.gitignore' is up to date.
make[2]: `.gitignore' is up to date.
make[2]: `.gitignore' is up to date.
make[3]: `.gitignore' is up to date.
make[4]: `.gitignore' is up to date.
make[2]: `.gitignore' is up to date.
make[2]: `.gitignore' is up to date.
make[3]: `.gitignore' is up to date.
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in transport
Making all in local
Making all in owr
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
cp -f `find .. -name Owr-0.3.gir.h || echo "Owr-0.3.gir.h"` .
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
make[3]: *** [Owr-0.3.gir.h] Error 64
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Running command 'make'

Recipe 'openwebrtc' failed at the build step 'compile'
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort

**Comment by superdump** [comment]
We're in the process of making a release today. Expect breakages.
