### ISSUE TITLE
Building in ios 

### ISSUE THREAD

**Issue by imadgit** [EricssonResearch/openwebrtc#357]
hi,
i try to build OpenWebrtc in my Machine but when i launch pod install he gives me an error
xcode-select error unknown command option '-p' , i have Mac OS 10.8.2 Mountain Lion with xcode 4.6.3
really i don't know what the problem can you help me please.

**Comment by superdump** [comment]
I don't think we support anything that old. Please update to OS X 10.10 and Xcode 6.3 if you can.

**Comment by imadgit** [comment]
and if i'll  Build OpenWebRTC withe Alternative 2( Manual installation )
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC
can work with  OS 10.8.2 Mountain Lion and xcode 4.6.3 ??

**Comment by imadgit** [comment]
and if i'll Build OpenWebRTC withe Alternative 2( Manual installation )
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC
can work with OS 10.8.2 Mountain Lion and xcode 4.6.3 ??

2015-04-24 16:13 GMT+00:00 Robert Swain <notifications@github.com>:
