### ISSUE TITLE
iOS, very poor video performance with openwebrtc.framework 0.3.0

### ISSUE THREAD

**Issue by cellcma** [EricssonResearch/openwebrtc#362]
The first of all thanks for your great work. I have tested openwebrtc.framework 0.3.0 with SimpleDemo app and i have video delays about 10 seconds or more. I have tested the same demo with Bowser browser installed from App Store and it runs much better. Is there any difference between them?

My tests:

Test 1 iPhone 6 Plus and iPhone 5C:
Description: SimpleDemo app with openwebrtc.framework 0.3.0 installed with cocoapods.
Result: Very poor video performance (send and receive).

Test 2 iPhone 6 Plus and iPhone 5C
Description: SimpleDemo app with openwebrtc.framework 0.3.0 compiled and generated (following wiki steps) by me.
Result:  like test1. In this case i am not able to run SimpleDemo in iPhone 5C beacuse it gives an error in  ffi.c calling method  fun(cif, rvalue, avalue, user_data);

Test 3 iPhone 6 Plus and iPhone 5C:
Description: Test with Bowser browser -> http://demo.openwebrtc.io:38080/
Result: Bowser browser runs ok.

Thanks in advance.

**Comment by superdump** [comment]
Have you tried NativeDemo? Bowser from the App Store is quite old and we're going to update it soon.

I've been noticing performance regressions too and will be looking into this as my current priority. I want to make the pipeline always responsive but if it can't keep up with real time, the frame rate will reduce. However, latency should not be impacted more tha the time it is taking to process one frame. We know of a bunch of optimisations that we can do and they are in progress but help is very welcome.

See #240 for example. Plus @ikonst and @alessandrod have been working on avoiding expensive memory copies.

**Comment by cellcma** [comment]
Hi Robert

Thanks for your fast answer. NativeDemo works great with iPhone 6 and iPhone 5C. Do you think that is possible connect with several webrtc session at the same time with OpenWebRTC?

One webrtc session sending your video and several session receiving remote video.

Thanks in advance.

**Comment by superdump** [comment]
It's certainly possible according to the API. The limitations will be according to the capabilities of the device and how far along we are in the optimisation process. Once #240 is closed and memory copies are removed, we should be able to support as many as the CPU and hardware codecs can handle. We can fall back to software codecs if the hardware codecs are busy.

**Comment by stefanalund** [comment]
Is this still the case? Many performance improvements have been made since May. Re-open if you still have problems.
