### ISSUE TITLE
.cerbero/cerbero.cbc is missing

### ISSUE THREAD

**Issue by wadeLeeWei** [EricssonResearch/openwebrtc#363]
Processing triggers for menu ...
WARNING: Using default configuration because /home/wade/.cerbero/cerbero.cbc is missing
WARNING: Could not recover status
WARNING: Error loading recipe in file /home/wade/cerbero/recipes/gst-plugins-bad-1.0.recipe list.remove(x): x not in list

where  is  cerbero.cbc   ??

**Comment by superdump** [comment]
That part out the output does not matter you can ignore it. It can optionally be at `~/cerbero/cerbero.cbc` but you don't need it.

If you have a problem building, you can either use something prevail from our release or you will need to paste the actual problem which is usually in the last 50 lines of output.

**Comment by superdump** [comment]
https://github.com/EricssonResearch/openwebrtc/releases

**Comment by wadeLeeWei** [comment]
hi superdump 
Thanks  a lot !

**Comment by wadeLeeWei** [comment]
run command "./cerbero-uninstalled -c config/linux.cbc package -f openwebrtc",  output  errors:


****************************************************************************
WARNING: Using default configuration because /home/wade/.cerbero/cerbero.cbc is missing
WARNING: Could not recover status
WARNING: Error loading recipe in file /home/wade/cerbero/recipes/gst-plugins-bad-1.0.recipe list.remove(x): x not in list
***** Error running 'package' command:
Recipe 'gst-plugins-bad-1.0' not found

*******************************************************************

how to resolve this  problem?

**Comment by superdump** [comment]
We'll continue in the real issue in #364
