### ISSUE TITLE
 'gst-plugins-bad-1.0' not found

### ISSUE THREAD

**Issue by wadeLeeWei** [EricssonResearch/openwebrtc#364]
run command "./cerbero-uninstalled -c config/linux.cbc package -f openwebrtc", output errors:

*****************************************************************
WARNING: Using default configuration because /home/wade/.cerbero/cerbero.cbc is missing
WARNING: Could not recover status
WARNING: Error loading recipe in file /home/wade/cerbero/recipes/gst-plugins-bad-1.0.recipe list.remove(x): x not in list
***** Error running 'package' command:
Recipe 'gst-plugins-bad-1.0' not found

******************************************************************************

how to resolve this problem?

**Comment by superdump** [comment]
From where you run the cerbero-uninstalled command:

```
pwd
ls ~/cerbero/recipes
```

**Comment by Rugvip** [comment]
I can't test it since I don't have a debian installation atm, but EricssonResearch/cerbero#24 should hopefully fix the issue.

**Comment by wadeLeeWei** [comment]
which OS  are you    running ?

**Comment by wadeLeeWei** [comment]
hi  superdump;



wade@openWebrtc:~$ pwd
/home/wade
wade@openWebrtc:~$ ls ~/cerbero/recipes  |  grep   bad
gst-plugins-bad-1.0.recipe
gst-plugins-bad-1.0-static.recipe

**Comment by wadeLeeWei** [comment]
hi Rugvip,

I test  it on debian7.8.
EricssonResearch/cerbero#24  fix the issue.

Thanks a lot.

**Comment by Rugvip** [comment]
Oops, I didn't mean to close this issue when merging it, sorry bout that.
Glad to hear it worked though :)

**Comment by wadeLeeWei** [comment]
hi Rugvip,

which operating system are you running ?

**Comment by superdump** [comment]
We mostly use Mac OS X but some use Ubuntu 14.04. We test building and running on Ubuntu as well as other target platforms.
