### ISSUE TITLE
Build fails with IOError: [Errno 2] No such file or directory: ... openwebrtc-0.3/lib/gstreamer-1.0/libgstpulse.a

### ISSUE THREAD

**Issue by vasuballa** [EricssonResearch/openwebrtc#368]
Hi All,

I am trying to build the openwebrtc from the source following the instructions in https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

I tried both on CentOS 6.4 and Ubuntu 14 & 12.04, in all cases it failing with error 

IOError: [Errno 2] No such file or directory: '/home/webrtc/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstpulse.a'

during the step 

[(20/35) gst-plugins-good-1.0-static -> post_install ]

Here is the full output. Can some one help me build openwebrtc

$ ./cerbero-uninstalled -c config/linux.cbc package -f openwebrtc
WARNING: Using default configuration because /home/webrtc/.cerbero/cerbero.cbc is missing
Building the following recipes: libffi zlib glib orc bzip2 openssl gobject-introspection gtk-doc-lite gstreamer-1.0 gst-plugins-base-1.0 libvpx gst-plugins-good-1.0 openh264 opus libsrtp gst-plugins-bad-1.0 libnice gstreamer-1.0-static gst-plugins-base-1.0-static gst-plugins-good-1.0-static gst-plugins-bad-1.0-static libnice-static gettext intltool gnome-js-common icu javascriptcoregtk seed libusrsctp openwebrtc-gst-plugins json-glib libxml2 libsoup openwebrtc openwebrtc-gst-plugins-static
[(1/35) libffi -> already built ]
[(2/35) zlib -> already built ]
[(3/35) glib -> already built ]
[(4/35) orc -> already built ]
[(5/35) bzip2 -> already built ]
[(6/35) openssl -> already built ]
[(7/35) gobject-introspection -> already built ]
[(8/35) gtk-doc-lite -> already built ]
[(9/35) gstreamer-1.0 -> already built ]
[(10/35) gst-plugins-base-1.0 -> already built ]
[(11/35) libvpx -> already built ]
[(12/35) gst-plugins-good-1.0 -> already built ]
[(13/35) openh264 -> already built ]
[(14/35) opus -> already built ]
[(15/35) libsrtp -> already built ]
[(16/35) gst-plugins-bad-1.0 -> already built ]
[(17/35) libnice -> already built ]
[(18/35) gstreamer-1.0-static -> already built ]
[(19/35) gst-plugins-base-1.0-static -> already built ]
[(20/35) gst-plugins-good-1.0-static -> fetch ]
-----> Step done
[(20/35) gst-plugins-good-1.0-static -> extract ]
-----> Step done
[(20/35) gst-plugins-good-1.0-static -> configure ]
-----> Step done
[(20/35) gst-plugins-good-1.0-static -> compile ]
-----> Step done
[(20/35) gst-plugins-good-1.0-static -> install ]
-----> Step done
[(20/35) gst-plugins-good-1.0-static -> post_install ]
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/webrtc/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideo4linux2.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/webrtc/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstalaw.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/webrtc/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstmulaw.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/webrtc/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvpx.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/webrtc/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideofilter.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/webrtc/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstvideocrop.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/webrtc/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstrtp.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/webrtc/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstrtpmanager.la'
Running command 'sed -i "s#^libdir='\(.*\)'#libdir='\1/static'#" /home/webrtc/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstudp.la'

Recipe 'gst-plugins-good-1.0-static' failed at the build step 'post_install'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "/home/webrtc/cerbero/recipes/custom.py", line 93, in post_install
    shutil.copyfile(src, dest)
  File "/usr/lib64/python2.6/shutil.py", line 50, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/webrtc/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/static-build/opt/openwebrtc-0.3/lib/gstreamer-1.0/libgstpulse.a'
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort

**Comment by superdump** [comment]
Had you run the bootstrap command? That should install the pulse libraries which should then be identified by the gst-plugins-good configure stage which should then build that plugin. What does `~/cerbero/logs/linux_x86_64/gst-plugins-good-1.0-static-configure.log` say? It should say:

```
configure: *** checking feature: pulseaudio plug-in ***
configure: *** for plug-ins: pulseaudio ***
configure: *** These plugins will be built: pulseaudio
```

If not then we need `~/cerbero/sources/linux_x86_64/gst-plugins-good-1.0-static-1.5/config.log` to try to identify why.

**Comment by vasuballa** [comment]
I did run the bootstrap. it completed without any errors

here is the snippet related to pulseaudio from ~/cerbero/logs/linux_x86_64/gst-plugins-good-1.0-static-configure.log


configure: *** checking feature: pulseaudio plug-in ***
configure: *** for plug-ins: pulseaudio ***
checking process.h usability... no
checking process.h presence... no
checking for process.h... no
checking for PULSE... no
configure: Requested 'libpulse >= 2.0' but version of libpulse is 0.9.21
configure: *** These plugins will not be built: pulseaudio


$ rpm -qa|grep pulse
pulseaudio-libs-glib2-0.9.21-17.el6.x86_64
pulseaudio-libs-0.9.21-17.el6.x86_64
pulseaudio-libs-zeroconf-0.9.21-17.el6.x86_64
pulseaudio-libs-devel-0.9.21-17.el6.x86_64

Can you let me know the version of pulse lib required ? i will try to get that installed or compiled.

**Comment by superdump** [comment]
It looks like the gst-plugins-good that we use requires much newer pulseaudio than is available on CentOS. I'm not really surprised as in my experience CentOS has mostly ancient packages.

We are currently building OpenWebRTC on Ubuntu 14.04 LTS and that works just fine. There should be new enough packages there.

**Comment by vasuballa** [comment]
Thanks a lot! The Build completed successfully on  Ubuntu 14.04 LTS
