### ISSUE TITLE
Bowser app doesnt do anything on iPad 3rd gen (iOS 8.1)

### ISSUE THREAD

**Issue by peterwilli** [EricssonResearch/openwebrtc#370]
Hi,

I'm looking for WebRTC functionality for iOS which brought me here. I assumed Bowser was some kind of WebRTC api polyfill for iOS but it doesnt seem to work for me.
I tried reinstalling many times as well.

What happens is it gets stuck at Initializing for a good 20 seconds or so. After that I go to the OpenWebRTC website to click on demo button on the top.

Here is a screenshot: http://imgur.com/sB3Y0XC

At that point I get no ID or anything. It just sits there and doesnt give any error. Other WebRTC demo's aren't working as well.

I was kind of relieved to find this project after being surprised that iOS doesnt support WebRTC. If anyone knows how to make it work that would be awesome! Thanks.

**Comment by superdump** [comment]
Are you using Bowser from the App Store or built yourself?

**Comment by peterwilli** [comment]
@superdump Wow that was fast! I downloaded from the App Store. (If that worked I wanted to build myself)

**Comment by superdump** [comment]
Push notifications allow me fast reaction times. :smile: I'll give it a go here on my phone and see if I see the same. What device are you using it on?

**Comment by peterwilli** [comment]
iPad 3rd Gen (MD328NF/A) with iOS 8.1 Thanks for helping!

**Comment by superdump** [comment]
So, I downloaded and installed the app from scratch. It takes a while to generate some language bindings on the first boot (we have an issue somewhere about improving that situation) and then it exhibits the same behaviour as in your screenshot above.

If I then double-click the home button and swipe out Bowser to make it close fully, then restart the app and open the demo page, the join button is active. I can set up an audio/video call too.

That was on an iPhone 6 Plus. Performance when using VP8 is not good because it's a software codec. If you make a call initiating from Bowser to Firefox, H.264 gets used which should give better performance as we use the hardware codec in Apple A7 and newer chips. Unfortunately your iPad 3 has an A5X chip so does not benefit from that and will instead use the OpenH264 software H264 codec implementation.

We will be working on some device profiles soon to select appropriate settings to provide as good an experience as we can given the hardware.

**Comment by peterwilli** [comment]
@superdump  thanks I'll try the swipe stuff - luckily I only need DataChannels to work.

I'm trying to get my side project (http://sketchb.us/) to use WebRTC to avoid programming p2p communication manually because I have more users than my server can handle lately ;)

**Comment by superdump** [comment]
I had audio/video working with Bowser from the App Store.

We need to send up an update to Bowser on the App Store as it's getting a bit old now. It indeed doesn't have data channel support. I'll try to build it with the recent release.

**Comment by superdump** [comment]
@peterwilli instead of building everything, you may want to try: https://github.com/EricssonResearch/bowser/pull/43

**Comment by peterwilli** [comment]
@superdump  oh nice is that going to be merged soon? Otherwise I can fork and merge it myself

**Comment by superdump** [comment]
I expect it will be merged fairly soon, yes.

**Comment by stefanalund** [comment]
Merged now.

**Comment by stefanalund** [comment]
Oh, and I also submitted Bowser 0.5 for App Store review.

**Comment by peterwilli** [comment]
Thanks @stefanalund  I'll check out bowser in the weekend or so!

**Comment by peterwilli** [comment]
@superdump  unfortunately even after the fresh Bowser build I can't seem to be able to make any connection :( 

The logs:

    CoreFoundation = 1141.140000
    2015-05-13 00:37:37.321 Bowser[1470:92904] BowserViewController viewDidLoad
    2015-05-13 00:37:38.650 Bowser[1470:92980] OWR bridge starting...
    ** Message: Loaded namespace: GLib
    ** Message: Loaded namespace: GObject
    ** Message: Loaded namespace: Gio
    ** Message: Loaded namespace: GIRepository
    ** Message: Loaded namespace: Owr
    ** Message: ready
    2015-05-13 00:37:39.593 Bowser[1470:92980] OWR bridge started
    2015-05-13 00:37:40.085 Bowser[1470:92904] webViewDidStartLoading...
    2015-05-13 00:37:40.086 Bowser[1470:92904] creating timer
    2015-05-13 00:34:10.660 Bowser[1433:91194] injecting bootstrap script
    2015-05-13 00:34:10.682 Bowser[1433:91194] injecting bootstrap script
    2015-05-13 00:34:10.713 Bowser[1433:91194] injecting bootstrap script
    2015-05-13 00:34:10.735 Bowser[1433:91194] injecting bootstrap script
    (.. Goes on many times while loading page)
    2015-05-13 00:34:10.754 Bowser[1433:91194] webViewDidFinishLoading... http://demo.openwebrtc.io:38080/
    2015-05-13 00:34:16.501 Bowser[1433:91194] writing files!



Writing files is called when app is shut down.

**Comment by superdump** [comment]
So did you try doing as I said above? Double-press the home button and swipe out Bowser to make sure it is fully closed and then start it up again? (That is a bug that needs to be addressed, but this workaround seems to work for me.)

**Comment by peterwilli** [comment]
@superdump  yeah I have. I'll record it so you can see for yourself what happens. Give me a moment

**Comment by superdump** [comment]
@stefanalund - looks like something's still not 100% reliable with the injection.

**Comment by stefanalund** [comment]
Yeah, we need to move to WKWebView as soon as possible, it has proper support for injecting scripts before each page load. The current solution seems to be too hacky and unreliable.

**Comment by peterwilli** [comment]
@stefanalund WKWebView seems to be used in other examples besides Bowser. Maybe I can try one of those see if that works.

**Comment by stefanalund** [comment]
Yes, please do! Thanks.

**Comment by jellnet** [comment]
I'm also experiencing the same problem, but your workaround does not work for me.  It there a place I can download a newer version than the app store?

**Comment by superdump** [comment]
We will need to retest on an iPad 3 after some recent fixes and changes. It may be working again now.

**Comment by stefanalund** [comment]
This has been fixed in version 0.6 (currently in App Store review): https://github.com/EricssonResearch/bowser/releases/tag/0.6
