### ISSUE TITLE
Pre-buffering of audio/video channels

### ISSUE THREAD

**Issue by mirekestafet** [EricssonResearch/openwebrtc#374]
Hi guys, this is rather a question not an issue.

Just made the AV live streaming working with a custom app, really great framework this is. Speaking for higher video framerates, a typical media player uses pre-buffering [100 ms ~ 1 sec].

Has anybody touched a relevant bit of GStreamer to enable this feature?

Thanks for any help.

**Comment by superdump** [comment]
What exactly are you trying to do? If you set a larger jitter buffer size on the receiving side media session then that will cause more buffering in the receiver as long as the video frames arrive in good time.

**Comment by mirekestafet** [comment]
Reason: occasional flicker in 30 fps video so I am wondering what could be the cause.

Would be PROP_JITTER_BUFFER_LATENCY any useful to increase the jitter buffer size?

**Comment by superdump** [comment]
I suspect the issue is something else, possibly related to performance or or packet losses.

That was the property to which I was referring, yes.

**Comment by mirekestafet** [comment]
Allowing 1000 ms to the jitter buffer reduced flickering significantly on poor networks. Also the changes in packet re-transmitting (commit a0a4adc09fed11ea7dd391ce5f1c15893c806cc4) improved the channel quality in my opinion.
