### ISSUE TITLE
can we integrate openwebrtc with phonegap ?

### ISSUE THREAD

**Issue by imadgit** [EricssonResearch/openwebrtc#380]
hi everyone.
can we integrate openwebrtc with phonegap 
if the qulq'un already done it can help me because I am trying to develop hybrid application for iPads and i want integrated openwebrtc can anybody help me and thanks.

**Comment by stefanalund** [comment]
Absolutely possible. Our sample app "SimpleDemo" is a hybrid app and can be used as a starting point: https://github.com/EricssonResearch/openwebrtc-examples/tree/master/ios
