### ISSUE TITLE
what   signal protocol can  be used  for  openwebrtc  ?

### ISSUE THREAD

**Issue by wadeLeeWei** [EricssonResearch/openwebrtc#381]
what   signal protocol can  be used  for  openwebrtc  ?

**Comment by superdump** [comment]
Any that you like really. It's your choice. There are examples of how to do signaling using WebRTC web apps and we also have examples of how to inter operate with such web apps. See the iOS and Android SDKs and demo.openwebrtc.io for one of the many ways.

**Comment by wadeLeeWei** [comment]
Thank you !
