### ISSUE TITLE
Improved RTCP in gst-plugins-good

### ISSUE THREAD

**Issue by superdump** [EricssonResearch/openwebrtc#393]
@sdroege has been working on some significant RTCP improvements in gst-plugins-good. We probably need to investigate and implement some bits and pieces to add support for setting the RTP profile (AVPF, SAVPF, etc.)

https://bugzilla.gnome.org/show_bug.cgi?id=746543
https://github.com/superdump/cerbero/commit/bc01ecb5600f0b8810db91f465e3aa6a11530033

**Comment by sdroege** [comment]
Currently you always specify RTP/SAVPF in your SDP, so just always setting that as profile on rtpbin would be the first simple change for this.

Ideally the profile should be negotiated via SDP between both sides, or does WebRTC only support SAVPF?

**Comment by superdump** [comment]
Correct, WebRTC only support SAVPF so I guess we can just set that. :smiley:

**Comment by superdump** [comment]
This is all merged now. Closing.

**Comment by sdroege** [comment]
But it's not used in owr yet, or is it?
