### ISSUE TITLE
Cross-compile to MIPS

### ISSUE THREAD

**Issue by david7482** [EricssonResearch/openwebrtc#404]
Hi all, 

We are trying to build WebRTC application on embedded linux device.
However, it uses MIPS processor.
Does OWR support cross-compile to MIPS ? 
Or, any hint to do so ?

Thanks

**Comment by superdump** [comment]
Running Linux? It would probably work but I don't think any of the components have MIPS optimisations. However, I expect you probably have hardware codecs you want to use - you'd want to write GStreamer elements for those. And do you have OpenGL drivers for your graphics? What about your camera device - V4L2? Do you run pulseaudio or ALSA?

**Comment by sdroege** [comment]
ORC has MIPS support
