### ISSUE TITLE
could include config file 

### ISSUE THREAD

**Issue by umar021** [EricssonResearch/openwebrtc#412]
While building OpenWebRTC with cerbero and during bootstrap .. I am getting ERROR after this command 

    ./cerbero-uninstalled -c config/osx-x86-64.cbc bootstrap

    WARNING: Using default configuration because /Users/emarnir/.cerbero/cerbero.cbc is missing
    Traceback (most recent call last):
      File "./cerbero/utils/__init__.py", line 275, in parse_file
      execfile(filename, dict)
      File "/Users/emarnir/cerbero/config/darwin.config", line 88, in <module>
        raise Exception ("GL headers path not found: %s" % gl_headers)
    Exception: GL headers path not found:          /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.1    0.sdk/System/Library/Frameworks/OpenGL.framework/Headers
    Configuration Error: Could not include config file (/Users/emarnir/cerbero/config/darwin.config)

Please guide me what do do .. 

I am using Mac OX Yosemite vrsion 10.10.3

/Umar

**Comment by SrujithPoondla** [comment]
Did you find any solution for this??

**Comment by superdump** [comment]
This issue is half a year old and has been closed. Do you observe the issue now? You have to have Xcode installed and then you need to follow the build instructions exactly.

**Comment by SrujithPoondla** [comment]
successfully done . Thanks @superdump
