### ISSUE TITLE
Raspberry Pi 2 errors

### ISSUE THREAD

**Issue by buihuythangqn** [EricssonResearch/openwebrtc#417]
Please tell me how to build OpenWebRTC on Raspberry Pi 2. I think I built it successfully (OpenWebRTC appeared in /usr/local/lib and /usr/local/inclue/owr directories). But I tried to run examples I got many errors. For concretely when I run test-self-view, I got following error:
ERROR:owr_video_renderer.c:317:owr_video_renderer_get_element: assertion failed: (sink)
This errors happened on both Raspberry Pi 2 and Ubuntu Linux 15.04
Please help. Thanks.

**Comment by superdump** [comment]
More than just the vanilla OpenWebRTC code is needed. Some patches are needed to add support for compressed sources and also one needs to build gst-rpicamsrc for the Raspberry Pi camera source element for GStreamer. Among other things.

**Comment by superdump** [comment]
Also, please post on https://github.com/EricssonResearch/openwebrtc/issues/172 . Closing this issue to keep discussion there.
