### ISSUE TITLE
Bowser dont open - iOS, iPhone 5 and iPad

### ISSUE THREAD

**Issue by lfbasantos** [EricssonResearch/openwebrtc#422]
Sorry to post this message here, I couldnt find anywhere else to do.

I have an iPhone 5 with iOS 8.1.2 and an iPad with 8.1.0. I have just installed Bowser, and after saying "initializing" it crashes.

Are those devices not compatible?

Is there anything I should do in configurations?

Thank you very much, for any help.

**Comment by superdump** [comment]
This is because of https://github.com/EricssonResearch/openwebrtc/issues/385 - we are dependent on someone fixing the issues in libffi.

**Comment by ageekhere** [comment]
did 0.4 have this problem? I remember testing Bowser on the iphone 5 before 0.5 came out and it did not have a problem. Maybe we need to revert back to a working version until the current issue is fixed?

**Comment by superdump** [comment]
Closing as this issue is being tracked elsewhere.
