### ISSUE TITLE
Firefox 39 disabled TLS_RSA_WITH_AES_128_CBC_SHA cipher suite for DTLS/SRTP

### ISSUE THREAD

**Issue by pixelbender** [EricssonResearch/openwebrtc#432]
Seems Firefox 39 disabled TLS_RSA_WITH_AES_128_CBC_SHA cipher suites for DTLS/SRTP and now it's not working with OpenWebRTC (DTLS Handshake Failure):
https://www.dropbox.com/s/4y7i2r30uf47jco/Screenshot%202015-07-16%2016.58.47.png

**Comment by superdump** [comment]
I suppose we have a couple of options to address this:

* Disable the disallowed ciphers in our OpenSSL build in cerbero
* Detect the available ciphers and allow filtering of them in the gstdtls* elements

And then any extra bits and pieces in OpenWebRTC itself.

**Comment by kittee** [comment]
Works fine after upgrading to OpenSSL 1.0.2d

**Comment by superdump** [comment]
@kittee - great! Can you provide a pull request for that? :smile:

**Comment by kittee** [comment]
@superdump that would be just updating openssl version for dtls in configure.ac at gst-plugins-bad, but I don't see a way to submit pull request there

**Comment by superdump** [comment]
I rather meant a patch against our cerbero fork if you wanted to contribute that. :cat:

**Comment by sdroege** [comment]
@kittee Not everything is on github fortunately :) GStreamer does patch review (currently) in it's Bugzilla at https://bugzilla.gnome.org (but sooner or later probably moves to phabricator)

**Comment by superdump** [comment]
I've bumped cerbero to 1.0.2d. Closing this. Thanks for the report and for identifying the fix.

**Comment by kittee** [comment]
@superdump thanks!
