### ISSUE TITLE
Include binaries for all supported Android architectures in the distribution

### ISSUE THREAD

**Issue by Rugvip** [EricssonResearch/openwebrtc#435]
Working build:
- [x] armv7
- [ ] arm64
- [ ] x86 ?
- [ ] x86_64 ?

Included in distribution:
- [x] armv7
- [ ] arm64
- [ ] x86
- [ ] x86_64

**Comment by superdump** [comment]
I think all are supported by cerbero, it's just that we only build for armv7.

**Comment by Rugvip** [comment]
Yes, but I'm pretty sure at least arm64 doesn't build. I'm trying them all atm.
