### ISSUE TITLE
receiving only audio but sending both audio and video

### ISSUE THREAD

**Issue by suganthikarthick** [EricssonResearch/openwebrtc#445]
Hi,

In our application, we need to send both audio and video from our setup, but we need to receive only audio from the remote side.
Currently I am not setting the receive_payload in case of video, but still I am able to see in wireshark, the video packets coming from the remote side as they are selecting both audio and video while making the call. Here, we are receiving the video packets but our application is ignoring since the receive payload function is not set.

Whether it is possible to send only audio from the remote side but send both audio and video from local to remote? In that case, how the candidate information and ice negotiation will be happened for video?

Thanks.

**Comment by superdump** [comment]
Your signalling needs to communicate that the video session is 'sendonly' in your SDP. Default is sendrecv I believe.

**Comment by suganthikarthick** [comment]
Thank you so much. :+1:
