### ISSUE TITLE
Using autoaudiosrc and autoaudiosink instead of pulsesrc and pulsesink

### ISSUE THREAD

**Issue by suganthikarthick** [EricssonResearch/openwebrtc#446]
Hi,

Since the pulsesrc is depending on more libraries and it needs pulseaudio server to be running as daemon, we are planning to use autoaudiosrc and autoaudiosink instead of pulsesrc and pulsesink in openwebrtc.

So, we changed #define DEFAULT_AUDIO_SINK "pulsesink" to "autoaudiosink"  and #define AUDIO_SRC  "pulsesrc" to "autoaudiosrc". 
But still the stack is depending on pulseauio since some of API's related to pulseaudio is called inside the file local/owr_device_list.c - enumerate_audio_source_devices function and still we are facing some errors. It would be helpful if you give your suggestion on this.

What kind of changes are needed for using autoaaudiosrc in the openwebrtc stack.

Thanks.

**Comment by suganthikarthick** [comment]
we tried with custom audio source and it is working fine. is there any other way to use other gst elements instead of pulsesrc?

**Comment by superdump** [comment]
The problem with autoaudiosrc is precisely that you don't have any control over which input device is being used. We have tried to select the most appropriate audio source and sink elements for each platform.

As you have noted, if you need to use something else, the custom GStreamer media sources and renderers are there, though we need to make them easier for people to use.
