### ISSUE TITLE
regarding delay when using vp8

### ISSUE THREAD

**Issue by suganthikarthick** [EricssonResearch/openwebrtc#447]
Hi,

We are using openwebrtc in arm platform currently.
It is working fine with our signaling server. 
The media is transferring with vp8 encoding. Here, the video that we are sending is getting delayed by 3 to 4 seconds and audio is reaching correctly.

Since the audio is working without any delay and the video is delayed, the audio and video is not in sync.
How to sync the audio and video and also it would be helpful if you give your views on improving the video performance with vp8 encoding.

Thanks.

**Comment by superdump** [comment]
I'm going to close this one as we should track it in #451. A fix is coming but currently only works for H.264.
