### ISSUE TITLE
 Failed to link source -> source_process

### ISSUE THREAD

**Issue by suganthikarthick** [EricssonResearch/openwebrtc#452]
Hi,
We tried to install the openwebrtc in VM.
It has webcam connect to it.

When executing the application, we are facing some errors like this.

0:04:21.279674741  3541       0xaa1e30 ERROR    owrlocalmediasource owr_local_media_source.c:703:owr_local_media_source_request_source: Failed to link source -> source_process
==== Error message start ====
Error in element video-source.
Error: Internal data flow error.
Debugging info: gstbasesrc.c(2943): gst_base_src_loop (): /GstPipeline:local-video-capture-source-bin-0/GstV4l2Src:video-source:
streaming task paused, reason not-linked (-1)
==== Error message stop ====
-----------------------------------------------------------------------------------------------------------
==== Warning message start ====
Warning in element autoaudiosrc0-actual-src-puls.
Warning: Can't record audio fast enough
Debugging info: gstaudiobasesrc.c(866): gst_audio_base_src_create (): /GstPipeline:transport-agent-1/GstBin:bin0/GstAutoAudioSrc:autoaudiosrc0/GstPulseSrc:autoaudiosrc0-actual-src-puls:
Dropped 7680 samples. This is most likely because downstream can't keep up and is consuming samples too slowly.
==== Warning message stop ====

Thanks.

**Comment by superdump** [comment]
Did you resolve this? If not, can you set an environment variable `GST_DEBUG=2,GST_CAPS:6,*v4l2src*:6` and run your program redirecting the output into a file then upload the file somewhere so we can take a look.

**Comment by stefanalund** [comment]
Still having this problem?

**Comment by superdump** [comment]
I am pretty sure that @suganthikarthick has got past this issue as I know testing has been done with video. Closing but we can reopen if it's still an issue.

**Comment by suganthikarthick** [comment]
Hi Superdump,

We tried to install in VM but we faced some issue. May the error can be resolved but we didnt try in VM after that. And so we installed in native linux machine and used in that.

Thank you.
