### ISSUE TITLE
how to communicate with   openwebrtc by modifying  IOS NativeDemo  between two IOS device  

### ISSUE THREAD

**Issue by WangHeng861021** [EricssonResearch/openwebrtc#459]
hi,robert
I want to make audio communicating between two IOS device by modifying IOS NativeDemo,but after finishing sending offer and answer,the got_remote_source method can't be triggered,so it can't build the audio  connection,please help to tell that how to trigger the got_remote_source method in another IOS device.

**Comment by superdump** [comment]
The remote sources are created when incoming audio / video streams have been received. If you are not getting any there is probably something wrong with your offer/answer signalling or with ICE. I'd need more information to be able to say.

**Comment by stefanalund** [comment]
Can we close this?

**Comment by superdump** [comment]
I think whatever issue caused this is likely to be fixed now. Closing but we can reopen if it reoccurs.
