### ISSUE TITLE
Making bitrate configurable from the application

### ISSUE THREAD

**Issue by suganthikarthick** [EricssonResearch/openwebrtc#467]
Hi,

How to make the target bitrate configurable from the  testclient application?
Whether setting the "bitrate" from the payload of the media session is enough?
Thanks.

**Comment by superdump** [comment]
Setting the bitrate on the payload is enough.

If you have problems with that, check that the payload bitrate property is correctly bound, transformed and synchronized to the encoder element bitrate property and that that element supports adjustment.

**Comment by suganthikarthick** [comment]
I am setting the bitrate as follows.

if (OWR_IS_VIDEO_PAYLOAD(send_payload)) {
     g_object_set_data(session, "bitrate", GUINT_TO_POINTER(256000));
} else

but when I do a print inside the function "evaluate_bitrate_from_payload" inside the owr/payload.c, we are not getting the value that we are setting.

Whether the way that I am setting is correct?

Thanks.

**Comment by suganthikarthick** [comment]
Hi Robert,

We did like as follows.

g_object_set(send_payload, "bitrate", target_bitrate_g, NULL);

And it is working fine.

Thanks.
