### ISSUE TITLE
iOS Client sending SDP message different from the one expected by test_client.c

### ISSUE THREAD

**Issue by barcoyou** [EricssonResearch/openwebrtc#469]
The iOS client send message:
"type":"answer","sdp":"v=0\r\no=- 3166549352666813948 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS 462mtD6dMPkBF4nYOo5XvFK368A8qIjE5Yrp\r\nm=audio 9 RTP/SAVPF 111 103 104 9 0 8 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:F5FMaWkhWqt/yxP2\r\na=ice-pwd:WXdmOjQMw0kcfyNArR1FpCLZ\r\na=fingerprint:sha-256 6D:CF:0A:84:FD:F9:E4:FF:5C:93:45:7B:F6:C4:07:51:9F:6D:1A:B4:7F:28:A5:87:19:F5:B1:5F:DE:91:5D:A8\r\na=setup:active\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10; useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:126 telephone-event/8000\r\na=maxptime:60\r\na=ssrc:3503228008 cname:d6qz8ueguKnd/8vI\r\na=ssrc:3503228008 msid:462mtD6dMPkBF4nYOo5XvFK368A8qIjE5Yrp 7acb6557-177c-421e-92d3-82df566659d7\r\na=ssrc:3503228008 mslabel:462mtD6dMPkBF4nYOo5XvFK368A8qIjE5Yrp\r\na=ssrc:3503228008 label:7acb6557-177c-421e-92d3-82df566659d7\r\nm=video 9 RTP/SAVPF 100 116 117 96\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:F5FMaWkhWqt/yxP2\r\na=ice-pwd:WXdmOjQMw0kcfyNArR1FpCLZ\r\na=fingerprint:sha-256 6D:CF:0A:84:FD:F9:E4:FF:5C:93:45:7B:F6:C4:07:51:9F:6D:1A:B4:7F:28:A5:87:19:F5:B1:5F:DE:91:5D:A8\r\na=setup:active\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:100 VP8/90000\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 goog-remb\r\na=rtpmap:116 red/90000\r\na=rtpmap:117 ulpfec/90000\r\na=rtpmap:96 rtx/90000\r\na=fmtp:96 apt=100\r\na=ssrc-group:FID 3898764650 2381895492\r\na=ssrc:3898764650 cname:d6qz8ueguKnd/8vI\r\na=ssrc:3898764650 msid:462mtD6dMPkBF4nYOo5XvFK368A8qIjE5Yrp ca912d9a-97b2-4018-a21d-a1c1f2b31ad7\r\na=ssrc:3898764650 mslabel:462mtD6dMPkBF4nYOo5XvFK368A8qIjE5Yrp\r\na=ssrc:3898764650 label:ca912d9a-97b2-4018-a21d-a1c1f2b31ad7\r\na=ssrc:2381895492 cname:d6qz8ueguKnd/8vI\r\na=ssrc:2381895492 msid:462mtD6dMPkBF4nYOo5XvFK368A8qIjE5Yrp ca912d9a-97b2-4018-a21d-a1c1f2b31ad7\r\na=ssrc:2381895492 mslabel:462mtD6dMPkBF4nYOo5XvFK368A8qIjE5Yrp\r\na=ssrc:2381895492 label:ca912d9a-97b2-4018-a21d-a1c1f2b31ad7\r\n"}

but the test_client.c expect message:
{"sdp":{"sdp":"v=0\r\no=- 1442570332604854000 1 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\nm=video 1 RTP/SAVPF 103 100 120\r\nc=IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=sendrecv\r\na=rtpmap:103 H264/90000\r\na=rtpmap:100 VP8/90000\r\na=rtpmap:120 RTX/90000\r\na=fmtp:103 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=fmtp:120 apt=100;rtx-time=200\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:103 nack pli\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:103 ccm fir\r\na=rtcp-fb:100 ccm fir\r\na=ice-ufrag:LNy6\r\na=ice-pwd:+BN0ixHVn9qotKO97Dc+p1\r\na=candidate:1 1 UDP 2013266431 fe80::58ad:92ff:fe84:9f08 51164 typ host\r\na=candidate:2 1 TCP 1019216383 fe80::58ad:92ff:fe84:9f08 0 typ host tcptype active\r\na=candidate:3 1 TCP 1015022079 fe80::58ad:92ff:fe84:9f08 63464 typ host tcptype passive\r\na=candidate:4 1 UDP 2013266431 192.168.1.167 57936 typ host\r\na=candidate:5 1 TCP 1019216383 192.168.1.167 0 typ host tcptype active\r\na=candidate:6 1 TCP 1015022079 192.168.1.167 63465 typ host tcptype passive\r\na=candidate:7 1 UDP 2013266431 fe80::8b8:1e4e:32d2:3015 57937 typ host\r\na=candidate:8 1 TCP 1019216383 fe80::8b8:1e4e:32d2:3015 0 typ host tcptype active\r\na=candidate:9 1 TCP 1015022079 fe80::8b8:1e4e:32d2:3015 63466 typ host tcptype passive\r\na=fingerprint:sha-256 E2:7A:4A:50:78:71:FC:CA:8B:27:F8:C3:2B:61:72:6B:A7:AC:CF:2D:D4:D3:B8:16:9C:0F:43:8B:9A:D3:EA:97\r\na=setup:actpass\r\nm=audio 1 RTP/SAVPF 111 8 0\r\nc=IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=sendrecv\r\na=rtpmap:111 OPUS/48000/2\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:0 PCMU/8000\r\na=ice-ufrag:T/De\r\na=ice-pwd:zHTFcrr6S01Red+Rau0yCb\r\na=candidate:10 1 UDP 2013266431 fe80::58ad:92ff:fe84:9f08 57938 typ host\r\na=candidate:11 1 TCP 1019216383 fe80::58ad:92ff:fe84:9f08 0 typ host tcptype active\r\na=candidate:12 1 TCP 1015022079 fe80::58ad:92ff:fe84:9f08 63467 typ host tcptype passive\r\na=candidate:13 1 UDP 2013266431 192.168.1.167 59780 typ host\r\na=candidate:14 1 TCP 1019216383 192.168.1.167 0 typ host tcptype active\r\na=candidate:15 1 TCP 1015022079 192.168.1.167 63468 typ host tcptype passive\r\na=candidate:16 1 UDP 2013266431 fe80::8b8:1e4e:32d2:3015 59781 typ host\r\na=candidate:17 1 TCP 1019216383 fe80::8b8:1e4e:32d2:3015 0 typ host tcptype active\r\na=candidate:18 1 TCP 1015022079 fe80::8b8:1e4e:32d2:3015 63469 typ host tcptype passive\r\na=fingerprint:sha-256 E2:7A:4A:50:78:71:FC:CA:8B:27:F8:C3:2B:61:72:6B:A7:AC:CF:2D:D4:D3:B8:16:9C:0F:43:8B:9A:D3:EA:97\r\na=setup:actpass\r\n","type":"offer"},"sessionDescription":{"version":0,"originator":{"username":"-","sessionId":1442570332604854000,"sessionVersion":1,"netType":"IN","addressType":"IP4","address":"127.0.0.1"},"sessionName":"-","startTime":0,"stopTime":0,"mediaDescriptions":[{"type":"video","port":"1","protocol":"RTP/SAVPF","netType":"IN","addressType":"IP4","address":"0.0.0.0","mode":"sendrecv","payloads":[{"type":103,"encodingName":"H264","clockRate":90000,"nack":false,"nackpli":true,"ccmfir":true},{"type":100,"encodingName":"VP8","clockRate":90000,"nack":true,"nackpli":true,"ccmfir":true},{"type":120,"encodingName":"RTX","clockRate":90000,"nack":false,"nackpli":false,"ccmfir":false}],"rtcp":{"mux":true},"ice":{"ufrag":"LNy6","password":"+BN0ixHVn9qotKO97Dc+p1","candidates":[{"foundation":"1","componentId":1,"transport":"UDP","priority":2013266431,"address":"fe80::58ad:92ff:fe84:9f08","port":51164,"type":"host"},{"foundation":"2","componentId":1,"transport":"TCP","priority":1019216383,"address":"fe80::58ad:92ff:fe84:9f08","port":0,"type":"host","tcpType":"active"},{"foundation":"3","componentId":1,"transport":"TCP","priority":1015022079,"address":"fe80::58ad:92ff:fe84:9f08","port":63464,"type":"host","tcpType":"passive"},{"foundation":"4","componentId":1,"transport":"UDP","priority":2013266431,"address":"192.168.1.167","port":57936,"type":"host"},{"foundation":"5","componentId":1,"transport":"TCP","priority":1019216383,"address":"192.168.1.167","port":0,"type":"host","tcpType":"active"},{"foundation":"6","componentId":1,"transport":"TCP","priority":1015022079,"address":"192.168.1.167","port":63465,"type":"host","tcpType":"passive"},{"foundation":"7","componentId":1,"transport":"UDP","priority":2013266431,"address":"fe80::8b8:1e4e:32d2:3015","port":57937,"type":"host"},{"foundation":"8","componentId":1,"transport":"TCP","priority":1019216383,"address":"fe80::8b8:1e4e:32d2:3015","port":0,"type":"host","tcpType":"active"},{"foundation":"9","componentId":1,"transport":"TCP","priority":1015022079,"address":"fe80::8b8:1e4e:32d2:3015","port":63466,"type":"host","tcpType":"passive"}]},"dtls":{"fingerprintHashFunction":"sha-256","fingerprint":"E2:7A:4A:50:78:71:FC:CA:8B:27:F8:C3:2B:61:72:6B:A7:AC:CF:2D:D4:D3:B8:16:9C:0F:43:8B:9A:D3:EA:97","setup":"actpass"}},{"type":"audio","port":"1","protocol":"RTP/SAVPF","netType":"IN","addressType":"IP4","address":"0.0.0.0","mode":"sendrecv","payloads":[{"type":111,"encodingName":"OPUS","clockRate":48000,"channels":2},{"type":8,"encodingName":"PCMA","clockRate":8000,"channels":1},{"type":0,"encodingName":"PCMU","clockRate":8000,"channels":1}],"rtcp":{"mux":true},"ice":{"ufrag":"T/De","password":"zHTFcrr6S01Red+Rau0yCb","candidates":[{"foundation":"10","componentId":1,"transport":"UDP","priority":2013266431,"address":"fe80::58ad:92ff:fe84:9f08","port":57938,"type":"host"},{"foundation":"11","componentId":1,"transport":"TCP","priority":1019216383,"address":"fe80::58ad:92ff:fe84:9f08","port":0,"type":"host","tcpType":"active"},{"foundation":"12","componentId":1,"transport":"TCP","priority":1015022079,"address":"fe80::58ad:92ff:fe84:9f08","port":63467,"type":"host","tcpType":"passive"},{"foundation":"13","componentId":1,"transport":"UDP","priority":2013266431,"address":"192.168.1.167","port":59780,"type":"host"},{"foundation":"14","componentId":1,"transport":"TCP","priority":1019216383,"address":"192.168.1.167","port":0,"type":"host","tcpType":"active"},{"foundation":"15","componentId":1,"transport":"TCP","priority":1015022079,"address":"192.168.1.167","port":63468,"type":"host","tcpType":"passive"},{"foundation":"16","componentId":1,"transport":"UDP","priority":2013266431,"address":"fe80::8b8:1e4e:32d2:3015","port":59781,"type":"host"},{"foundation":"17","componentId":1,"transport":"TCP","priority":1019216383,"address":"fe80::8b8:1e4e:32d2:3015","port":0,"type":"host","tcpType":"active"},{"foundation":"18","componentId":1,"transport":"TCP","priority":1015022079,"address":"fe80::8b8:1e4e:32d2:3015","port":63469,"type":"host","tcpType":"passive"}]},"dtls":{"fingerprintHashFunction":"sha-256","fingerprint":"E2:7A:4A:50:78:71:FC:CA:8B:27:F8:C3:2B:61:72:6B:A7:AC:CF:2D:D4:D3:B8:16:9C:0F:43:8B:9A:D3:EA:97","setup":"actpass"}}]},"type":"offer"}

How should I change the iOS client codes????

**Comment by stefanalund** [comment]
Try changing what is signaled here: https://github.com/EricssonResearch/openwebrtc-examples/blob/master/ios/NativeDemo/NativeDemo/NativeDemoViewController.m#L185

**Comment by barcoyou** [comment]
Hi Stefan,
It works now. Thank you very much.

Then another question. After the test_client.c get the video stream from another client, how can I output it to a UDP stream? Thank you!

**Comment by stefanalund** [comment]
@barcoyou if you think your solution is the proper way of doing things, please send a Pull Request with your changes.

I don't know how to get the media stream, perhaps @superdump can assist.

**Comment by barcoyou** [comment]
Ok, I will do a ull Request
