### ISSUE TITLE
Handling one to many session

### ISSUE THREAD

**Issue by suganthikarthick** [EricssonResearch/openwebrtc#470]
Hi,

We are working on the basis of test client application - which is for one to one scenario.
Incase of one to many session, we are sending the audio and video to the media server and it is communicating with n users and sending the audio and video to the n users. This has been done already.
But the audio needs to be received from every user and it should be played back in our application.
For implementing this, for each user, an audio session needs to be created and the Ice negotiation needs to done for receiving the audio.

Does anyone have any suggestion on implementing this?

**Comment by satyampv** [comment]
@suganthikarthick  I am looking for to connect with one => many session or many=>many like . creating any room or something you can say group call with 3 people. You already implemented a Video Section for this. will you guide me to setup one=>many session ?
