### ISSUE TITLE
Mac version 10.11 not supported

### ISSUE THREAD

**Issue by HedbergMartin** [EricssonResearch/openwebrtc#479]
Upon building OpenWebRTC on the latest Mac version (10.11, El Capitan) a fatal error is thrown: 
File "./cerbero/utils/__init__.py", line 232, in system_info
    raise FatalError("Mac version %s not supported" % ver)
cerbero.errors.FatalError: Fatal Error: Mac version 10.11 not supported

**Comment by superdump** [comment]
https://github.com/EricssonResearch/cerbero/pull/31

**Comment by adam-be** [comment]
Thanks @superdump
