### ISSUE TITLE
OpenWebRTC iOS SimpleDemo not working on iOS9

### ISSUE THREAD

**Issue by icasey** [EricssonResearch/openwebrtc#482]
Hi,
I'm new to OpenWebRTC and iOS development. I have been testing this with the SimpleDemo codes for 2 weeks, it works fine on iOS8.x. But I got updated to iOS 9 yesterday. I ran the same code with Xcode adviced code fix on iOS9, it built successfully, but after the app launch with the logo then it was a blank page, instead of showing your demo web page:( 

Could anyone please help? I don't know where to start and how to fix it....

**Comment by stefanalund** [comment]
I think this may have to do with iOS 9 SDK requiring HTTPS. I disabled it for Bowser before: https://github.com/EricssonResearch/bowser/commit/a11cb3a5c36151ec1d458f8bfd60e2c4d58ea2ba

Let me know if this helps.

**Comment by icasey** [comment]
@stefanalund
omg you nailed it
Just so that same changes and it works now:)
Thank you so much for the quick reply and saved my day:)

**Comment by stefanalund** [comment]
Awesome. I would really appreciate if you sent in a Pull Request with your changes so that others won't have the same problem. Thanks in advance.

**Comment by icasey** [comment]
@stefanalund
Seems like it's not done yet:(
I tested it on iPhone5 iOS9 is fine, but when it comes to iPhone6 iOS6, I got this error....
No clue what's going on...


I would love to send a pull request if I solved the problem, thanks again

![image](https://cloud.githubusercontent.com/assets/14147618/10393136/cc35b812-6ebf-11e5-8ebe-0cf7dd61ea2d.png)

**Comment by icasey** [comment]
I have tried put openwebrtc.framework 0.3.1 to the project, but no luck....  :(

All i was testing the files in https://github.com/EricssonResearch/openwebrtc-examples/tree/master/ios/SimpleDemoSwift

**Comment by icasey** [comment]
IPhone5 with ios9 is working fine.
But iphone6 with ios9 is not working...

**Comment by bamboolsu** [comment]
@icasey 

The follow issue hasn't been fixed up to now. then How can you work for iphone 5 ?  can you submit your change into the github or give some clue on the follow issue, thanks.

https://github.com/EricssonResearch/openwebrtc/issues/385

**Comment by icasey** [comment]
I'm new to ios development and cerbero. just share what i've tested and test results of switching openwebrtc.framework.

Finally, today i can build the up-to-date framework based on the guide (which is good and simple, that's a long story that i can't build one for a long time, it was some stupid stuff):
https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

I found that i can make the app works on iphone6, which is what i want to solve.
The key factory i changed is the framework, i use the latest source and compile the framework to replace to the app project.

Test Result:
openwebrtc.framework     iphone6    iphone5s    iphone5
     10.10.2015 build              ok               ok           error
     26.04.2015 build            error       not tested       ok

Test case details:
test project = SimpleDemoSwift (https://github.com/EricssonResearch/openwebrtc-examples/tree/master/ios/SimpleDemoSwift)
mac setting = mac version: 10.11, xcode version: 7.0.1
tested device = iphone5(iOS9), iphone5s(iOS8.3), iphone6(iOS9)

**Comment by stefanalund** [comment]
@bamboolsu the pure native apps (like NativeDemo don't use the "bridge" and should therefore not be affected by the libffi issues.

@icasey that is really nice to hear! We will make sure to release a new version of the pre-compiled framework as soon as possible. Did you only change the framework or also somewhere in the app code? Thanks.

**Comment by icasey** [comment]
For iOS9, I have to update my xcode to >=7.0 to test the app on device.
There are things that I have change in the project:
- disable bitcode and HTTPS as @stefanalund  mentioned (https://github.com/EricssonResearch/bowser/commit/a11cb3a5c36151ec1d458f8bfd60e2c4d58ea2ba)
- replace libresolv.dylib and libc++.dylib  to  libresolv.tbd and libc++.tbd (duno if this is necessary, but i replaced them and it worked : )
- update swift syntax from   Edit > Convert > To Latest Swift Syntax...


For 64bit problem, i just changed the framework.


Framework I used in this test:
10.10.2015 build: https://drive.google.com/open?id=0B49chjTf6eU1SWJKYlJ6WWJqZTA

26.04.2015 build (0.3.0): https://drive.google.com/open?id=0B49chjTf6eU1Nnc2UjZ1YkFYRVE
or in this link at the moment(https://github.com/EricssonResearch/openwebrtc/releases)

**Comment by icasey** [comment]
@stefanalund Thanks again  : )

Please find the files(10.10.2015 build) in https://drive.google.com/open?id=0B49chjTf6eU1UHpYbkRidDdOMkU
if you need it.

**Comment by stefanalund** [comment]
It would be great if you could provide a PR for the app changes so that we don't need to do the same changes again.

**Comment by icasey** [comment]
things got out of my control...

when I thought it's ok and running successfully with ios9 iphone6, problems come out when I archived the app to upload to app store or in ad hoc distribution, it crashed after initializing.

I dont really know what to do..... sign.......

**Comment by bamboolsu** [comment]
@icasey  a

Oh, Are there any other suggestions for IOS 9?

And how can you get the following results? Thanks.

------------------------------------------------------------------------------------------------
Test Result:
openwebrtc.framework____iphone6___iphone5s___iphone5
___10.10.2015 build_________ok_______ok_______error
___26.04.2015 build________error___not tested_____ok
------------------------------------------------------------------------------------------------

**Comment by stefanalund** [comment]
I remember having to set "don't strip linked products" for Bowser: https://github.com/EricssonResearch/bowser/commit/2db2956cc1b4866eef9ddc625a471100a2b1a804#diff-631f4b4ea8bb3cefd08b001b9cca1a22R4193

**Comment by bamboolsu** [comment]
Hi, @stefanalund  and other experts:

-----------------------------------------------------------

I remember having to set "don't strip linked products" for Bowser: EricssonResearch/bowser@2db2956#diff-631f4b4ea8bb3cefd08b001b9cca1a22R4193

-----------------------------------------------------
"don't strip" has merged into the github.

so we still don't know how to make our bowser working for IOS9 on Iphone 6 and Iphone 6 plus.

**Comment by stefanalund** [comment]
@bamboolsu, yes, sorry. I was providing the pointer to @icasey since he is not using Bowser.

**Comment by bamboolsu** [comment]
Now most of Iphone has updated  ios to 9. and openwebrtc cannot run one ios 9. This issue should be a high priority. 

Are there anybody pay attention to this issue?

**Comment by stefanalund** [comment]
Yes, we are looking in to it.

**Comment by icasey** [comment]
@bamboolsu  Oh yes, it works by turning off "strip lined product"

**Comment by icasey** [comment]
Hey guys,

I have built iOS9 version of SimpleDemo in https://drive.google.com/file/d/0B49chjTf6eU1NXhqeHl4V1BYdG8/view?usp=sharing

(I have tried a few times to upload this to github, but I don't know why I cannot see it on my page or here....so i just upload the zip file, can you guys help to upload the files to this page?)

As I tested the demo on iPhone5(iOS9) and iPhone6(iOS9), it required different version of openwebrtc.framework (this is my conclusion for now after many times of trials, if there were better solution please let me know).

For iPhone5 or older models, the demo folder is named as "SimpleDemo_iOS9_iPhone5" and the framework is 26.04.2015 build (0.3.0)(https://drive.google.com/open?id=0B49chjTf6eU1Nnc2UjZ1YkFYRVE)
or in this link at the moment(https://github.com/EricssonResearch/openwebrtc/releases).

For iPhone6 or newer models, the demo folder is named as "SimpleDemoSwift_iOS9_iPhone6" and the framework is 10.10.2015 build (https://drive.google.com/open?id=0B49chjTf6eU1SWJKYlJ6WWJqZTA)


The changes I made with xcode7:
- disable bitcode and HTTPS as @stefanalund mentioned (EricssonResearch/bowser@a11cb3a)
- replace libresolv.dylib and libc++.dylib to libresolv.tbd and libc++.tbd (duno if this is necessary, but i replaced them and it worked : )
- update swift syntax from Edit > Convert > To Latest Swift Syntax... (in case of using swift)
- turn off strip linked products as @bamboolsu mentioned, so that it can be archived and running without error (https://github.com/EricssonResearch/bowser/commit/2db2956)
- change the openwebrtc.framework as montioned above


This is the workaround I found, but I don't know why and how to fix or improve it.
I love you guys keep up the great work :)

**Comment by stefanalund** [comment]
@icasey have you also tried running NativeDemo, or are you more interested in a hybrid app?

**Comment by icasey** [comment]
@stefanalund i have not try Native Demo yet, as i dont know how to add webview with swift yet. Lol...
I might try it later

**Comment by stefanalund** [comment]
(the NativeDemo does not use WebViews of any sort)

**Comment by stefanalund** [comment]
@icasey is this the same problem that you solved, you think? https://github.com/EricssonResearch/bowser/issues/60

**Comment by icasey** [comment]
@stefanalund I dont know if it is related... I dont have 6s to test it though...

**Comment by icasey** [comment]
@stefanalund but i do know that the app store downloaded version is running fine for both iphone6 and iphone5

**Comment by stefanalund** [comment]
@icasey Do you have a link to your app so I can try it on my iPhone 6s?

**Comment by bamboolsu** [comment]
@icasey  Based on your steps, I have run the demo of https://drive.google.com/file/d/0B49chjTf6eU1NXhqeHl4V1BYdG8/view?usp=sharing on  iphone 5 (IOS 9) and iphone 6(IOS 9).

The result is:
   SimpleDemo_iOS9_iPhone5   ::     IPhone5 (IOS 9)  ::     successful loaded.
   SimpleDemo_iOS9_iPhone5    ::    IPhone5 (IOS 8)    ::    Failed loaded.
   SimpleDemoSwift_iOS9_iPhone6   ::     IPhone5s (IOS 8)   ::    Failed loaded.
   SimpleDemoSwift_iOS9_iPhone6   ::    IPhone6 (IOS 9)    ::     successful loaded.
   SimpleDemoSwift_iOS9_iPhone6   ::     IPhone6 (IOS 8)    ::     Failed loaded.
   SimpleDemoSwift_iOS9_iPhone6   ::    IPhone6 plus (IOS 9)   ::     Failed loaded.

So some questions for the result:
 1, why all IOS 8 phones are always failed?   
 2, Why IPhone 6s with IOS9 is failed?
 3,  For ' the framework is 26.04.2015 build (0.3.0)', Have you done some modification for the official cerbero (26-04-2015)?
  4,  For '  the framework is 10.10.2015 build', Have you done some modification for the official cerbero (10-10-2015)?  I have built the latest cerbero, but when I test it on IPhone 6 (IOS 9), Failed loaded!  why? I guess you have done some modification.

**Comment by icasey** [comment]
@bamboolsu 
The framework 26.04.2015 build (0.3.0) in (https://drive.google.com/file/d/0B49chjTf6eU1Nnc2UjZ1YkFYRVE/view?usp=sharing) or in this link at the moment(https://github.com/EricssonResearch/openwebrtc/releases). These two are the same.

Before I raised up this issue, I was using xcode6.3 and 26.04.2015 build (0.3.0) for building app for iPhone5(iOS8.4) and iPhone6(iOS8.4), they were both running fine...(not sure if I remembered correctly about iPhone6 was fine).

For ' the framework is 10.10.2015 build', I have done a little modification but nothing matters to the function in order to compile it successfully, just changed the a line of ~\cerbero\config\darwin.config as below:
"sdk_version = osx_target_sdk_version or SDK_VERSION[distro_version]"
to
"sdk_version = 10.11 or SDK_VERSION[distro_version]"
and I was following the guide to compile it, it took hours to compile on my mac mini (not sure if it's normal).

I have no iOS8 iPhone here, so I have not tested the files I uploaded to iOS8.

**Comment by icasey** [comment]
@bamboolsu 
I have found that I have to "clean"  before every time I "build", otherwise it goes wrong on the app.

**Comment by icasey** [comment]
@stefanalund 
http://install.diawi.com/p7FeZo (iPhone6 not tested yet, I will have the phone to test at night)
http://install.diawi.com/XRBCR8 (iPhone5 tested, working fine)

**Comment by stefanalund** [comment]
@icasey sorry, can't install the apps :disappointed:

**Comment by icasey** [comment]
updated:
working app tested on iPhone6 Plus iOS9
http://install.diawi.com/HN8ihW
![20151019_180500_hdr-1](https://cloud.githubusercontent.com/assets/14147618/10575070/a47a3364-768c-11e5-8b3b-d284696b431c.jpg)

**Comment by bamboolsu** [comment]
@icasey 　First thanks for you quickly answer for my issues.

Using "The framework 26.04.2015 build (0.3.0) ", I have tried the latest  openwebrtc-examples/ios/SimpleDemo and openwebrtc-examples/ios/SimpleDemoSwift.  Iphone 5 with IOS8 always failed. but I Cannot find why?  :disappointed:  But by using the  same framework, IPhone 5 with IOS9 can work fine.

And for IPhone5 with IOS8, when I download it from apple app, which also cannot work.  :disappointed:

So how can your iphone5 (IOS8) work? Are you do any modification?

Test environment:
    Xcode 6.1.1    Xcode 6.4  Xcode 7.0.1 
    MAC os 10.10.5

**Comment by stefanalund** [comment]
What happened to your screen :smiley:

**Comment by stefanalund** [comment]
Thanks to your hard work @icasey I have submitted the following PR https://github.com/EricssonResearch/openwebrtc-examples/pull/125 that should close this Issue. Much appreciated!

**Comment by icasey** [comment]
Hey @stefanalund 
May I know if there's any way to switch camera in ios hybrid app?
or set back camera as default?

I have checked the selfie app but I don't understand most of the code, I dont know where to start digging...
if there's an easy way to set the default camera in config or in code b4 compiling the framework...
Thanks!

**Comment by stefanalund** [comment]
@icasey since you are developing a Hybrid app I assume you are looking for the JavaScript way of doing it: https://github.com/EricssonResearch/openwebrtc/wiki/Developing-WebRTC-web-applications-for-OpenWebRTC-and-Bowser#selecting-camera

**Comment by icasey** [comment]
@stefanalund 
Thanks for your quick reply!!!
I try it now, Thanks~

**Comment by icasey** [comment]
@stefanalund 
It works so fine!
Thanks! <3

**Comment by stefanalund** [comment]
Great! The issue with ARM 32-bit should also be solved now. Let us know if you have any other questions/problems.

**Comment by icasey** [comment]
@stefanalund 
May I know if the standard compiled framework has embedded compress video and audio function?
Any api I can change the streaming video / audio quality via web or native code?
It takes very high bandwidth, like 30~40Mbps.

I only know how to change the constraints in getUserMedia for web, is that works for ios / android hybrid?

Thanks!

**Comment by stefanalund** [comment]
Not sure what you mean by "embedded compress video". We have native APIs for setting video bitrate. Have a look at NativDemo.

**Comment by superdump** [comment]
@icasey : we have not added some official compressed source support yet but it should not be too much work to implement it now and I think @suganthikarthick and a few other OpenWebRTC users have implemented that. It would be good if someone did it in a generic way now and contributed it back to us so that all can benefit.

**Comment by icasey** [comment]
@superdump @stefanalund 
Thanks guys!!!
I will take a look a it :)

**Comment by icasey** [comment]
@superdump @stefanalund 
as I found that the framwork has been updated, I tried to compile, update and test on ios demo app.
And I got this error as show below,
![image](https://cloud.githubusercontent.com/assets/14147618/11162456/9c808022-8add-11e5-9df4-daf9f25368d4.png)

I had just updated the framework, nothing changed. The app used to be built successfully, instead of changing to the latest one I compiled.

I was hoping if the latest one can solve some problem, like arm7 arm64 issue or video stream delay so much than audio
Please help:(

Thanks!

**Comment by icasey** [comment]
I don't know if it's the error I got from false framework compile or any other problem...

If you have compiled the latest framework ios pkg, please share it and let me try.

Thanks!

**Comment by superdump** [comment]
@stefanalund : have you seen this with SimpleDemo?

**Comment by stefanalund** [comment]
Yes, just add libiconv to the project. For some reason it was removed earlier by Alessandro.

**Comment by alessandrod** [comment]
Oh no, I created a pull request to actually add the iconv dependency back since I get this failure too. See https://github.com/EricssonResearch/cerbero/pull/41

**Comment by icasey** [comment]
Dear All,
May I know if the _iconv problem fixed?
as I have just downloaded the latest and complied it, the problem is still exist :(

**Comment by stefanalund** [comment]
Sorry for leaving this hanging. You need to add libiconv to the project build settings (Extrnal Libraries). Let me know if you have problems.

**Comment by icasey** [comment]
@stefanalund
Cool I added it and it works!!!!

Thanks! 
: )

**Comment by stefanalund** [comment]
Super @icasey!

**Comment by stefanalund** [comment]
Could you please submit a PR?

**Comment by icasey** [comment]
@stefanalund 
I tried but i don't know how to submit this.
I have updated openwebrtc-example/ios/SimpleDemo and SimpleDemoSwift. I tested them they both working.

change log:
SimpleDemo:
- added libiconv.tbd

SimpleDemoSwift:
- added libiconv.tbd
- changed libresolv to .tbd
- changed libc++ to .tbd
- changed Enable Bitcode to No in Build Setting
- changed Strip Linked Product to No in Build Setting
- added item to info.plist as following
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>


please find them in https://drive.google.com/file/d/0B49chjTf6eU1WHFweW00VkdHS1k/view?usp=sharing

**Comment by stefanalund** [comment]
@icasey we use the workflow where you first my a fork of the repo: https://yangsu.github.io/pull-request-tutorial/
