### ISSUE TITLE
irc channel of openwebrtc

### ISSUE THREAD

**Issue by suganthikarthick** [EricssonResearch/openwebrtc#484]
Hi,

We tried to access the IRC channel for openwebrtc. But we are facing some issue.
Can you send the exact link?

Thanks.

**Comment by ford-prefect** [comment]
You can use the web client at: https://webchat.freenode.net/?channels=#openwebrtc

To know more about using IRC: http://freenode.net/using_the_network.shtml

**Comment by suganthikarthick** [comment]
Thanks
