### ISSUE TITLE
using gst_pipeline_use_clock in owr_transport_agent_init

### ISSUE THREAD

**Issue by suganthikarthick** [EricssonResearch/openwebrtc#485]
Hi,

Currently we are facing an issue in which, if we send both audio and video, the video is having more stuck in between. If we send only video, then the video is playing perfectly good.
For resolving this issue, we were trying and testing with different scenarios.

We tried the following but we are not getting the audio on the other side.
As per the patch #240, we added the following lines at the file owr_transport_agent.c inside the function owr_transport_agent_init().

gst_pipeline_use_clock(GST_PIPELINE(priv->pipeline), gst_system_clock_obtain());
gst_element_set_base_time(priv->pipeline, 0);
gst_element_set_start_time(priv->pipeline, GST_CLOCK_TIME_NONE);

When adding the above lines, the audio is not able to hear on the browser side and the video is playing fine. On removing those line, we are able to hear the audio, but the video is stuck.

Thanks.

**Comment by sdroege** [comment]
Why are *you* adding those lines to the transport agent code? The lines are already there

**Comment by suganthikarthick** [comment]
We are using the openwebrtc-0.3 version, in which the code is not there.

**Comment by sdroege** [comment]
You need more changes than just those lines. Update your openwebrtc version.

**Comment by suganthikarthick** [comment]
Ok, thank you.
I am using the custom gst pipelines for my application.

Here, I am using as follows.
gst_source = gst_parse_bin_from_description(bin_description, TRUE, &error);

I am not sure on how to set the system clock for the above?
