### ISSUE TITLE
Android: change audio routing

### ISSUE THREAD

**Issue by gabberrr** [EricssonResearch/openwebrtc#489]
Hi! How I can change audio stream routing to headphones?
Need something like this audioManager.setMode(AudioManager.MODE_IN_CALL)

**Comment by ford-prefect** [comment]
AudioManager calls are intended to be managed by you. There isn't intentionally no API in GStreamer or OpenWebRTC to deal with that as it is expected that the app devloper is in the best position to manage these bits.
