### ISSUE TITLE
Ubuntu 15.04 no daemon

### ISSUE THREAD

**Issue by HedbergMartin** [EricssonResearch/openwebrtc#490]
I built OpenWebRTC on Ubuntu 15.04 and the build went through successfully. But I don't get any owr daemon

**Comment by HedbergMartin** [comment]
My linux_x86_64 is only containing /share which seems to be the problem, but I don't know why

**Comment by HedbergMartin** [comment]
I built a new cerbero, got the same result. Then I rebuilt cerbero and then I got a daemon. This seems odd especially when I built it 2 times

**Comment by stefhak** [comment]
Closing as you got it to work.
