### ISSUE TITLE
Build Error. Many patches failed

### ISSUE THREAD

**Issue by NSky** [EricssonResearch/openwebrtc#495]
I followed the official guide but failed with error below. This actually also happened to zlib and glib
which I fixed by applying patches manually. But that's too boring to do it for about 30 libs.
Ubuntu 14.04; git 2.6.2

BTW: My main goal is to stream audio (only!) from Chrome to Raspberry Pi (there is no camera device on RPi). Could someone tell me if I'm going the right way of if this is possible to implement with openwebrtc at all?

[(5/37) bzip2 -> extract ]
-----> Extracting tarball to /home/eugene/cerbero/sources/linux_x86_64/bzip2-1.0.6
Unpacking /home/eugene/cerbero/sources/local/bzip2-1.0.6/bzip2-1.0.6.tar.gz in /home/eugene/cerbero/sources/linux_x86_64
Initialized empty Git repository in /home/eugene/cerbero/sources/linux_x86_64/bzip2-1.0.6/.git/
fatal: CRLF would be replaced by LF in dlltest.c.
Applying: Fix Makefiles and add support for Windows and OS X
.git/rebase-apply/patch:128: trailing whitespace.
 This Makefile builds a shared version of the library, 
.git/rebase-apply/patch:130: trailing whitespace.
 at least on x86-Linux (RedHat 7.2), 
.git/rebase-apply/patch:131: trailing whitespace.
 with gcc-2.96 20000731 (Red Hat Linux 7.1 2.96-98).  
.git/rebase-apply/patch:132: trailing whitespace.
 Please see the README file for some important info 
.git/rebase-apply/patch:142: trailing whitespace.
 Please read the WARNING, DISCLAIMER and PATENTS sections in the 
error: Makefile: does not exist in index
error: Makefile-libbz2_so: does not exist in index
error: bzip2.c: does not exist in index
Patch failed at 0001 Fix Makefiles and add support for Windows and OS X
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Running command 'rm -rf /home/eugene/cerbero/sources/linux_x86_64/bzip2-1.0.6'
Running command 'mkdir -p /home/eugene/cerbero/sources/linux_x86_64/bzip2-1.0.6'
Running command 'git init'
Running command 'git add --force -A .'
Running command 'git am --ignore-whitespace /home/eugene/cerbero/recipes/bzip2/0001-Fix-Makefiles-and-add-support-for-Windows-and-OS-X.patch'

Recipe 'bzip2' failed at the build step 'extract'

**Comment by stefanalund** [comment]
@sdroege any ideas?

**Comment by sdroege** [comment]
Yes, complain to your OS' manufacturer and switch to something usable. That's the problem here that you can see from the screenshot: https://twitter.com/kern/status/657994294029103104

**Comment by sdroege** [comment]
Actually wrong bug, sorry! Can you upload the /home/eugene/cerbero/sources/local/bzip2-1.0.6/bzip2-1.0.6.tar.gz somewhere?

**Comment by NSky** [comment]
I'm sure the problem is not in the sources tarball but in the build environment.
I can't upload bzip2 now as I deleted the folder. But the same error happens to zlib. I tried to do a fresh build from scratch with the result below.
At first building attempt I got the same problem. I unpacked zlib, applied pathes manually then packed it back and removed patches from recipe. That allowed build to go one step further. Then I did the same for glib etc... At the bzip2 stage I gave up:)

zlib tarball:
https://www.dropbox.com/sh/ybzwxcl8l5o42rz/AABVL3Zk9LevtGUQFiIwBFAYa?dl=0


[(10/14) zlib -> fetch ]
-----> Fetching tarball http://zlib.net/zlib-1.2.8.tar.xz to /home/eugene/cerbero/sources/local/zlib-1.2.8/zlib-1.2.8.tar.xz
[(10/14) zlib -> extract ]
-----> Extracting tarball to /home/eugene/cerbero/sources/build-tools/zlib-1.2.8
Unpacking /home/eugene/cerbero/sources/local/zlib-1.2.8/zlib-1.2.8.tar.xz in /home/eugene/cerbero/sources/build-tools
Initialized empty Git repository in /home/eugene/cerbero/sources/build-tools/zlib-1.2.8/.git/
fatal: CRLF would be replaced by LF in contrib/dotzlib/DotZLib.build.
Applying: win32: fix dll name
error: win32/Makefile.gcc: does not exist in index
Patch failed at 0001 win32: fix dll name
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Running command 'tar -Jxf /home/eugene/cerbero/sources/local/zlib-1.2.8/zlib-1.2.8.tar.xz'
Running command 'mkdir -p /home/eugene/cerbero/sources/build-tools/zlib-1.2.8'
Running command 'git init'
Running command 'git add --force -A .'
Running command 'git am --ignore-whitespace /home/eugene/cerbero/recipes/zlib/0001-win32-fix-dll-name.patch'

Recipe 'zlib' failed at the build step 'extract'
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort

**Comment by sdroege** [comment]
Ah this might be relevant:  fatal: CRLF would be replaced by LF in contrib/dotzlib/DotZLib.build.

This sounds like something is wrong in your environment with line-endings. Maybe cerbero was checked out with Windows line-endings or something like that. Or in the global GIT config.

Did you configure core.autocrlf at some point in GIT? What's the output of "git config --get core.autocrlf" from inside the cerbero GIT repository?

**Comment by NSky** [comment]
It was "input". I set autocrlf=false and it's built fine. Thank you much!
