### ISSUE TITLE
Crashes after merge of Scream

### ISSUE THREAD

**Issue by stefhak** [EricssonResearch/openwebrtc#506]
Just tested, get the following error message:
$ openwebrtc-daemon
{"line":24,"column":32,"sourceURL":"/Users/eplhak/cerbero/dist/darwin_x86_64/share/seed-gtk3/extensions/Seed.js"}
**
ERROR:owr_transport_agent.c:1522:prepare_transport_bin_send_elements: assertion failed: (scream_queue)
Abort trap: 6

**Comment by ford-prefect** [comment]
That looks like you don't have the corresponding update to openwebrtc-gst-plugins (which now provides the screamqueue element).

**Comment by stefhak** [comment]
sounds probable - I'll update and test.

**Comment by stefhak** [comment]
I get the error:
"(gst-plugin-scanner:95989): GLib-GObject-WARNING **: cannot register existing type 'GstLiveAdder'

(gst-plugin-scanner:95989): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(gst-plugin-scanner:95989): GStreamer-CRITICAL **: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed"

This is certainly due to some mistake of mine, would appreciate input.

**Comment by ford-prefect** [comment]
I see these on gstreamer master. They shouldn't affect your build, though.
Does the owr build still not work?

**Comment by stefhak** [comment]
no, it does not. FYI, I followed the steps at https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC from "Update cerbero and the recipes" to update.

**Comment by ford-prefect** [comment]
Do you still get the assert about missing scream_queue or is the failure
elsewhere now?

**Comment by stefhak** [comment]
The error is elsewhere now. I run with the bridge, and the browser can't load owr.js (i.e. http://localhost:10717/owr.js). I assumed that was connected to those errors* Also noted that what is usually (when things work) output in the console, '{"line":24,"column":32,"sourceURL":"/Users/eplhak/cerbero/dist/darwin_x86_64/share/seed-gtk3/extensions/Seed.js"}' is not.

*Console output from "$ openwebrtc-daemon":
"(gst-plugin-scanner:137): GLib-GObject-WARNING **: cannot register existing type 'GstLiveAdder'

(gst-plugin-scanner:137): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(gst-plugin-scanner:137): GStreamer-CRITICAL **: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed"

**Comment by ford-prefect** [comment]
Doing a clean build of gst-plugins-bad and gst-plugins-bad-static should make those errors go away.

**Comment by superdump** [comment]
Also note that I merged upstream cerbero with OpenWebRTC cerbero last night.

**Comment by ford-prefect** [comment]
Yup, liveadder moved from its own plugin to audiomixer, so a not-cleaned-up build (make clean + make clean-cruft) would have two copies of the liveadder plugin generating an error that looks like that.

That said, the two-liveadder-elements critical shouldn't prevent things from working.

**Comment by stefhak** [comment]
$ history
537  ./cerbero-uninstalled -c config/osx-x86-64.cbc fetch-package --full-reset --reset-rdeps openwebrtc
  538  ./cerbero-uninstalled -c config/osx-x86-64.cbc bootstrap
  539  ./cerbero-uninstalled -c config/osx-x86-64.cbc package -f openwebrtc
  540  ./cerbero-uninstalled -c config/osx-x86-64.cbc buildone openwebrtc
  541  ./cerbero-uninstalled -c config/osx-x86-64.cbc package -f openwebrtc

"--full-reset --reset-rdeps" not sufficient?

$ find . -name "liveadder" ->
./sources/darwin_x86_64/gst-plugins-bad-1.0-static-1.5/gst/liveadder

**Comment by superdump** [comment]
With your desired cerbero configs...

buildone gst-plugins-bad-1.0
buildone gst-plugins-bad-static-1.0
buildone openwebrtc
package -f openwebrtc

I think.

**Comment by superdump** [comment]
Err, gst-plugins-bad-1.0-static perhaps. I never remember which way around those are. :)

**Comment by stefhak** [comment]
I tried that, but still got the error. What is worse, even after "rm -rf cerbero" and starting from scratch it does not work. 
I get one strange(?) warning when building package: WARNING: Some files required by this package are missing in the prefix:
lib/gstreamer-1.0/libgstscream.so

Unrelated?

**Comment by superdump** [comment]
After rebuilding from scratch with cerbero master and then hopping into a shell and trying to run test-send-receive, I saw the following:

```
0:00:00.004346000  9646 0x7f8601411460 WARN            GST_REGISTRY gstregistrybinary.c:489:gint gst_registry_binary_check_magic(gchar **, gsize): Binary registry magic version is different : 1.3.0 != 1.0.0
```

I fixed that by doing: `rm -rf ${GST_REGISTRY_1_0}` to remove the outdated GStreamer plugin registry.

Then I ran again and saw:

```
0:00:01.224318000 16448 0x7f97f18740a0 ERROR              glslstage gstglslstage.c:482:_compile_shader:<glslstage2> vertex shader compilation failed:ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:1: 'attribute' : syntax error: syntax error

0:00:01.224340000 16448 0x7f97f18740a0 ERROR                default gstglutils.c:398:_compile_shader:<glslstage2> vertex shader compilation failed:ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:1: 'attribute' : syntax error: syntax error
```

@sdroege , @ford-prefect : Any suggestions about that one?

**Comment by superdump** [comment]
I do see things like:

```
0:00:04.721467000 16448 0x7f97f3c17f30 INFO       owrtransportagent owr_transport_agent.c:1354:emit_bitrate_change: Updating bitrate to 307603 from 303018
0:00:04.786718000 16448 0x7f97f3002a80 INFO              owrsession owr_transport_agent.c:2877:print_rtcp_feedback_type:<RTPSession@0x7f97f487e3e0> Session 1, Received RTCP feedback for 2402180500: SCReAM
```

So SCReAM seems to be working.

**Comment by stefhak** [comment]
test-send-receive gives:

(gst-plugin-scanner:5351): GLib-GObject-WARNING **: cannot register existing type 'GstLiveAdder'

(gst-plugin-scanner:5351): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(gst-plugin-scanner:5351): GStreamer-CRITICAL **: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed
Displaying self-view
Got remote source: Remote audio stream
Creating audio renderer
Connecting source to audio renderer
0:00:03.346962000  5337 0x7fb00407b5e0 ERROR              glslstage gstglslstage.c:482:_compile_shader:<glslstage2> vertex shader compilation failed:ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:1: 'attribute' : syntax error: syntax error

0:00:03.347016000  5337 0x7fb00407b5e0 ERROR                default gstglutils.c:398:_compile_shader:<glslstage2> vertex shader compilation failed:ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:1: 'attribute' : syntax error: syntax error

==== Error message start ====
Error in element glcolorconvertelement0.
Error: Failed to convert video buffer
Debugging info: gstglcolorconvertelement.c(219): gst_gl_color_convert_element_prepare_output_buffer (): /GstPipeline:media-renderer-0/GstBin:video-renderer-bin-0/GstGLImageSinkBin:video-renderer-sink/GstGLColorConvertElement:glcolorconvertelement0
==== Error message stop ====
Got remote source: Remote video stream
Creating video renderer
Connecting source to video renderer
0:00:03.506357000  5337 0x7fb0038d3a30 ERROR              glslstage gstglslstage.c:482:_compile_shader:<glslstage5> vertex shader compilation failed:ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:1: 'attribute' : syntax error: syntax error

0:00:03.506390000  5337 0x7fb0038d3a30 ERROR                default gstglutils.c:398:_compile_shader:<glslstage5> vertex shader compilation failed:ERROR: 0:1: '' :  #version required and missing.
ERROR: 0:1: 'attribute' : syntax error: syntax error

==== Error message start ====
Error in element glcolorconvertelement1.
Error: Failed to convert video buffer
Debugging info: gstglcolorconvertelement.c(219): gst_gl_color_convert_element_prepare_output_buffer (): /GstPipeline:media-renderer-2/GstBin:video-renderer-bin-1/GstGLImageSinkBin:video-renderer-sink/GstGLColorConvertElement:glcolorconvertelement1
==== Error message stop ====
Dumping send transport agent pipeline!
==== Error message start ====
Error in element srtp-encoder.
Error: GStreamer encountered a general supporting library error.
Debugging info: gstsrtpenc.c(1058): gst_srtp_enc_process_buffer (): /GstPipeline:transport-agent-1/GstBin:transport_bin_1/GstBin:send-output-bin-1/GstDtlsSrtpEnc:dtls_srtp_rtcp_encoder_1/GstSrtpEnc:srtp-encoder:
Unable to protect buffer (protect failed) code 2
==== Error message stop ====
 *** ERROR *** 
origin=recv TransportAgent, type=processing-error
==== Error message start ====
Error in element srtp-encoder.
Error: GStreamer encountered a general supporting library error.
Debugging info: gstsrtpenc.c(1058): gst_srtp_enc_process_buffer (): /GstPipeline:transport-agent-1/GstBin:transport_bin_1/GstBin:send-output-bin-1/GstDtlsSrtpEnc:dtls_srtp_rtcp_encoder_1/GstSrtpEnc:srtp-encoder:
Unable to protect buffer (protect failed) code 2
==== Error message stop ====

**Comment by sdroege** [comment]
> After rebuilding from scratch with cerbero master and then hopping into a shell and trying to run test-send-receive, I saw the following:
> 
> 0:00:00.004346000  9646 0x7f8601411460 WARN            GST_REGISTRY gstregistrybinary.c:489:gint gst_registry_binary_check_magic(gchar **, gsize): Binary registry magic version is different : 1.3.0 != 1.0.0
> 
> I fixed that by doing: rm -rf ${GST_REGISTRY_1_0} to remove the outdated GStreamer plugin registry.

That's needed because of the addition of the tracer subsystem. The registry version changed, but as a result the registry should be automatically rebuild. You get this message and from then on it's all good. It wasn't for you?


> Then I ran again and saw:
> 
> 0:00:01.224318000 16448 0x7f97f18740a0 ERROR              glslstage gstglslstage.c:482:_compile_shader:<glslstage2> vertex shader compilation failed:ERROR: 0:1: '' :  #version required and missing.
> ERROR: 0:1: 'attribute' : syntax error: syntax error
> 
> 0:00:01.224340000 16448 0x7f97f18740a0 ERROR                default gstglutils.c:398:_compile_shader:<glslstage2> vertex shader compilation failed:ERROR: 0:1: '' :  #version required and missing.
> ERROR: 0:1: 'attribute' : syntax error: syntax error

That's probably some fallout of @ystreet 's shader refactoring recently, might even be fixed in a newer version now. @ystreet , any ideas on this one?


> (gst-plugin-scanner:5351): GLib-GObject-WARNING **: cannot register existing type 'GstLiveAdder' (gst-plugin-scanner:5351): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed (gst-plugin-scanner:5351): GStreamer-CRITICAL **: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed

@stefhak this means you have some old cruft lying around. A lib/gstreamer-1.0/libgstliveadder.so somewhere. Please delete that :)

The other problems you're seeing are the same as @superdump sees. Mostly the GL shader issue, Linux/mesa is IIRC a bit more forgiving with not 100% compliant shaders, but I thought we had code to inject #version into shaders as needed. Maybe missing in a single case now, @ystreet will know :)

**Comment by alessandrod** [comment]
On Mon, Nov 2, 2015 at 6:06 AM Sebastian Dröge <notifications@github.com>
wrote:

> Then I ran again and saw:
>
> 0:00:01.224318000 16448 0x7f97f18740a0 ERROR glslstage
> gstglslstage.c:482:_compile_shader: vertex shader compilation failed:ERROR:
> 0:1: '' : #version required and missing.
>
>
> ERROR: 0:1: 'attribute' : syntax error: syntax error
>
> 0:00:01.224340000 16448 0x7f97f18740a0 ERROR default
> gstglutils.c:398:_compile_shader: vertex shader compilation failed:ERROR:
> 0:1: '' : #version required and missing.
>
>
> ERROR: 0:1: 'attribute' : syntax error: syntax error
>
> That's probably some fallout of @ystreet <https://github.com/ystreet> 's
> shader refactoring recently, might even be fixed in a newer version now.
> @ystreet <https://github.com/ystreet> , any ideas on this one?
>
I ran into this too and it's now fixed in gst-plugins-bad master

**Comment by superdump** [comment]
Excellent. I'll bump to master again then. Thanks!

**Comment by superdump** [comment]
I've just bumped all the gst repos to master in cerbero. I'll retest when my build is done.

**Comment by stefhak** [comment]
I rebuilt. Now test-send-recive works! However, ```~/cerbero$ openwebrtc-daemon```still gives
```
(gst-plugin-scanner:613): GLib-GObject-WARNING **: cannot register existing type 'GstLiveAdder'

(gst-plugin-scanner:613): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(gst-plugin-scanner:613): GStreamer-CRITICAL **: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed
```
and the daemon does not work as intended.
I did (embarrassment) find liveadder at a completely different location in my system, but removed before rebuilding after applying Rob's bump. ```find```now returns no liveadder at all.
I have no idea what the reason is...

**Comment by sdroege** [comment]
@stefhak See my comment above, liveadder is gone in git master and if you have a libgstliveradder.* file lying around somewhere you should remove it.

**Comment by stefhak** [comment]
@sdroege this is embarrassing, I found two more liveadder files. After removing them all works as intended. Thanks all for all help in this thread!

**Comment by superdump** [comment]
The GL errors are gone for me too now. Closing.
