### ISSUE TITLE
Something's fishy with ICE 

### ISSUE THREAD

**Issue by stefhak** [EricssonResearch/openwebrtc#510]
See https://github.com/EricssonResearch/bowser/issues/63; owr - owr, or Bowser - owr, outputs a lot of errors in the log seemingly related to ICE and there is (at best) one way video.

**Comment by stefanalund** [comment]
@alessandrod has been working on this lately. Maybe he knows more.

**Comment by bamboolsu** [comment]
Maybe Issue #359 is related this issue. anybody has some ideas.

#359, #504 and this issue #510, all this issues is big problems, and If we want  product to use our openwebrtc, we should fix all this base problems.

**Comment by superdump** [comment]
We are very aware of these issues and are working on them.

**Comment by alessandrod** [comment]
Some changes were committed recenty to gst-plugins-bad which improved OWR <-> OWR significantly. 

As far as I can tell the following is the only error left, which doesn't seem to be fatal:

==== Error message start ====
Error in element srtp-encoder.
Error: GStreamer encountered a general supporting library error.
Debugging info: gstsrtpenc.c(1058): gst_srtp_enc_process_buffer (): /GstPipeline:transport-agent-1/GstBin:transport_bin_1/GstBin:send-output-bin-1/GstDtlsSrtpEnc:dtls_srtp_rtcp_encoder_1/GstSrtpEnc:srtp-encoder:
Unable to protect buffer (protect failed) code 2
==== Error message stop ====

I get this one when doing NativeDemo <=> Safari (OWR), no matter which side initiates the call. I always get video in both directions.

**Comment by alessandrod** [comment]
> ==== Error message start ====
> Error in element srtp-encoder.
> Error: GStreamer encountered a general supporting library error.
> Debugging info: gstsrtpenc.c(1058): gst_srtp_enc_process_buffer (): /GstPipeline:transport-agent-1/GstBin:transport_bin_1/GstBin:send-output-bin-1/GstDtlsSrtpEnc:dtls_srtp_rtcp_encoder_1/GstSrtpEnc:srtp-encoder:
> Unable to protect buffer (protect failed) code 2
> ==== Error message stop ====

I just pushed a commit in gst-plugins-good (http://cgit.freedesktop.org/gstreamer/gst-plugins-good/commit/?id=dd4df554d5c2d4a61d09e7ec7ab5844d126474a9) which fixes this. Now I don't get any more warnings \o/

**Comment by superdump** [comment]
\o/ I'll bump gst.

**Comment by stefanalund** [comment]
@superdump let's make a new pod release with this fix.

@alessandrod can we close this issue then?

**Comment by superdump** [comment]
@stefanalund - I'll get on it

**Comment by stefhak** [comment]
I checked out the latest stuff and tested - and now things work nicely owr <-> owr. Thanks a lot!
