### ISSUE TITLE
False assertion in on_new_selected_pair when doing data channels?

### ISSUE THREAD

**Issue by NCommander** [EricssonResearch/openwebrtc#516]
I'm currently working on getting a data channel between Chrome and native code going. I've successfully gotten the DTLS handshake to complete, but I get these assertions as the channel tries to come up. Looking at https://github.com/EricssonResearch/openwebrtc/blob/master/transport/owr_transport_agent.c#L1990, this should work just fine for data sessions (we only have RTP components, not RTCP, but the code handles it). I think this assertion needs to be changed to IS_SESSION, vs. IS_MEDIA_SESSION.

** (webrtc_dispatcher:26842): CRITICAL **: on_new_selected_pair: assertion 'OWR_IS_MEDIA_SESSION(session)' failed

** (webrtc_dispatcher:26842): CRITICAL **: on_new_selected_pair: assertion 'OWR_IS_MEDIA_SESSION(session)' failed

**Comment by NCommander** [comment]
One line charge, but I provided a pull request that fixes this, and appears to work.

**Comment by stefanalund** [comment]
PR landed. Thanks.
