### ISSUE TITLE
Android packaging fails with missing libgstscream.so

### ISSUE THREAD

**Issue by superdump** [EricssonResearch/openwebrtc#520]
```
-----> Creating package openwebrtc-base 
***** Error running 'package' command:
The following files required by this package are missing:
 lib/gstreamer-1.0/libgstscream.so
```

I don't really understand why this is so as:

https://github.com/EricssonResearch/cerbero/blob/master/recipes/openwebrtc-gst-plugins.recipe#L50

and

https://github.com/EricssonResearch/cerbero/blob/master/recipes/openwebrtc-gst-plugins-static.recipe#L46

and

https://github.com/EricssonResearch/cerbero/blob/master/packages/openwebrtc-base.package#L43

**Comment by sdroege** [comment]
@superdump this is fixed now as discussed on IRC by fixing the Makefile.am, right?
