### ISSUE TITLE
[wiki] fix link for Simple Camera Test

### ISSUE THREAD

**Issue by pietrushnic** [EricssonResearch/openwebrtc#529]
WebRTC samples are no longer on `http://googlechrome.github.io`. Content was moved to `https://webrtc.github.io`.

Fix can be found [here](https://github.com/pietrushnic/openwebrtc-wiki/commit/8150e7f434507c9b3e0d83662ffb24d3fec01641)

**Comment by stefanalund** [comment]
Fixed now, thanks!
