### ISSUE TITLE
Build openwebrtc-0.3.0-android-sources failed in last step

### ISSUE THREAD

**Issue by gghome** [EricssonResearch/openwebrtc#544]
Hi,I compile it on Ubuntu14.0. But I always failed at last step.Have someone can help me solve this problem.Thanks for your warmly help.Thanks.

[(29/35) icu -> already built ]
[(30/35) javascriptcoregtk -> already built ]
[(31/35) seed -> already built ]
[(32/35) libusrsctp -> already built ]
[(33/35) openwebrtc-gst-plugins -> already built ]
[(34/35) openwebrtc-gst-plugins-static -> already built ]
[(35/35) openwebrtc -> fetch ]
-----> Step done
[(35/35) openwebrtc -> extract ]
-----> Step done
[(35/35) openwebrtc -> configure ]
host_prefix=/home/cj/cerbero/dist/android_armv7/../linux_x86_64
gir_file_path=/home/cj/cerbero/dist/android_armv7/../linux_x86_64/share/gir-1.0
gir_file=Owr-0.3.gir
Recipe 'openwebrtc' failed at the build step 'configure'
Traceback (most recent call last):
  File "./cerbero/build/oven.py", line 143, in _cook_recipe
    stepfunc()
  File "/home/cj/cerbero/recipes/openwebrtc.recipe", line 193, in configure
    raise Exception(err_nobuild)
Exception: You need to build openwebrtc for the host linux before you can cross-compile it for android
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort

**Comment by superdump** [comment]
Note in the output: `Exception: You need to build openwebrtc for the host linux before you can cross-compile it for android`

**Comment by gghome** [comment]
I had compile by those steps,but still failed.
sudo mkdir -p /opt/openwebrtc-0.3
sudo chown -R $UID /opt/openwebrtc-0.3

cd ~/cerbero \
&& ./cerbero-uninstalled -c config/linux.cbc fetch-package --full-reset --reset-rdeps openwebrtc \
&& ./cerbero-uninstalled -c config/linux.cbc bootstrap \
&& ./cerbero-uninstalled -c config/linux.cbc package -f openwebrtc

I meet error, no dir /opt/openwebrtc-1.0 ,then I build it;or change /cerbero/config/linux.cbc..
Then I succesfully build linux version.

After This, I build android version.
cd ~/cerbero \
&& ./cerbero-uninstalled -c config/cross-android-armv7.cbc fetch-package --full-reset --reset-rdeps openwebrtc \
&& ./cerbero-uninstalled -c config/cross-android-armv7.cbc bootstrap \
&& ./cerbero-uninstalled -c config/cross-android-armv7.cbc package -f openwebrtc

At last, I failed in 35 step.

**Comment by gghome** [comment]
On Ubuntu, I know the method,what is "export PATH="$PATH:/home/username/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin", can build cross-compile envirionment.But how can I do in buildding openwebrtc, I start learn openwebrtc just few days.Please Help me solve this problem.Thanks.

**Comment by superdump** [comment]
>  I meet error, no dir /opt/openwebrtc-1.0 ,then I build it;or change /cerbero/config/linux.cbc..
Then I succesfully build linux version.

I don't understand. We don't use /opt/openwebrtc-1.0 .

It is important to follow the instructions exactly and not miss any steps. I would recommend removing cerbero and /opt/openwebrtc* and then follow the steps again.

**Comment by gghome** [comment]
what version do you use in site of "https://github.com/EricssonResearch/openwebrtc/releases" ?
openwebrtc-0.3.0-android-sources.tar.bz2 or
openwebrtc-0.3.0-linux-sources.tar.bz2

**Comment by gghome** [comment]
in openwebrtc-0.3.0-android-sources\cerbero\config\linux.cbc
import os
from cerbero.config import Platform, Architecture, Distro
packages_prefix = 'openwebrtc'
packager = 'OpenWebRTC <packages@openwebrtc.io>'
prefix = "/opt/openwebrtc-1.0"

# Uncomment to allow parallel builds
# allow_parallel_build = True

# Uncomment this to allow cross-building for another architecture
# target_arch = Architecture.X86_64

I download openwebrtc-0.3.0-android-sources.tar.bz2,then I compile it ,meet those problems.

**Comment by superdump** [comment]
Ah, OK. That must have been a bug. I would recommend cloning from master and building that instead.

**Comment by gghome** [comment]
Thanks for your warmly help, I success to get openwebrtc-android-armv7-0.3.0.zip
