### ISSUE TITLE
getUserMedia thru https not working

### ISSUE THREAD

**Issue by SteveWebs** [EricssonResearch/openwebrtc#549]
Bowser 0.6 downloaded from App store.

getUserMedia() works ok within HTTP but when accessing same code thru HTTPS getUserMedia() fails. Tested on two different servers with HTTP & HTTPS. No error thrown, camera and stream just cannot be accessed in HTTPS. Please fix this as HTTPS is preferred.

Device: iPad Air 2

```
// Code
var isMozilla = window.mozRTCPeerConnection && !window.webkitRTCPeerConnection;
if (isMozilla)
    getUserMedia = navigator.mozGetUserMedia;
else
    getUserMedia = navigator.webkitGetUserMedia;

window.onload = function () {
    getUserMedia({"audio": false, "video": true}, function (stream) {
        selfView.src = URL.createObjectURL(stream);
        localStream = stream;
    }, logError);
}

**Comment by stefanalund** [comment]
This seems to be a mixed origin issue caused by changes in iOS 9.x. @pererikb @adam-be @stefhak we need to start serving the local bridge script from secure websocket (or find a way to disable this check).

![screen shot 2016-01-21 at 09 41 47](https://cloud.githubusercontent.com/assets/190856/12475469/72f5ae78-c023-11e5-8974-e85334c8ef74.png)

**Comment by SteveWebs** [comment]
And as I may add to my original post; no websockets or any references to outside scripts was used in the test. Just inline Javascript to attach local stream to video element.

iPad Air 2 / iOS 9.0.1 / Bowser 0.6

**Comment by stefanalund** [comment]
@SteveWebs yes, but Bowser connects to a local websocket server on the device for communication between native and javascript land.

**Comment by stefhak** [comment]
@stefanalund yes, we should look into serving via a secure ws.

**Comment by stefanalund** [comment]
@adam-be @pererikb this is your domain. How difficult would that be?

**Comment by stefanalund** [comment]
This is the same problem as https://github.com/EricssonResearch/bowser/issues/72. I've done some digging and it seems that the TLS requirement introduced in iOS 9 breaks the JavaScript bridge (using a WebSocket from localhost). We need to support Secure WebSocket to make this work.

@adam-be @pererikb @stefhak I need your help here.

**Comment by stefanalund** [comment]
This has now been solved! https://github.com/EricssonResearch/bowser/issues/72#issuecomment-182390937
