### ISSUE TITLE
Openwebrtc Daemon in linux

### ISSUE THREAD

**Issue by SrujithPoondla** [EricssonResearch/openwebrtc#551]
How to run openwebrtc deamon in linux?

**Comment by stefanalund** [comment]
Instructions are here: https://github.com/EricssonResearch/openwebrtc/wiki/Running-and-Testing#step-2---running-the-daemon

**Comment by SrujithPoondla** [comment]
Using Ubuntu14.04. I am getting error like this

srujith@PC:~/cerbero/sources/linux_x86_64/openwebrtc-0.3.0/bridge$ ./openwebrtc-daemon

** (gst-plugin-scanner:29399): CRITICAL **: Couldn't g_module_open libpython. Reason: /usr/lib/libpython2.7.so: cannot open shared object file: No such file or directory
{"line":24,"column":32,"sourceURL":"/opt/openwebrtc-0.3/share/seed-gtk3/extensions/Seed.js"}

**Comment by SrujithPoondla** [comment]
issue resolved thanks for the help

**Comment by pavank1933** [comment]
Hi Srujith,

I am seeing the below line after running the command "openwebrtc-daemon". Its not even stating whether its the error or not. Hope you have previous experience in running openwebrtc in linux as the steps mentioned in the official blog. I did the same. Can you please help me out whether this message states the openwebrtc runnning or not-

```
[cerbero-linux-x86_64]:/core/cerbero# openwebrtc-daemon
{"line":24,"column":32,"sourceURL":"/opt/openwebrtc-0.3/share/seed-gtk3/extensions/Seed.js"}

```

**screenshot for the reference**
![open](https://cloud.githubusercontent.com/assets/17086076/26783176/7aa2803e-4a14-11e7-9852-de5ac4c3197e.PNG)
