### ISSUE TITLE
Using openWebrtc as a library for integrating with conference bridge, so that webrtc clients can communicate with the conference bridge

### ISSUE THREAD

**Issue by Nir-Riko** [EricssonResearch/openwebrtc#557]
Hello,

I need to implement a WebRTC gateway LIBRARY. The library will be used by an existing conference bridge. The intention is to provide WebRTC support (Websocket, ICE, STUN & DTLS) to the conference bridge.

Eventhough OpenWebRTC is a kind of client framework, I thought it is feasible to use OpenWebrtc  as a WEBRTC gateway library which serves for the above purpose?

Whether OpenWebRTC is suitable for this need? 
Regards,
Riko

**Comment by superdump** [comment]
You could probably do this with OpenWebRTC but it would require some modification. A better fit right now is probably the Kurento WebRTC endpoint. See http://www.kurento.org/

**Comment by Nir-Riko** [comment]
Thanks for the quick response. I need to run the conference bridge on top of this library, and I need to create an interface between openwebrtc and the conference bridge. Both JsSIP or any JSON over Websocket can be the webrtc clients.

What kind of modification we would require to use openwebrtc as a gateway?

**Comment by Nir-Riko** [comment]
Thanks for the quick response. I need to run the conference bridge on top
of this library, and I need to create an interface between openwebrtc and
the conference bridge. Both JsSIP or any JSON over Websocket can be the
webrtc clients.

What kind of modification we would require to use openwebrtc as a gateway?
