### ISSUE TITLE
To create webrtc support for existing sip.

### ISSUE THREAD

**Issue by ashwin-mk** [EricssonResearch/openwebrtc#560]
Is it possible to make the Openwebrtc to utilise any existing SIP only framework and provide the WebRTC support, by catering the essential like websocket, ice, to it.

**Comment by stefanalund** [comment]
Yes, you can use OpenWebRTC with any type of signalling protocol as long as you keep to the WebRTC offer/answer procedure, which basically means sending SDP's to one another.

**Comment by ashwin-mk** [comment]
Thank you @stefanalund ,
How could we use the openwebrtc stack to impliment as a module, which could play the role as a websocket server, to handle dtls-srtp handshake also to add/remove ice candidate information in sdp from webrtc clients.

**Comment by stefanalund** [comment]
@ashwin-mk that is a pretty broad question which makes it hard to answer. I think you should get going and ask more detailed questions along the way. You can find various example clients here:

https://github.com/EricssonResearch/openwebrtc-examples

**Comment by ashwin-mk** [comment]
We have JsSIP client on one end, other end is a SIP framework. For enabling webrtc support to the SIP framework, there needs to be a module in between that can handle webrtc clients and  communicate with SIP framework. Since the SIP framework does not provide support for ICE, DTLS-SRTP, the module should take care of the stuffs.  Also, the module should behave like a server, for handling different webrtc clients, and then send the messages to SIP framework. Can I use Openwebrtc stack for implementing this module?

**Comment by stefanalund** [comment]
I think that should be possible. If you are building a server-like solution, there are basic C examples such as this to start from: https://github.com/EricssonResearch/openwebrtc/blob/master/tests/test_client.c

**Comment by ashwin-mk** [comment]
Thank you. I have already gone through this application. Basically, JsSIP client is sending "SIP over Web-socket". So, for handling SIP over websocket packets, I need to add SIP over Websocket support to the sample test-client application and handle SIP messages. Any sample server application available to refer to?

**Comment by stefanalund** [comment]
@ashwin-mk as OpenWebRTC is primary a client-side framework we have not developed any sample applications for servers. Sorry.

**Comment by stefhak** [comment]
You might also be interested in looking into Kurento (which is server side
and WebRTC compliant).

**Comment by ashwin-mk** [comment]
Thank you. :)
We had gone thought the Kurento also, but as far in our case, we would be using the webrtc library with another server. The library behaves more or less like a client implmentation because for every sdp offer that we are getting from a client, we need to reply with an sdp answer, where the media information will be added by conference server and the ICE and finger print information will be added by the  webrtc library. The server kind of usage would be coming only for the Websocket connection for handling different webrtc clients.
