### ISSUE TITLE
can we extract the SRTP keys and send it to another library?

### ISSUE THREAD

**Issue by ashwin-mk** [EricssonResearch/openwebrtc#568]
We are using the OpenWebRTC libraries with another library which can take care of media. How could we make use of the OpenWebRTC to hande the DTLS handshakes, and provide the SRTP key to the media library, where the media would be handled. Also, we need to know how we would block the media handling in openwebrtc. I like to implement an interface library which can talk with openwebrtc and the exiting library. The interface library will be similar to the test_client application. In the test_client prespective, can we extract the SRTP keys and send it to another library?

**Comment by stefanalund** [comment]
@Rugvip knows best about SRTP handling.

**Comment by Rugvip** [comment]
It sounds like a quite low-level integration, so you'll probably be better of just using the DTLS elements in OpenWebRTC directly. They're available in [gst-plugins-bad](https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/ext/dtls).

And it's not possible to export the SRTP keys in OpenWebRTC, not without some ugly workaround.

**Comment by ashwin-mk** [comment]
Thank you for the response. 
I am not clear on this. 
"probably be better of just using the DTLS elements in OpenWebRTC directly"
Could you explain a bit more detail?

**Comment by Rugvip** [comment]
OpenWebRTC is built on top of GStreamer http://gstreamer.freedesktop.org/
The architecture of GStreamer lets you put together pipelines consisting of elements that process media as well as generic data. The DTLS elements used in OpenWebRTC are found in the dtls plugin inside gst-plugins-bad, and those could be used directly in your application.

**Comment by ashwin-mk** [comment]
Thank you. As per your reply, the DTLS functionality can be accessed from the application itself. Whether we can get the DTLS key in the application? 

We would like to know about the SRTP handling also. How to give the SRTP control to another module. Do you have suggestion on this?
We would like to know whether this is possible with openwebrtc?
