### ISSUE TITLE
setRotation does not working

### ISSUE THREAD

**Issue by nakyup** [EricssonResearch/openwebrtc#569]
I tested Android to Android  my phone and my device

openwebrtc commit 30ca989ff4237ebe17641e15fa9cb17c98bf11f9
VideoView  setRotation is working 

but commit 42619e3eb1ee542434eb332daaa210184b75c270
setRotaion 0 , 1, 2, 3  is same, not working

This remote view screen is displayed upside down.

**Comment by superdump** [comment]
It's probably a bug because of the GL changes. @alessandrod @ystreet ?

**Comment by alessandrod** [comment]
Thanks for spotting this. Fixed in -bad https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/commit/?id=effe1323105059cbd3380c97fc65a605a2120623

**Comment by superdump** [comment]
GStreamer versions have been bumped in cerbero, so you just need to follow the update process.
