### ISSUE TITLE
iOS 9.2.1 incompatibility

### ISSUE THREAD

**Issue by Duraiamuthan** [EricssonResearch/openwebrtc#571]
I have an app that uses OpenWebRTC I installed the app in iOS 8 it works very well.
But in iOS 9.2.1 the app is installed but its crashing upon launch.
I think the bug is due to OpenWebRTC **owr-bridge**

Herewith I have attached the necessary parts of crashlog 

**Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00000000000000e8
Triggered by Thread:  6**

Thread 6 name:  **owr-bridge-thread**
**Thread 6 Crashed**:
0   JavaScriptCore                	0x0000000185982f5c 0x1855a4000 + 4058972
1   JavaScriptCore                	0x0000000185982f50 0x1855a4000 + 4058960
2   JavaScriptCore                	0x00000001855ea098 0x1855a4000 + 286872
3   JavaScriptCore                	0x0000000185a2dd58 0x1855a4000 + 4758872
4   JavaScriptCore                	0x0000000185a2dd64 0x1855a4000 + 4758884
5   JavaScriptCore                	0x0000000185a27dd8 0x1855a4000 + 4734424
6   JavaScriptCore                	0x0000000185954bb8 0x1855a4000 + 3869624
7   JavaScriptCore                	0x00000001855d53e8 0x1855a4000 + 201704
8   JavaScriptCore                	0x000000018572d810 0x1855a4000 + 1611792
9   JavaScriptCore                	0x000000018597883c 0x1855a4000 + 4016188
10  MyAppNameSwift               	0x00000001005ada74 0x100004000 + 5937780
11  MyAppNameSwift               	0x00000001005ad930 0x100004000 + 5937456
12  MyAppNameSwift              	0x00000001002fc3e4 0x100004000 + 3113956
13  libsystem_pthread.dylib       	0x0000000181fbfb28 0x181fbc000 + 15144
14  libsystem_pthread.dylib       	0x0000000181fbfa8c 0x181fbc000 + 14988
15  libsystem_pthread.dylib       	0x0000000181fbd028 0x181fbc000 + 4136

You can find more info [here](http://stackoverflow.com/q/35457315/730807)

**Comment by Duraiamuthan** [comment]
Got the solution [here](http://stackoverflow.com/a/35499112/730807)

**Comment by stefanalund** [comment]
Good! Closing this then.
