### ISSUE TITLE
HTTPS Needed for Work in Google Chrome

### ISSUE THREAD

**Issue by tobiastromm** [EricssonResearch/openwebrtc#592]
Hi.

Its possible to add HTTPS support for the demo work at Google Chrome?

Thanks.

**Comment by stefhak** [comment]
Hi, are you referring to the example app, or what?
I think openwebrtc already supports https.

**Comment by tobiastromm** [comment]
Yes, I am talking about the example.

I am using it with some modifications.

**Comment by stefhak** [comment]
Then, could you please file an issue for openwebrtc-examples?

**Comment by tobiastromm** [comment]
Sorry, just see it. Thanks.
