### ISSUE TITLE
Build Error( ./build-all.sh -r linux android)

### ISSUE THREAD

**Issue by spmeone** [EricssonResearch/openwebrtc#61]
I tried to build openwebrtc following "Building OpenWebRTC".
But next message appears　after "./build-all.sh -r linux android".

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
x-androideabi/gst-plugins-good/tests/examples/rtp' に入ります
  CC       server_alsasrc_PCMA-server-alsasrc-PCMA.o
  CCLD     server-alsasrc-PCMA
  CC       client_PCMA-client-PCMA.o
/home/test/openwebrtc/scripts/dependencies/gst-plugins-good/tests/examples/rtp/client-PCMA.c: In function 'pad_added_cb':
/home/test/openwebrtc/scripts/dependencies/gst-plugins-good/tests/examples/rtp/client-PCMA.c:105:20: warning: variable 'lres' set but not used [-Wunused-but-set-variable]
   GstPadLinkReturn lres;
                    ^
/home/test/openwebrtc/scripts/dependencies/gst-plugins-good/tests/examples/rtp/client-PCMA.c: In function 'main':
/home/test/openwebrtc/scripts/dependencies/gst-plugins-good/tests/examples/rtp/client-PCMA.c:134:20: warning: variable 'lres' set but not used [-Wunused-but-set-variable]
   GstPadLinkReturn lres;
                    ^
/home/test/openwebrtc/scripts/dependencies/gst-plugins-good/tests/examples/rtp/client-PCMA.c:133:12: warning: variable 'res' set but not used [-Wunused-but-set-variable]
   gboolean res;
            ^
  CCLD     client-PCMA
  CC       client_rtpaux-client-rtpaux.o
  CCLD     client-rtpaux
  CC       server_rtpaux-server-rtpaux.o
  CCLD     server-rtpaux
make[4]: ディレクトリ `/home/test/openwebrtc/scripts/dependencies/build/arm-linux-androideabi/gst-plugins-good/tests/examples/rtp' から出ます
make -C shapewipe
make[4]: ディレクトリ `/home/test/openwebrtc/scripts/dependencies/build/arm-linux-androideabi/gst-plugins-good/tests/examples/shapewipe' に入ります
  CC       shapewipe_example-shapewipe-example.o
  CCLD     shapewipe-example
collect2: error: ld returned 1 exit status
make[4]: *** [shapewipe-example] エラー 1
make[4]: ディレクトリ `/home/test/openwebrtc/scripts/dependencies/build/arm-linux-androideabi/gst-plugins-good/tests/examples/shapewipe' から出ます
make[3]: *** [shapewipe] エラー 2
make[3]: ディレクトリ `/home/test/openwebrtc/scripts/dependencies/build/arm-linux-androideabi/gst-plugins-good/tests/examples' から出ます
make[2]: *** [all-recursive] エラー 1
make[2]: ディレクトリ `/home/test/openwebrtc/scripts/dependencies/build/arm-linux-androideabi/gst-plugins-good/tests' から出ます
make[1]: *** [all-recursive] エラー 1
make[1]: ディレクトリ `/home/test/openwebrtc/scripts/dependencies/build/arm-linux-androideabi/gst-plugins-good' から出ます
make: *** [all] エラー 2
Failed building...gst-plugins-good
mv gst-plugins-good gst-plugins-good_build_failed_on_141026-10:41:29_using_script_with_md5sum_02d8fad0dfeb41512490590c392f5a4aabe22771

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Do you know  solutions.?

**Comment by superdump** [comment]
Any response about this problem? Lots of updates have happened since the issue was posted.

**Comment by superdump** [comment]
We have moved to cerbero as our build system. Please try building using that.

https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

Closing.
