### ISSUE TITLE
Make offer generated by "createOffer" spec compliant

### ISSUE THREAD

**Issue by stefhak** [EricssonResearch/openwebrtc#62]
Offers generated now miss ICE-ufrag and password as well as DTLS fingerprint, meaning they can't be sent to the other side (you have to do setLocal and fetch the local config and send that one).

According to the spec you should be able to send the offer generated by createOffer (it should be complete with ufrag, pw and fingerprint). We should fix this.

**Comment by ajohnson23** [comment]
It has been a few more months, any more word on this?

**Comment by stefanalund** [comment]
@adam-be @pererikb would you like to comment?

**Comment by stefhak** [comment]
I think an update to libnice is needed. I don't know if anyone looked into
that.

**Comment by stefanalund** [comment]
Maybe Olivier Crete knows. Describe the issue in an email an I can forward it.

**Comment by stefhak** [comment]
I asked on the libnice list: http://lists.freedesktop.org/archives/nice/2015-February/001072.html
Olivier has already responded, and I'm trying to gather info to be able to make a reasonable response. Please chime in if you have anything to add!

**Comment by szimek** [comment]
I'm not sure if it's related, but I'm trying out data channels in OpenWebRTC and Chrome complains about ICE candidates sent by Safari. Safari sends e.g. something like this:
```javascript
{
  "candidate": "candidate:2 1 TCP 1019216383 fe80::4a0:1bff:fe63:21f7 9 typ host tcptype active",
  "sdpMLineIndex":0,
  "sdpMid":""
}
```
and when Chrome tries to add such candidate:
```javascript
connection.addIceCandidate(new RTCIceCandidate({
  sdpMLineIndex: sdpMLineIndex,
  candidate: candidate
}));
```
I'm getting an error: `Failed to execute 'addIceCandidate' on 'RTCPeerConnection': The ICE candidate could not be added.`

**Comment by ijsf** [comment]
Somebody submitted a patch on the libnice list, see link above.

**Comment by dborovik** [comment]
Current (from App store) version of Bowser run on IPhone6.
Offer does not contain DTLS fingerpring:
 
sdp: "v=0
o=- 1427208527661020400 1 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic:WMS 2iQLycjj5ZgOpXY3ztfUxCpNiQ0vltk1gg5P
m=audio 1 RTP/SAVPF 111 8 0
c=IN IP4 0.0.0.0
a=rtcp-mux
a=sendrecv
a=rtpmap:111 OPUS/48000/2
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=msid:2iQLycjj5ZgOpXY3ztfUxCpNiQ0vltk1gg5P NjgqaQfdGpUz8Wvk2EVOSGM8Y1VZTZGAfNfK
a=setup:actpass
m=video 1 RTP/SAVPF 103 100 120
c=IN IP4 0.0.0.0
a=rtcp-mux
a=sendrecv
a=rtpmap:103 H264/90000
a=rtpmap:100 VP8/90000
a=rtpmap:120 RTX/90000
a=fmtp:103 packetization-mode=1
a=fmtp:120 apt=100;rtx-time=200
a=rtcp-fb:100 nack
a=rtcp-fb:103 nack pli
a=rtcp-fb:100 nack pli
a=rtcp-fb:103 ccm fir
a=rtcp-fb:100 ccm fir
a=msid:2iQLycjj5ZgOpXY3ztfUxCpNiQ0vltk1gg5P 1egNvfTh3Mlq0EeJvGljCjNjxUP1Ix9M645B
a=setup:actpass
"

**Comment by superdump** [comment]
Now being tracked here: https://bugs.freedesktop.org/show_bug.cgi?id=89839

**Comment by stefhak** [comment]
Follow up: the freedesktop bug is part of the problem, but there is more to it (e.g. the offer created should contain ssrc info, mid, ....)

**Comment by Zalmoxisus** [comment]
Any update of this issue? I see that the bug from freedesktop was fixed.

Just tested in Safari (with owr) and the following offer is generated:
m=video 1 RTP/SAVPF 100
↵c=IN IP4 0.0.0.0
↵a=sendrecv
↵a=rtpmap:100 VP8/90000
↵a=rtcp-fb:100 nack
↵a=rtcp-fb:100 ccm fir
↵a=msid:MlIIetGUkwgXOAJwDZDJRcQatW3xnr0Bi9lA 4UTGksHhkDIUdsgcHQw9g+c4M1QaKWmBbQg3
↵a=setup:active

While in chrome the offer is:
m=video 9 RTP/SAVPF 100 116 117
↵c=IN IP4 0.0.0.0
↵a=rtcp:9 IN IP4 0.0.0.0
↵a=ice-ufrag:k0QA2sdLpdu5mCLM
↵a=ice-pwd:EjnDQZlWo8dWLdi76VkbRfc3
↵a=fingerprint:sha-256 78:09:3D:DB:AF:D3:CC:D1:FA:3A:81:5A:0D:B5:B3:66:39:90:E4:56:07:D3:D6:C4:58:9B:89:1C:FA:04:5F:07
↵a=setup:active
↵a=mid:video
↵a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
↵a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
↵a=sendrecv
↵a=rtpmap:100 VP8/90000
↵a=rtcp-fb:100 ccm fir
↵a=rtcp-fb:100 nack
↵a=rtcp-fb:100 goog-remb
↵a=rtpmap:116 red/90000
↵a=rtpmap:117 ulpfec/90000
↵a=ssrc:1181138693 cname:lkjR0pUPXzMtQOOT
↵a=ssrc:1181138693 msid:664a6a7c-77fb-4050-9410-7cd05c48ad2c 85f02b9e-642a-4944-b99c-938691c8ae84
↵a=ssrc:1181138693 mslabel:664a6a7c-77fb-4050-9410-7cd05c48ad2c
↵a=ssrc:1181138693 label:85f02b9e-642a-4944-b99c-938691c8ae84

We need at least ICE-ufrag and password.

**Comment by superdump** [comment]
@stefhak - if we update libnice to pull in the _set_local_credentials patch, do you think you can implement the remaining parts in OpenWebRTC?

**Comment by stefhak** [comment]
With some help I think I could manage that.

**Comment by superdump** [comment]
Then I'll look into updating libnice after the release tomorrow.

**Comment by superdump** [comment]
@stefhak, libnice is updated in cerbero to 0.1.12 which includes the _set_local_credentials API.

**Comment by superdump** [comment]
@stefhak any luck with this?

**Comment by stefhak** [comment]
I have not done anything yet. Promise to get to it next week.

**Comment by stefhak** [comment]
So after some discussions with people who know stuff, we've concluded that a possible way forward is to divide this into the following parts (all of which are needed to make the offer spec compliant):
* [ ] make ssrc and cname properties writable
* [ ] create binding between all local candidates (so ufrag and password are consistent even if changed on one of them) - add a dummy candidate to be used as "master"
* [ ] call nice_agent_set_local_credentials with ufrag and password of candidates
* [ ] set dtls-certificate and dtls-key properties on OwrSession with values from offer/answer created
* [ ] generate ufrag and password in JS when doing createOffer - and add to dummy candidate
* [ ] generate certificate for dtls in JS ofr createOffer/Answer

**Comment by superdump** [comment]
SSRC should be set in the capsfilter caps after the RTP payloader.

cname can be set on the internal RTPSession's sdes property. That property is a GstStructure which has key=value fields as follows: http://cgit.freedesktop.org/gstreamer/gst-plugins-good/tree/gst/rtpmanager/rtpsource.c#n99  When requesting a new pad on rtpbin, the RTPSource and RTPSession will be created. After that, you can use the get-internal-session action signal ( http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good-plugins/html/gst-plugins-good-plugins-rtpbin.html#GstRtpBin-get-internal-session ) to get the RTPSession object and then create the appropriate SDES GstStructure and set it on the RTPSession. If the cname is the same for all sessions, the structure can be set on the rtpbin sdes property.

**Comment by superdump** [comment]
https://github.com/EricssonResearch/openwebrtc/pull/398

**Comment by superdump** [comment]
So, I think we need an rtx-ssrc property somewhere and then we need to correctly handle the ssrc-map signal from rtprtxsend and rtprtxreceive to map the payload types to ssrcs.

**Comment by superdump** [comment]
@pererikb has implemented and tested the credentials handling parts: https://github.com/EricssonResearch/openwebrtc/pull/400

**Comment by sdroege** [comment]
@superdump, see the ssrc-map property on rtprtxsend.

**Comment by stefanalund** [comment]
Done https://github.com/EricssonResearch/openwebrtc/pull/427

**Comment by superdump** [comment]
I think the only part remaining is to check and fix is the RTX SSRC bit.

**Comment by stefanalund** [comment]
Should we reopen or create a separate, new, issue?

**Comment by superdump** [comment]
I'll reopen this as the information is above.

**Comment by stefhak** [comment]
We can do that, but I think being able to set MID has higher prio.

**Comment by superdump** [comment]
@stefhak: do you have any list of compliance issues?

**Comment by stefhak** [comment]
I'll work on one.

**Comment by superdump** [comment]
OK, I've changed my mind. I think we can close this and consider the original issue with createOffer compliance completed. The RTX stuff can be added later.

See here: https://github.com/EricssonResearch/openwebrtc/issues/492
