### ISSUE TITLE
./build-all.sh -r OS X - build failed

### ISSUE THREAD

**Issue by josipbernat** [EricssonResearch/openwebrtc#67]
Hi,

I get following error when I try to build library for OS X or OS X + iOS. Do you know what may be a problem?

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C gaudieffects
  ORCC   tmp-orc.c
In function gaudi_orc_burn:
error: line 13: too many arguments for copyb (expected 2)
error: line 14: too many arguments for convubw (expected 2)
error: line 16: too many arguments for addw (expected 3)
error: line 17: too many arguments for shruw (expected 3)
error: line 18: too many arguments for subb (expected 3)
error: line 20: too many arguments for convubw (expected 2)
error: line 21: too many arguments for shlw (expected 3)
error: line 22: too many arguments for divluw (expected 3)
error: line 23: too many arguments for subw (expected 3)
error: line 25: too many arguments for convwb (expected 2)
error: variable "(null)" used before being written
error: variable "(null)" used before being written
error: variable "(null)" used before being written
error: variable "(null)" used before being written
error: variable "(null)" used before being written
error: variable "(null)" used before being written
Failed to compile gaudi_orc_burn
Failed to compile gaudi_orc_burn
make[3]: *** [tmp-orc.c] Error 1
make[2]: *** [gaudieffects] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Failed building...gst-plugins-bad
mv gst-plugins-bad gst-plugins-bad_build_failed_on_141029-17:05:13_using_script_with_md5sum_20ecfbb538434fca0b850642721d81d14e2d22b0

**Comment by superdump** [comment]
Please retest with current master and reopen if the issue still occurs.
