### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by Fuzzyma** [EricssonResearch/openwebrtc#689]
I stumbled across openwebrtc because I searched for an webrtc client which I could use on the server. However, it seems like this project is not maintained anymore. The last update was two month ago and there are over 200 open issues around.

So could one of the maintainer @sdroege @superdump @Rugvip @ford-prefect @pererikb make a statement about further developmnet of this library?

**Comment by miminashi** [comment]
+1

**Comment by zhumeiteng** [comment]
anything is not OK

**Comment by pererikb** [comment]
The project is not under active development right now but it is still being used so I would not consider it dead. We have limited time to help out with build problems and debugging, which is why there are many open issues. We still encourage people to fix bugs and send pull requests.

**Comment by sdroege** [comment]
The parts of this project that were merged into GStreamer are also still actively used and maintained and used by other projects for implementing WebRTC (and other things), but I'm not working on OpenWebRTC anymore.
