### ISSUE TITLE
I am interested in taking ownership of this project

### ISSUE THREAD

**Issue by BloggerBust** [EricssonResearch/openwebrtc#710]
Since this project is no longer being maintained I am interested in taking ownership. Is that a possibility?

**Comment by sdroege** [comment]
GStreamer has WebRTC support integrated since version 1.14. Check https://gstreamer.freedesktop.org/releases/1.14/ for details.
That kind of obsoletes this project.

**Comment by BloggerBust** [comment]
Thank you,

I will read up on GStreamer to see how well it satisfies my needs.
