### ISSUE TITLE
Corrupted tar file in icu dependency

### ISSUE THREAD

**Issue by warrenjmcdonald** [EricssonResearch/openwebrtc#76]
I am getting consistent error in building dependencies for osx just after cleaning and download in icu.

File shows as 100% and 354 received but tar throws "Unrecognised archive format"
This is truncated icu4c-53_1-src.tgz 354 bytes instead of 22MB 

Stepping over re instructions for splitting dependencies builds.
Will alert source repo

**Comment by superdump** [comment]
I have not seen any issues with icu downloading in months. Closing.
