### ISSUE TITLE
Framerate slows down

### ISSUE THREAD

**Issue by stefanalund** [EricssonResearch/openwebrtc#96]
Video frame rate on iOS slows down in bad lighting conditions.

**Comment by stefanalund** [comment]
@alessandrod found anything interesting?

**Comment by superdump** [comment]
@stefanalund - I think everything was committed to GStreamer master before the holidays. I'm in the process of rebuilding everything from current master including bumping to GStreamer master as of this morning. I'll see how it looks after I've done that and report back.

**Comment by superdump** [comment]
Looks good now. Slow downs in frame rate that I notice are due to poor lighting (particularly with front-facing) or autofocus. Otherwise (good lighting, no need to refocus) I observe a pretty solid frame rate.

**Comment by stefanalund** [comment]
Lighting conditions still greatly influences fps. May be a problem in the GStreamer plugin.

**Comment by superdump** [comment]
It's worth noting that the framerate issues are not present in other applications using the camera. Ways to reproduce:

Cover the camera. Start the iOS selfie app. Uncover the camera. Particularly on older devices (pre-iPad Air for example), the frames displayed are black and either don't recover at all or take a very long time (30s or more) to return to a normal white balance / exposure / frame rate.

Alternatively, start the iOS Selfie app, cover the camera and then uncover it.

**Comment by sdroege** [comment]
Maybe there's a mode on the camera where it tries less to compensate for bad lightning conditions and just outputs things faster

**Comment by richardmitic** [comment]
There are properties of AVCaptureSource that let you set the maximum frame duration, although they might not be available in all the SDKs that the applemedia plugin supports. https://bugzilla.gnome.org/show_bug.cgi?id=711211

**Comment by sdroege** [comment]
This API is already used when available, but there might be a bug around that code.

**Comment by alessandrod** [comment]
We're negotiating the framerate correctly, but then we're also setting stuff like auto frame drop and auto focus could be causing this. I'll take a closer look once i'm done with texture sharing between AVF <=> glimagesink.

**Comment by sdroege** [comment]
@alessandrod any progress here?

**Comment by superdump** [comment]
@alessandrod - ping?

**Comment by stefanalund** [comment]
IIRC @sdroege said it was fixed in a later GStreamer.

**Comment by sdroege** [comment]
Not this bug, no.

**Comment by ijsf** [comment]
Definitely looks like a duplicate of #243.

**Comment by stefanalund** [comment]
Duplicate of https://github.com/EricssonResearch/openwebrtc/issues/243, closing.
