### ISSUE TITLE
Build for linux fails with "No package 'libpulse' found"

### ISSUE THREAD

**Issue by vgottardi** [EricssonResearch/openwebrtc#97]
Linux build requires libpulse (configure.ca line 90). Do we need a build-libpulse.sh in scripts/dependencies?

**Comment by jiyeyuran** [comment]
When this problem can be fixed? Compiling all dependencies is time-consuming, and ubuntu already have most of the dependencies.

**Comment by river9100** [comment]
I'm also met this problem. how can I do?

checking whether to build static owr or not... yes
checking for PULSE... no
configure: error: Package requirements (libpulse libpulse-mainloop-glib) were not met:

No package 'libpulse' found
No package 'libpulse-mainloop-glib' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables PULSE_CFLAGS
and PULSE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
configure failed

**Comment by river9100** [comment]
My environment: Ubuntu 14.04 x64 TLS.
bootstrap and dependencies all built well.

**Comment by superdump** [comment]
I'll put up some patches that fix this soon. Sorry for the delay.

**Comment by superdump** [comment]
So this is kind of hacky, but it works for me on Ubuntu at least. I haven't had time to find a better way. Does it work for you? https://github.com/superdump/openwebrtc/commit/c7ec41870f0e031279ec1345c8ade697c05b8321

**Comment by vgottardi** [comment]
Thanks for the fix. It works through the libpulse problem but I now hit another link problem. 
```
make[2]: Entering directory `/home/dev/openwebrtc/build/x86_64-unknown-linux/owr'
  CCLD     libopenwebrtc.la
/usr/bin/ld: cannot find -lgstopengl
/usr/bin/ld: cannot find -lgstgl-1.0
collect2: error: ld returned 1 exit status
make[2]: *** [libopenwebrtc.la] Error 1
```
It's not obvious where to get the missing libraries. Any suggestion?

**Comment by superdump** [comment]
`sudo apt-get install libegl1-Mesa-dev` I think. I will push up a patch that adds this and ruby to bootstrap.sh soon.

**Comment by superdump** [comment]
Lower case m there

**Comment by vgottardi** [comment]
I installed libegl1-mesa-dev but it didn't resolve the problem. I was thinking I have to rebuild the gst-plugins-bad in dependencies. I did that, but "gl" stayed in the "Plug-ins with dependencies that will NOT be built" category. Am I on the right path? Here's what I get when I run build-gst-plugins-bad.sh:
```
...
checking for X... no
configure: No package 'x11' found
checking for glTexImage2D in -lGL... yes
checking GL/gl.h usability... yes
checking GL/gl.h presence... yes
checking for GL/gl.h... yes
checking for glTexImage2D in -lGLESv2... no
checking for eglGetError in -lEGL... yes
checking EGL/egl.h usability... yes
checking EGL/egl.h presence... yes
checking for EGL/egl.h... yes
checking EGL/fbdev_window.h usability... no
checking EGL/fbdev_window.h presence... no
checking for EGL/fbdev_window.h... no
checking for bcm_host_init in -lbcm_host... no
checking for WAYLAND_EGL... no
host is x86_64-unknown-linux-gnu
configure: WARNING: X or Wayland is required for OpenGL support
configure: WARNING: Either OpenGL or OpenGL|ES is required for OpenGL support
configure: WARNING: Could not find any OpenGL platforms to use such as CGL, WGL or GLX
configure: WARNING: Could not find any window systems to use such as Cocoa, Win32API or X11
...
```

**Comment by superdump** [comment]
Ah, I forgot that we have to revert a pkg-config related patch in -bad for X detection that breaks things for us. If you can wait a little I can find time to push up some fixes.

**Comment by superdump** [comment]
@vgottardi - try this: https://github.com/EricssonResearch/openwebrtc-build-scripts/pull/30

**Comment by vgottardi** [comment]
OK, that solved the missing libraries problem but I'm now getting some undefined symbols.
```
make[2]: Entering directory `/home/dev/openwebrtc/build/x86_64-unknown-linux/owr'
  GISCAN Owr-0.1.gir
./.libs/libopenwebrtc.so: undefined reference to `eglCreateWindowSurface'
./.libs/libopenwebrtc.so: undefined reference to `eglBindAPI'
./.libs/libopenwebrtc.so: undefined reference to `eglCreateContext'
./.libs/libopenwebrtc.so: undefined reference to `eglMakeCurrent'
./.libs/libopenwebrtc.so: undefined reference to `eglDestroySurface'
./.libs/libopenwebrtc.so: undefined reference to `eglGetDisplay'
./.libs/libopenwebrtc.so: undefined reference to `eglChooseConfig'
./.libs/libopenwebrtc.so: undefined reference to `eglInitialize'
./.libs/libopenwebrtc.so: undefined reference to `eglGetProcAddress'
./.libs/libopenwebrtc.so: undefined reference to `eglCreatePbufferSurface'
./.libs/libopenwebrtc.so: undefined reference to `eglQueryString'
./.libs/libopenwebrtc.so: undefined reference to `eglGetCurrentContext'
./.libs/libopenwebrtc.so: undefined reference to `eglDestroyContext'
./.libs/libopenwebrtc.so: undefined reference to `eglReleaseThread'
./.libs/libopenwebrtc.so: undefined reference to `eglSwapBuffers'
./.libs/libopenwebrtc.so: undefined reference to `eglGetError'
./.libs/libopenwebrtc.so: undefined reference to `eglTerminate'
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['/bin/bash', '../libtool', '--mode=link', '--tag=CC', '--silent', 'gcc', '-o', '/home/dev/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspect2lko65/Owr-0.1', '-export-dynamic', '-fPIC', '-I/home/dev/openwebrtc/openwebrtc-deps-x86_64-linux/include', '-I/home/dev/openwebrtc/framework', '-L/home/dev/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '-L/home/dev/openwebrtc/openwebrtc-deps-x86_64-linux/lib/gstreamer-1.0', '-L/home/dev/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '/home/dev/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspect2lko65/Owr-0.1.o', '-L.', 'libopenwebrtc.la', '-L/home/dev/.openwebrtc/lib', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0', '-lintl']' returned non-zero exit status 1
```

**Comment by superdump** [comment]
Install `libegl1-mesa-dev` and try again.

**Comment by uberguru** [comment]
bumped into the same problem, with libpulse applied your proposed fix and the meda-dev stuff mentioned. 

I built all the depedencies and the output seemed fine from each of the steps so im not sure what the final build script is looking for.... something i apparently dont have. 

Makefile.am:3: error: required directory ./client does not exist
Makefile.am:3: error: required directory ./seed does not exist
Makefile.am:3: error: required directory ./shared does not exist
Makefile.am:3: error: required directory ./worker does not exist
autoreconf: automake failed with exit status: 1
autogen.sh failed
Failed building....

**Comment by vgottardi** [comment]
I already had libegl1-mesa-dev installed as you suggested a few days ago. I think some component needs to link with the egl library, just don't know where. It could also be a library order problem.

**Comment by rishabhp** [comment]
Ubuntu 14.04 64bit - Tried everything mentioned but couldn't get past the `gl` errors. So I finally gave up after 10hrs of trying to build OpenWebRTC (on Mac first and then Ubuntu). Will probably come back later. If anyone is able to build the jar/so files for android then just let me know so that I can take them and at least test the NativeCall sample app (which is what I wanted to do in the first place).

**Comment by superdump** [comment]
@vgottardi @rishabhp And then this patch to openwebrtc itself and I am fairly confident the GL issue will be fixed : https://github.com/superdump/openwebrtc/commit/c7ec41870f0e031279ec1345c8ade697c05b8321

**Comment by rishabhp** [comment]
So I'll tell you what all I did (Ubuntu 14.04 64bit).

- Installed `sudo apt-get install libegl1-mesa-dev`.
- Applied the patch here - https://github.com/EricssonResearch/openwebrtc-build-scripts/pull/30 and executed `bootstrap/bootstrap.sh` till the point where it installs dependencies (`sudo apt-get install` thing) and also `./build-gst-plugins-bad.sh -r linux` and `./build-gst-plugins-bad.sh -r android` inside `scripts/dependencies`.
- Finally applied https://github.com/superdump/openwebrtc/commit/c7ec41870f0e031279ec1345c8ade697c05b8321 to the respective files and executed `./build.sh -r linux` which ended up with this dump (last few lines).

```bash
config.status: creating docs/reference/owr/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

Now type 'make' to compile this module.

patching file libtool
Hunk #1 succeeded at 5718 (offset 3 lines).
Hunk #2 succeeded at 5964 (offset 3 lines).
Hunk #3 succeeded at 6701 (offset 3 lines).
Hunk #4 succeeded at 6874 (offset 3 lines).
Hunk #5 succeeded at 6882 (offset 3 lines).
Hunk #6 succeeded at 7556 (offset 3 lines).
Hunk #7 succeeded at 8452 (offset 3 lines).
Hunk #8 succeeded at 9182 (offset 3 lines).
make  all-recursive
make[1]: Entering directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux'
Making all in transport
make[2]: Entering directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux/transport'
make[2]: Leaving directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux/transport'
Making all in local
make[2]: Entering directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux/local'
make[2]: Leaving directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux/local'
Making all in owr
make[2]: Entering directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux/owr'
  CCLD     libopenwebrtc.la
/usr/bin/ld: cannot find -lgstopengl
/usr/bin/ld: cannot find -lgstgl-1.0
collect2: error: ld returned 1 exit status
make[2]: *** [libopenwebrtc.la] Error 1
make[2]: Leaving directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux/owr'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux'
make: *** [all] Error 2
Failed building....
```

Not sure what I might have missed.

**Comment by superdump** [comment]
I would recommend using -Cbr instead of just -r.

However, in scripts/dependencies, after you have built gst-plugins-bad, you need to run the following:
```
rm -rf openwebrtc-deps-* ../../openwebrtc-deps-*
./create_file_release.sh linux
./create_file_release.sh android
./deploy_deps.sh
```

Then you should be able to change directory up to openwebrtc and `./build.sh -Cbr linux android`

**Comment by rishabhp** [comment]
@superdump Aah, so I missed `./deploy_deps.sh`. I did what you said (although note `./create_file_release.sh...` is not mentioned in the [wiki](https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC)).

Although this time it failed again with the following dump:

```bash
Making all in local
make[2]: Entering directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux/local'
  CC       owr_local.lo
  CC       owr_local_media_source.lo
  CC       owr_media_renderer.lo
  CC       owr_audio_renderer.lo
  CC       owr_video_renderer.lo
  CC       owr_image_renderer.lo
  CC       owr_image_server.lo
  CC       owr_window_registry.lo
  CC       owr_device_list.lo
  OBJCLD   libopenwebrtc_local.la
make[2]: Leaving directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux/local'
Making all in owr
make[2]: Entering directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux/owr'
  CC       owr.lo
  CC       owr_types.lo
  CC       owr_media_source.lo
  CC       owr_utils.lo
python /home/rishabh/openwebrtc/owr/symbols_to_source.py /home/rishabh/openwebrtc/libopenwebrtc.exp owr_require_symbols.c
  CC       owr_require_symbols.lo
  CCLD     libopenwebrtc.la
  GISCAN Owr-0.1.gir
./.libs/libopenwebrtc.so: undefined reference to `eglCreateWindowSurface'
./.libs/libopenwebrtc.so: undefined reference to `eglBindAPI'
./.libs/libopenwebrtc.so: undefined reference to `eglCreateContext'
./.libs/libopenwebrtc.so: undefined reference to `eglMakeCurrent'
./.libs/libopenwebrtc.so: undefined reference to `eglDestroySurface'
./.libs/libopenwebrtc.so: undefined reference to `eglGetDisplay'
./.libs/libopenwebrtc.so: undefined reference to `eglChooseConfig'
./.libs/libopenwebrtc.so: undefined reference to `eglInitialize'
./.libs/libopenwebrtc.so: undefined reference to `eglGetProcAddress'
./.libs/libopenwebrtc.so: undefined reference to `eglCreatePbufferSurface'
./.libs/libopenwebrtc.so: undefined reference to `eglQueryString'
./.libs/libopenwebrtc.so: undefined reference to `eglGetCurrentContext'
./.libs/libopenwebrtc.so: undefined reference to `eglDestroyContext'
./.libs/libopenwebrtc.so: undefined reference to `eglReleaseThread'
./.libs/libopenwebrtc.so: undefined reference to `eglSwapBuffers'
./.libs/libopenwebrtc.so: undefined reference to `eglGetError'
./.libs/libopenwebrtc.so: undefined reference to `eglTerminate'
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['/bin/bash', '../libtool', '--mode=link', '--tag=CC', '--silent', 'gcc', '-o', '/home/rishabh/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspectSOy3bE/Owr-0.1', '-export-dynamic', '-fPIC', '-I/home/rishabh/openwebrtc/openwebrtc-deps-x86_64-linux/include', '-I/home/rishabh/openwebrtc/framework', '-L/home/rishabh/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '-L/home/rishabh/openwebrtc/openwebrtc-deps-x86_64-linux/lib/gstreamer-1.0', '-L/home/rishabh/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '/home/rishabh/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspectSOy3bE/Owr-0.1.o', '-L.', 'libopenwebrtc.la', '-L/home/rishabh/.openwebrtc/lib', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0', '-lintl']' returned non-zero exit status 1
make[2]: *** [Owr-0.1.gir] Error 1
make[2]: Leaving directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux/owr'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/rishabh/openwebrtc/build/x86_64-unknown-linux'
make: *** [all] Error 2
Failed building....
```

Similar to what @vgottardi faced.

**Comment by VenkataPraneethT** [comment]
Hi, I too faced the same issue. I followed all the suggestions, but still couldn't get it working. Below is the error that I get, similar to the one that everyone is facing:

./.libs/libopenwebrtc.so: undefined reference to `eglGetError'
./.libs/libopenwebrtc.so: undefined reference to `eglTerminate'
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['/bin/bash', '../libtool', '--mode=link', '--tag=CC', '--silent', 'gcc', '-o', '/home/praneeth/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspectbbbG3I/Owr-0.1', '-export-dynamic', '-fPIC', '-I/home/praneeth/openwebrtc/openwebrtc-deps-x86_64-linux/include', '-I/home/praneeth/openwebrtc/framework', '-L/home/praneeth/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '-L/home/praneeth/openwebrtc/openwebrtc-deps-x86_64-linux/lib/gstreamer-1.0', '-L/home/praneeth/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '/home/praneeth/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspectbbbG3I/Owr-0.1.o', '-L.', 'libopenwebrtc.la', '-L/home/praneeth/.openwebrtc/lib', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0', '-lintl']' returned non-zero exit status 1
make[2]: *** [Owr-0.1.gir] Error 1
make[2]: Leaving directory `/home/praneeth/openwebrtc/build/x86_64-unknown-linux/owr'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/praneeth/openwebrtc/build/x86_64-unknown-linux'
make: *** [all] Error 2
Failed building....

**Comment by vgottardi** [comment]
I added "-lEGL" to PLATFORM_GSTREAMER_LIBS in the linux section in build.sh. That solved the eglXxxx undefined symbols. 

I got one more undefined symbol later on. Adding "-lm" took care of that. With these changes, the build completes.

**Comment by VenkataPraneethT** [comment]
Thank you @vgottardi . I too followed your suggestions of adding "-lEGL" and "-lm" to PLATFORM_GSTREAMER_LIBS . That solved the problem and the build is now successful.

**Comment by rishabhp** [comment]
@vgottardi @VenkataPraneethT Would you guys want to make the built files available publicly so that I can download and quickly test the NativeCall sample app? Unfortunately I had ended up deleting my openwebrtc folder where I had executed the build process. Re-doing that means again a lot of time consumed.

**Comment by sdroege** [comment]
Instead of that it would also work to use --disable-egl on Linux for gst-plugins-bad. It's not needed or used by Owr.

**Comment by KerwinMa** [comment]
Thank you @vgottardi . I did the same and I don't have the issue now.
 export PLATFORM_GSTREAMER_LIBS="-lgstvideoconvert -lgstpulse -lgstvideo4linux2 -lX11 -lXv -lgstallocators-1.0 -lGLU -lGL -lEGL -lm"
But I have another issue, which happens on Mac(#29) as well:
configure: error: in `/home/kerwin/Documents/openwebrtc/build/arm-linux-androideabi':
configure: error: C compiler cannot create executables


configure:3194: $? = 0
configure:3183: /home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/third_party/android_tools/ndk/platforms/android-9/arch-arm/ -fuse-ld=gold -v >&5
Using built-in specs.
COLLECT_GCC=/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
COLLECT_LTO_WRAPPER=/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/chromium/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../libexec/gcc/arm-linux-androideabi/4.8/lto-wrapper
Target: arm-linux-androideabi
Configured with: /s/ndk-toolchain/src/build/../gcc/gcc-4.8/configure --prefix=/tmp/ndk-andrewhsieh/build/toolchain/prefix --target=arm-linux-androideabi --host=x86_64-linux-gnu --build=x86_64-linux-gnu --with-gnu-as --with-gnu-ld --enable-languages=c,c++ --with-gmp=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --with-mpfr=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --with-mpc=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --with-cloog=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --with-isl=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --with-ppl=/tmp/ndk-andrewhsieh/build/toolchain/temp-install --disable-ppl-version-check --disable-cloog-version-check --disable-isl-version-check --enable-cloog-backend=isl --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --disable-libssp --enable-threads --disable-nls --disable-libmudflap --disable-libgomp --disable-libstdc__-v3 --disable-sjlj-exceptions --disable-shared --disable-tls --disable-libitm --with-float=soft --with-fpu=vfp --with-arch=armv5te --enable-target-optspace --enable-initfini-array --disable-nls --prefix=/tmp/ndk-andrewhsieh/build/toolchain/prefix --with-sysroot=/tmp/ndk-andrewhsieh/build/toolchain/prefix/sysroot --with-binutils-version=2.24 --with-mpfr-version=3.1.1 --with-mpc-version=1.0.1 --with-gmp-version=5.0.5 --with-gcc-version=4.8 --with-gdb-version=7.6 --with-python=/usr/local/google/home/andrewhsieh/mydroid/ndk/prebuilt/linux-x86_64/bin/python-config.sh --with-gxx-include-dir=/tmp/ndk-andrewhsieh/build/toolchain/prefix/include/c++/4.8 --with-bugurl=http://source.android.com/source/report-bugs.html --disable-bootstrap --disable-libquadmath --enable-plugins --enable-libgomp --disable-libsanitizer --enable-gold --enable-graphite=yes --with-cloog-version=0.18.0 --with-isl-version=0.11.1 --enable-eh-frame-hdr-for-static --with-arch=armv5te --program-transform-name='s&^&arm-linux-androideabi-&' --enable-gold=default
Thread model: posix
gcc version 4.8 (GCC) 
configure:3194: $? = 0
configure:3183: /home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/third_party/android_tools/ndk/platforms/android-9/arch-arm/ -fuse-ld=gold -V >&5
arm-linux-androideabi-gcc: error: unrecognized command line option '-V'
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
configure:3194: $? = 1
configure:3183: /home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/third_party/android_tools/ndk/platforms/android-9/arch-arm/ -fuse-ld=gold -qversion >&5
arm-linux-androideabi-gcc: error: unrecognized command line option '-qversion'
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
configure:3194: $? = 1
configure:3214: checking whether the C compiler works
configure:3236: /home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc --sysroot=/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/third_party/android_tools/ndk/platforms/android-9/arch-arm/ -fuse-ld=gold -march=armv7-a -mfloat-abi=softfp -mfpu=neon -Wl,--fix-cortex-a8 -I/home/kerwin/Documents/openwebrtc/openwebrtc-deps-armv7-android/include -I/home/kerwin/Documents/openwebrtc/framework -march=armv7-a -mfloat-abi=softfp -mfpu=neon -Wl,--fix-cortex-a8 -I/home/kerwin/Documents/openwebrtc/openwebrtc-deps-armv7-android/include -I/home/kerwin/Documents/openwebrtc/framework -L/home/kerwin/Documents/openwebrtc/openwebrtc-deps-armv7-android/lib -L/home/kerwin/Documents/openwebrtc/openwebrtc-deps-armv7-android/lib/gstreamer-1.0 -L/home/kerwin/Documents/openwebrtc/openwebrtc-deps-armv7-android/lib -llog -Wl,--allow-multiple-definition -landroid  conftest.c  >&5
/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/chromium/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot open crtbegin_dynamic.o: No such file or directory
/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/chromium/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot open crtend_android.o: No such file or directory
/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/chromium/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot find -llog
/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/chromium/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot find -landroid
/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/chromium/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot find -lc
/home/kerwin/Documents/webrtc-build-scripts/android/webrtc/src/chromium/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld.gold: error: cannot find -ldl
collect2: error: ld returned 1 exit status
configure:3240: $? = 1
configure:3278: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "openwebrtc"
| #define PACKAGE_TARNAME "openwebrtc"
| #define PACKAGE_VERSION "0.1"
| #define PACKAGE_STRING "openwebrtc 0.1"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "openwebrtc"
| #define VERSION "0.1"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3283: error: in `/home/kerwin/Documents/openwebrtc/build/arm-linux-androideabi':
configure:3285: error: C compiler cannot create executables
See `config.log' for more details

**Comment by superdump** [comment]
@sdroege - so what packages do we need to add to bootstrap for GLX? And then we need to add --disable-egl and remove all EGL references for Linux targets from the build scripts. Right? Is this all correct in cerbero? If so, I guess we don't need to spend time on this.

**Comment by sdroege** [comment]
For GLX you also just need mesa, nothing special. Yes to everything else, except cerbero (I don't know).

**Comment by superdump** [comment]
This issue is also noted in https://github.com/EricssonResearch/openwebrtc/issues/158

**Comment by VenkataPraneethT** [comment]
Hi,

I have done fresh build for openwebrtc in linux and used all the above mentioned suggestions. I am not getting any opengl issues. However i get different error, below is the error. Could you suggest help regarding this.

CCLD     libopenwebrtc.la
  GISCAN Owr-0.1.gir
./.libs/libopenwebrtc.so: undefined reference to `eglCreateWindowSurface'
./.libs/libopenwebrtc.so: undefined reference to `eglBindAPI'
./.libs/libopenwebrtc.so: undefined reference to `eglCreateContext'
./.libs/libopenwebrtc.so: undefined reference to `eglMakeCurrent'
./.libs/libopenwebrtc.so: undefined reference to `eglDestroySurface'
./.libs/libopenwebrtc.so: undefined reference to `eglGetDisplay'
./.libs/libopenwebrtc.so: undefined reference to `eglChooseConfig'
./.libs/libopenwebrtc.so: undefined reference to `eglInitialize'
./.libs/libopenwebrtc.so: undefined reference to `eglGetProcAddress'
./.libs/libopenwebrtc.so: undefined reference to `eglCreatePbufferSurface'
./.libs/libopenwebrtc.so: undefined reference to `eglQueryString'
./.libs/libopenwebrtc.so: undefined reference to `eglGetCurrentContext'
./.libs/libopenwebrtc.so: undefined reference to `eglDestroyContext'
./.libs/libopenwebrtc.so: undefined reference to `eglReleaseThread'
./.libs/libopenwebrtc.so: undefined reference to `eglSwapBuffers'
./.libs/libopenwebrtc.so: undefined reference to `eglGetError'
./.libs/libopenwebrtc.so: undefined reference to `eglTerminate'
./.libs/libopenwebrtc.so: undefined reference to `SSL_CTX_set_ecdh_auto'
collect2: error: ld returned 1 exit status
linking of temporary binary failed: Command '['/bin/bash', '../libtool', '--mode=link', '--tag=CC', '--silent', 'gcc', '-o', '/home/praneeth/openwebrtctest/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspectelw1qJ/Owr-0.1', '-export-dynamic', '-fPIC', '-I/home/praneeth/openwebrtctest/openwebrtc/openwebrtc-deps-x86_64-linux/include', '-I/home/praneeth/openwebrtctest/openwebrtc/framework', '-L/home/praneeth/openwebrtctest/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '-L/home/praneeth/openwebrtctest/openwebrtc/openwebrtc-deps-x86_64-linux/lib/gstreamer-1.0', '-L/home/praneeth/openwebrtctest/openwebrtc/openwebrtc-deps-x86_64-linux/lib', '/home/praneeth/openwebrtctest/openwebrtc/build/x86_64-unknown-linux/owr/tmp-introspectelw1qJ/Owr-0.1.o', '-L.', 'libopenwebrtc.la', '-L/home/praneeth/.openwebrtc/lib', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0', '-lintl']' returned non-zero exit status 1
make[2]: *** [Owr-0.1.gir] Error 1
make[2]: Leaving directory `/home/praneeth/openwebrtctest/openwebrtc/build/x86_64-unknown-linux/owr'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/praneeth/openwebrtctest/openwebrtc/build/x86_64-unknown-linux'
make: *** [all] Error 2
Failed building....

**Comment by lgrahl** [comment]
Same problem here.

**Comment by superdump** [comment]
We have moved to the cerbero build system. Please try building using that:

https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

Create new issues if you have any problems and we will address them. Thanks for the reports! :smile:
